Tonatiuh: NormalVector.cpp File Reference
NormalVector.cpp File Reference
Functions
NormalVector operator- (const NormalVector &normal)
NormalVector operator+ (const NormalVector &lhs, const NormalVector &rhs)
NormalVector operator- (const NormalVector &lhs, const NormalVector &rhs)
NormalVector operator* (const NormalVector &normal, double scalar)
NormalVector operator* (double scalar, const NormalVector &normal)
NormalVector operator/ (const NormalVector &normal, double scalar)
std::ostream & operator<< (std::ostream &os, const NormalVector &normal)
double DotProduct (const NormalVector &nA, const NormalVector &nB)
double AbsDotProduct (const NormalVector &nA, const NormalVector &nB)
NormalVector Normalize (const NormalVector &n)
Function Documentation
double AbsDotProduct (const NormalVector & nA, const NormalVector & nB)
References DotProduct().
double DotProduct (const NormalVector & nA, const NormalVector & nB)
References NormalVector::x, NormalVector::y, and NormalVector::z.
Referenced by AbsDotProduct().
NormalVector Normalize (const NormalVector & n)
References NormalVector::Length().
Referenced by DifferentialGeometry::DifferentialGeometry(), LookAt(), and Rotate().
NormalVector operator* (double scalar, const NormalVector & normal)
References NormalVector::x, NormalVector::y, and NormalVector::z.
NormalVector operator* (const NormalVector & normal, double scalar)
References NormalVector::x, NormalVector::y, and NormalVector::z.
NormalVector operator+ (const NormalVector & lhs, const NormalVector & rhs)
References NormalVector::x, NormalVector::y, and NormalVector::z.
NormalVector operator- (const NormalVector & lhs, const NormalVector & rhs)
References NormalVector::x, NormalVector::y, and NormalVector::z.
NormalVector operator- (const NormalVector & normal)
References NormalVector::x, NormalVector::y, and NormalVector::z.
NormalVector operator/ (const NormalVector & normal, double scalar)
References NormalVector::x, NormalVector::y, and NormalVector::z.
std::ostream& operator<< (std::ostream & os, const NormalVector & normal)
References NormalVector::x, NormalVector::y, and NormalVector::z.