Tonatiuh: MersenneTwister Class Reference
MersenneTwister Class Reference
Public Member Functions
MersenneTwister (unsigned long seedValue=5489UL, long int randomNumberArraySize=1000000)
MersenneTwister (const unsigned long *seedArray, int seedArraySize, long int randomNumberArraySize=1000000)
virtual ~MersenneTwister ()
void FillArray (double *array, const unsigned long arraySize)
unsigned long RandomUInt ()
Private Types
enum { N = 624, M = 397 }
Private Member Functions
void Seed (unsigned long seedValue)
void Seed (const unsigned long *seedArray, int arraySize)
unsigned long int RandomInteger ()
double Random01 ()
unsigned long Twiddle (unsigned long u, unsigned long v)
void GenerateNewState ()
MersenneTwister (const MersenneTwister &)
void operator= (const MersenneTwister &)
Private Attributes
unsigned long m_state [N]
int m_p
bool m_init
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
N
M
Constructor & Destructor Documentation
MersenneTwister::MersenneTwister (unsigned long seedValue = 5489UL, long int randomNumberArraySize = 1000000) [inline]
References m_init, and Seed().
MersenneTwister::MersenneTwister (const unsigned long * seedArray, int seedArraySize, long int randomNumberArraySize = 1000000) [inline]
References m_init, and Seed().
MersenneTwister::~MersenneTwister () [inline, virtual]
MersenneTwister::MersenneTwister (const MersenneTwister &) [private]
Member Function Documentation
void MersenneTwister::FillArray (double * array, const unsigned long arraySize) [inline, virtual]
Implements RandomDeviate.
References Random01().
void MersenneTwister::GenerateNewState () [private]
References M, m_p, m_state, N, and Twiddle().
Referenced by RandomInteger().
void MersenneTwister::operator= (const MersenneTwister &) [private]
double MersenneTwister::Random01 () [inline, private]
References LongIntegerToDouble, and RandomInteger().
Referenced by FillArray().
unsigned long int MersenneTwister::RandomInteger () [inline, private]
References GenerateNewState(), m_p, m_state, and N.
Referenced by Random01(), and RandomUInt().
unsigned long MersenneTwister::RandomUInt ()
References RandomInteger().
void MersenneTwister::Seed (const unsigned long * seedArray, int arraySize) [private]
References m_p, m_state, N, and Seed().
void MersenneTwister::Seed (unsigned long seedValue) [private]
References m_p, m_state, and N.
Referenced by MersenneTwister(), and Seed().
unsigned long MersenneTwister::Twiddle (unsigned long u, unsigned long v) [inline, private]
Referenced by GenerateNewState().
Member Data Documentation
bool MersenneTwister::m_init [private]
Referenced by MersenneTwister().
int MersenneTwister::m_p [private]
Referenced by GenerateNewState(), RandomInteger(), and Seed().
unsigned long MersenneTwister::m_state[N] [private]
Referenced by GenerateNewState(), RandomInteger(), and Seed().
The documentation for this class was generated from the following files:
MersenneTwister.h
MersenneTwister.cpp