######################################################################
# Automatically generated by qmake (2.01a) mi� 7. feb 13:18:07 2007
######################################################################

TEMPLATE      = lib
CONFIG       += plugin debug_and_release


INCLUDEPATH += . \
				src \
				$$(TONATIUH_ROOT)/src \
				$$(TDE_ROOT)/local/include
					
win32{
	DEFINES+= COIN_DLL SOQT_DLL	
}


# Input
HEADERS = *.h \
           	$$(TONATIUH_ROOT)/src/Trace.h \
           	$$(TONATIUH_ROOT)/src/TSunShape.h 


SOURCES = *.cpp \
           	$$(TONATIUH_ROOT)/src/Trace.cpp \
           	$$(TONATIUH_ROOT)/src/TSunShape.cpp

RESOURCES += SunshapePillbox.qrc	


DESTDIR       = $$(TONATIUH_ROOT)/plugins/SunshapePillbox	
TARGET        = SunshapePillbox

contains(TEMPLATE,lib) {  
	CONFIG(debug, debug|release) {
		DESTDIR       = $$(TONATIUH_ROOT)/bin/debug/plugins/SunshapePillbox	
		unix {
			LIBS +=-L$$(TDE_ROOT)/local/lib -lCoin_debug -lSoQt_debug
			TARGET = $$member(TARGET, 0)_debug
		}
		else {
			LIBS +=-L$$(TDE_ROOT)/local/lib -lCoind -lSoQtd
			TARGET = $$member(TARGET, 0)d
		}
	}
	else { 
		LIBS +=-L$$(TDE_ROOT)/local/lib -lCoin -lSoQt
		DESTDIR       = $$(TONATIUH_ROOT)/bin/release/plugins/SunshapePillbox
	}
}
