######################################################################
# Automatically generated by qmake (2.01a) mi� 7. feb 13:18:07 2007
######################################################################

TEMPLATE      = lib
CONFIG       += plugin debug_and_release
unix{
	INCLUDEPATH += 	. \
					../Tonatiuh/src\ 
					src
}

win32{
DEFINES+= COIN_DLL SOQT_DLL
INCLUDEPATH += . \
				src \
				../Tonatiuh/src\ 
				C:/msys/usr/local/include 
}

# Input
HEADERS = *.h \
           	../Tonatiuh/src/Trace.h \
           	../Tonatiuh/src/TSunShape.h 


SOURCES = *.cpp \
           	../Tonatiuh/src/Trace.cpp \
           	../Tonatiuh/src/TSunShape.cpp

RESOURCES += SunshapePillbox.qrc	

win32	{
	LIBS += -L"c:\msys\usr\local\lib" -lmingw32 -lqtmain  -lSoQt -lCoin -lopengl32
	DESTDIR  = ..\Tonatiuh\release\plugins\SunshapePillbox
}

unix	{
	LIBS +=-L/usr/local/lib -lCoin -lSoQt
	DESTDIR       = ../Tonatiuh/release/plugins/SunshapePillbox
}
	
TARGET        = SunshapePillbox
    contains(TEMPLATE,lib) {
    
       CONFIG(debug, debug|release) {
       
          unix	{
          	DESTDIR       = ../Tonatiuh/debug/plugins/SunshapePlugins/SunshapePillbox
          	TARGET = $$member(TARGET, 0)_debug
          	
          }
          else:TARGET = $$member(TARGET, 0)d
       }
       
    }