Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/Normal.cpp File Reference
C:/eclipse/workspace/Tonatiuh/src/Normal.cpp File Reference
#include <cmath>
#include <cfloat>
#include "Normal.h"
#include "Vector3D.h"
Functions
Normal operator- (const Normal &normal)
Normal operator+ (const Normal &lhs, const Normal &rhs)
Normal operator- (const Normal &lhs, const Normal &rhs)
Normal operator* (const Normal &normal, double scalar)
Normal operator* (double scalar, const Normal &normal)
Normal operator/ (const Normal &normal, double scalar)
std::ostream & operator<< (std::ostream &os, const Normal &normal)
double DotProduct (const Normal &nA, const Normal &nB)
double AbsDotProduct (const Normal &nA, const Normal &nB)
Normal Normalize (const Normal &n)
Function Documentation
double AbsDotProduct (const Normal & nA, const Normal & nB)
Definition at line 173 of file Normal.cpp.
References DotProduct().
double DotProduct (const Normal & nA, const Normal & nB)
Definition at line 168 of file Normal.cpp.
References Normal::x, Normal::y, and Normal::z.
Referenced by AbsDotProduct().
Normal Normalize (const Normal & n)
Definition at line 178 of file Normal.cpp.
References Normal::Length().
Referenced by DifferentialGeometry::DifferentialGeometry(), LookAt(), and Rotate().
Normal operator* (double scalar, const Normal & normal)
Definition at line 151 of file Normal.cpp.
References Normal::Normal(), Normal::x, Normal::y, and Normal::z.
Normal operator* (const Normal & normal, double scalar)
Definition at line 146 of file Normal.cpp.
References Normal::Normal(), Normal::x, Normal::y, and Normal::z.
Normal operator+ (const Normal & lhs, const Normal & rhs)
Definition at line 136 of file Normal.cpp.
References Normal::Normal(), Normal::x, Normal::y, and Normal::z.
Normal operator- (const Normal & lhs, const Normal & rhs)
Definition at line 141 of file Normal.cpp.
References Normal::Normal(), Normal::x, Normal::y, and Normal::z.
Normal operator- (const Normal & normal)
Definition at line 131 of file Normal.cpp.
References Normal::Normal(), Normal::x, Normal::y, and Normal::z.
Normal operator/ (const Normal & normal, double scalar)
Definition at line 156 of file Normal.cpp.
References Normal::Normal(), Normal::x, Normal::y, and Normal::z.
std::ostream& operator<< (std::ostream & os, const Normal & normal)
Definition at line 162 of file Normal.cpp.
References Normal::x, Normal::y, and Normal::z.