Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/ParametersItem.cpp File Reference
C:/eclipse/workspace/Tonatiuh/src/ParametersItem.cpp File Reference
#include <QString>
#include <Inventor/SbString.h>
#include <Inventor/fields/SoField.h>
#include <Inventor/fields/SoSFString.h>
#include <Inventor/lists/SoFieldList.h>
#include <Inventor/sensors/SoFieldSensor.h>
#include "ParametersItem.h"
#include "Trace.h"
Functions
void updateItem (void *data, SoSensor *sensor)
Function Documentation
void updateItem (void * data, SoSensor * sensor)
Definition at line 55 of file ParametersItem.cpp.
References ParametersItem::data(), and ParametersItem::setData().
Referenced by ParametersItem::ParametersItem().