Tonatiuh: MapFrame Class Reference
MapFrame Class Reference
#include <MapFrame.h>
Signals
void positionChanged (double longitude, double latitude)
void positionSelected (double longitude, double latitude)
Public Member Functions
MapFrame (QWidget *parent=0)
~MapFrame ()
Protected Member Functions
void mousePressEvent (QMouseEvent *e)
void mouseMoveEvent (QMouseEvent *e)
Private Member Functions
QString Country (int x, int y)
Private Attributes
QImage * gray
QVector< QString > countries
Detailed Description
Definition at line 49 of file MapFrame.h.
Constructor & Destructor Documentation
MapFrame::MapFrame (QWidget * parent = 0)
Definition at line 51 of file MapFrame.cpp.
References countries, and gray.
MapFrame::~MapFrame ()
Definition at line 333 of file MapFrame.cpp.
Member Function Documentation
void MapFrame::mousePressEvent (QMouseEvent * e) [protected]
Definition at line 364 of file MapFrame.cpp.
References positionSelected().
void MapFrame::mouseMoveEvent (QMouseEvent * e) [protected]
Definition at line 338 of file MapFrame.cpp.
References Country(), and positionChanged().
void MapFrame::positionChanged (double longitude, double latitude) [signal]
Referenced by mouseMoveEvent().
void MapFrame::positionSelected (double longitude, double latitude) [signal]
Referenced by mousePressEvent().
QString MapFrame::Country (int x, int y) [private]
Definition at line 383 of file MapFrame.cpp.
References countries, and gray.
Referenced by mouseMoveEvent().
Member Data Documentation
QImage* MapFrame::gray [private]
Definition at line 69 of file MapFrame.h.
Referenced by Country(), and MapFrame().
QVector<QString> MapFrame::countries [private]
Definition at line 70 of file MapFrame.h.
Referenced by Country(), and MapFrame().
The documentation for this class was generated from the following files:
C:/eclipse/workspace/Tonatiuh/src/MapFrame.h
C:/eclipse/workspace/Tonatiuh/src/MapFrame.cpp