Tonatiuh: TShapeFactory Class Reference
TShapeFactory Class Reference
#include <TShapeFactory.h>
Public Member Functions
virtual ~TShapeFactory ()
virtual QString TShapeName () const =0
virtual QIcon TShapeIcon () const =0
virtual TShape * CreateTShape () const =0
virtual bool IsFlat ()=0
Detailed Description
Definition at line 53 of file TShapeFactory.h.
Constructor & Destructor Documentation
virtual TShapeFactory::~TShapeFactory () [inline, virtual]
Definition at line 56 of file TShapeFactory.h.
Member Function Documentation
virtual QString TShapeFactory::TShapeName () const [pure virtual]
Referenced by MainWindow::CreateShape(), and MainWindow::SetupActionInsertShape().
virtual QIcon TShapeFactory::TShapeIcon () const [pure virtual]
Referenced by MainWindow::SetupActionInsertShape().
virtual TShape* TShapeFactory::CreateTShape () const [pure virtual]
Referenced by SunDialog::changeShape(), MainWindow::CreateShape(), and MainWindow::LoadPlugins().
virtual bool TShapeFactory::IsFlat () [pure virtual]
Referenced by MainWindow::LoadPlugins().
The documentation for this class was generated from the following file:
C:/eclipse/workspace/Tonatiuh/src/TShapeFactory.h