Tonatiuh: SunPosDialog Class Reference
SunPosDialog Class Reference
#include <SunPosDialog.h>
Signals
void changeRepresentation (cSunCoordinates results)
void changeSunLight (QDateTime *time, double longitude, double latitude)
Public Member Functions
SunPosDialog (QWidget *parent=0)
~SunPosDialog ()
void ChangePosition (QDateTime time, double longitude, double latitude)
void setLongitude (int x)
void setLatitude (int y)
Private Slots
void on_updateButton_clicked ()
void CalculateSunPosition ()
void on_selectButton_clicked ()
Private Member Functions
QDateTime * GetTime ()
Detailed Description
Definition at line 33 of file SunPosDialog.h.
Constructor & Destructor Documentation
SunPosDialog::SunPosDialog (QWidget * parent = 0)
Definition at line 35 of file SunPosDialog.cpp.
References CalculateSunPosition(), and changeRepresentation().
SunPosDialog::~SunPosDialog ()
Definition at line 56 of file SunPosDialog.cpp.
Member Function Documentation
void SunPosDialog::ChangePosition (QDateTime time, double longitude, double latitude)
Definition at line 61 of file SunPosDialog.cpp.
void SunPosDialog::setLongitude (int x)
void SunPosDialog::setLatitude (int y)
void SunPosDialog::on_updateButton_clicked () [private, slot]
Definition at line 71 of file SunPosDialog.cpp.
References changeSunLight(), and GetTime().
void SunPosDialog::CalculateSunPosition () [private, slot]
Definition at line 81 of file SunPosDialog.cpp.
References changeRepresentation(), GetTime(), and sunpos().
Referenced by SunPosDialog().
void SunPosDialog::on_selectButton_clicked () [private, slot]
Definition at line 108 of file SunPosDialog.cpp.
References MapDialog::GetCoordinates(), tgc::Pi, and MapDialog::SetCoordinates().
void SunPosDialog::changeRepresentation (cSunCoordinates results) [signal]
Referenced by CalculateSunPosition(), and SunPosDialog().
void SunPosDialog::changeSunLight (QDateTime * time, double longitude, double latitude) [signal]
Referenced by on_updateButton_clicked().
QDateTime * SunPosDialog::GetTime () [private]
Definition at line 123 of file SunPosDialog.cpp.
Referenced by CalculateSunPosition(), and on_updateButton_clicked().
The documentation for this class was generated from the following files:
C:/eclipse/workspace/Tonatiuh/src/SunPosDialog.h
C:/eclipse/workspace/Tonatiuh/src/SunPosDialog.cpp