Tonatiuh: tgf Namespace Reference
tgf Namespace Reference
Functions
double RandomDouble ()
double Radians (double deg)
bool IsPowerOf2 (int v)
int Round2Int (double val)
int Log2Int (float v)
bool Quadratic (double A, double B, double C, double *t0, double *t1)
void ConcentricSampleDisk (double u1, double u2, double *dx, double *dy)
Vector3D CosineSampleHemisphere (double u1, double u2)
bool SameHemisphere (const Vector3D &w, const Vector3D &wp)
Vector3D UniformSampleHemisphere (double u1, double u2)
void SevereError (std::string errorMessage)
void Warning (std::string warningMessage)
double Clamp (double val, double low, double high)
int Clamp (int val, int low, int high)
double CosTheta (const Vector3D &w)
double SinTheta (const Vector3D &w)
double SinTheta2 (const Vector3D &w)
double CosPhi (const Vector3D &w)
double SinPhi (const Vector3D &w)
void BuildFileList (QDir parentDirectory, QStringList &fileList)
void TraceRay (Ray &ray, InstanceNode *instanceNode, PhotonMap &photonMap, RandomDeviate &rand)
bool IsOdd (int number)
double computeSigmaOptica (double sigmaSlope, double sigmaSpecularity)
SoSeparator * DrawPhotonMapPoints (const PhotonMap &map)
SoSeparator * DrawPhotonMapRays (const PhotonMap &map, unsigned long numberOfRays, double fraction)
double AlternateBoxMuller (RandomDeviate &rand)
void InitRand ()
void LatinHypercube (double *samples, int nSamples, int dims)
Function Documentation
double tgf::AlternateBoxMuller (RandomDeviate & rand)
Definition at line 407 of file tgf.cpp.
References RandomDeviate::RandomDouble().
void tgf::BuildFileList (QDir parentDirectory, QStringList & fileList)
Definition at line 252 of file tgf.cpp.
int tgf::Clamp (int val, int low, int high)
Definition at line 220 of file tgf.cpp.
double tgf::Clamp (double val, double low, double high)
Definition at line 213 of file tgf.cpp.
double tgf::computeSigmaOptica (double sigmaSlope, double sigmaSpecularity)
Definition at line 319 of file tgf.cpp.
void tgf::ConcentricSampleDisk (double u1, double u2, double * dx, double * dy)
Definition at line 128 of file tgf.cpp.
Referenced by CosineSampleHemisphere().
Vector3D tgf::CosineSampleHemisphere (double u1, double u2)
Definition at line 179 of file tgf.cpp.
References ConcentricSampleDisk(), Vector3D::x, Vector3D::y, and Vector3D::z.
double tgf::CosPhi (const Vector3D & w)
Definition at line 242 of file tgf.cpp.
References SinTheta(), and Vector3D::x.
double tgf::CosTheta (const Vector3D & w)
Definition at line 227 of file tgf.cpp.
References Vector3D::z.
Referenced by SinTheta2().
SoSeparator * tgf::DrawPhotonMapPoints (const PhotonMap & map)
Definition at line 326 of file tgf.cpp.
References PhotonMap::GetPhoton(), Photon::m_pos, PhotonMap::StoredPhotons(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by MainWindow::on_actionRayTraceRun_triggered().
SoSeparator * tgf::DrawPhotonMapRays (const PhotonMap & map, unsigned long numberOfRays, double fraction)
Definition at line 353 of file tgf.cpp.
References PhotonMap::GetPhoton(), Photon::m_next, Photon::m_pos, Photon::m_prev, PhotonMap::StoredPhotons(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by MainWindow::on_actionRayTraceRun_triggered().
void tgf::InitRand ()
bool tgf::IsOdd (int number)
Definition at line 312 of file tgf.cpp.
bool tgf::IsPowerOf2 (int v)
Definition at line 90 of file tgf.cpp.
void tgf::LatinHypercube (double * samples, int nSamples, int dims)
int tgf::Log2Int (float v)
Definition at line 107 of file tgf.cpp.
bool tgf::Quadratic (double A, double B, double C, double * t0, double * t1)
Definition at line 112 of file tgf.cpp.
References swap.
double tgf::Radians (double deg)
Definition at line 85 of file tgf.cpp.
References tgc::Pi.
double tgf::RandomDouble ()
Definition at line 72 of file tgf.cpp.
References RandomDeviate::RandomDouble().
int tgf::Round2Int (double val)
Definition at line 95 of file tgf.cpp.
References _doublemagicroundeps.
bool tgf::SameHemisphere (const Vector3D & w, const Vector3D & wp)
Definition at line 187 of file tgf.cpp.
void tgf::SevereError (std::string errorMessage)
Definition at line 202 of file tgf.cpp.
Referenced by CmdInsertMaterial::CmdInsertMaterial(), CmdInsertSeparatorKit::CmdInsertSeparatorKit(), CmdInsertShape::CmdInsertShape(), CmdInsertShapeKit::CmdInsertShapeKit(), CmdInsertTracker::CmdInsertTracker(), CmdLightPositionModified::CmdLightPositionModified(), CmdPaste::CmdPaste(), SceneModel::Cut(), TSquare::GetPoint3D(), SceneModel::IndexFromPath(), MainWindow::LoadPlugins(), MainWindow::on_actionDefine_SunLight_triggered(), SceneModel::Paste(), SceneModel::PathFromIndex(), PhotonMap::PhotonMap(), MainWindow::SetupActionInsertMaterial(), MainWindow::SetupDocument(), MainWindow::SetupGraphicView(), MainWindow::SetupParametersView(), MainWindow::SetupToolBars(), MainWindow::SetupTreeView(), and MainWindow::StartManipulation().
double tgf::SinPhi (const Vector3D & w)
Definition at line 247 of file tgf.cpp.
References SinTheta(), and Vector3D::y.
double tgf::SinTheta (const Vector3D & w)
Definition at line 232 of file tgf.cpp.
References Vector3D::z.
Referenced by CosPhi(), and SinPhi().
double tgf::SinTheta2 (const Vector3D & w)
Definition at line 237 of file tgf.cpp.
References CosTheta().
void tgf::TraceRay (Ray & ray, InstanceNode * instanceNode, PhotonMap & photonMap, RandomDeviate & rand)
Definition at line 271 of file tgf.cpp.
References InstanceNode::GetNode(), TSeparatorKit::Intersect(), Photon::m_next, Ray::maxt, Ray::origin, and PhotonMap::store().
Referenced by MainWindow::on_actionRayTraceRun_triggered().
Vector3D tgf::UniformSampleHemisphere (double u1, double u2)
Definition at line 192 of file tgf.cpp.
References tgc::Pi.
void tgf::Warning (std::string warningMessage)
Definition at line 208 of file tgf.cpp.