Tonatiuh: TMaterial Class Reference
TMaterial Class Reference
#include <TMaterial.h>
Public Member Functions
virtual QString getIcon ()=0
virtual Ray * GetReflectedRay (const Ray &incident, DifferentialGeometry *dg, RandomDeviate &rand) const =0
Static Public Member Functions
static void initClass ()
Protected Member Functions
TMaterial ()
virtual ~TMaterial ()
Private Member Functions
SO_NODE_ABSTRACT_HEADER (TMaterial)
Detailed Description
Definition at line 53 of file TMaterial.h.
Constructor & Destructor Documentation
TMaterial::TMaterial () [protected]
Definition at line 50 of file TMaterial.cpp.
TMaterial::~TMaterial () [protected, virtual]
Definition at line 56 of file TMaterial.cpp.
Member Function Documentation
TMaterial::SO_NODE_ABSTRACT_HEADER (TMaterial) [private]
void TMaterial::initClass () [static]
Reimplemented in TDefaultMaterial.
Definition at line 44 of file TMaterial.cpp.
Referenced by main().
virtual QString TMaterial::getIcon () [pure virtual]
Implemented in TDefaultMaterial.
Referenced by SceneModel::data().
virtual Ray* TMaterial::GetReflectedRay (const Ray & incident, DifferentialGeometry * dg, RandomDeviate & rand) const [pure virtual]
Implemented in TDefaultMaterial.
Referenced by TShapeKit::Intersect().
The documentation for this class was generated from the following files:
C:/eclipse/workspace/Tonatiuh/src/TMaterial.h
C:/eclipse/workspace/Tonatiuh/src/TMaterial.cpp