Tonatiuh: Ptr< T > Class Template Reference
Ptr< T > Class Template Reference
#include <Ptr.h>
Public Member Functions
Ptr (T *realPointer=0)
Ptr (const Ptr &rhs)
~Ptr ()
Ptr & operator= (const Ptr< T > &rhs)
Ptr & operator= (const T *&realPointer)
T * operator-> () const
T & operator* () const
operator bool () const
void ShowCount () const
Private Member Functions
void Init ()
Private Attributes
T * m_realPointer
Detailed Description
template<class T>
class Ptr< T >
Definition at line 43 of file Ptr.h.
Constructor & Destructor Documentation
template<class T> Ptr< T >::Ptr (T * realPointer = 0) [inline]
Definition at line 62 of file Ptr.h.
References Ptr< T >::Init().
template<class T> Ptr< T >::Ptr (const Ptr< T > & rhs) [inline]
Definition at line 69 of file Ptr.h.
References Ptr< T >::Init().
template<class T> Ptr< T >::~Ptr () [inline]
Definition at line 83 of file Ptr.h.
References Ptr< T >::m_realPointer.
Member Function Documentation
template<class T> Ptr< T > & Ptr< T >::operator= (const Ptr< T > & rhs) [inline]
Definition at line 89 of file Ptr.h.
References Ptr< T >::Init(), and Ptr< T >::m_realPointer.
template<class T> Ptr< T > & Ptr< T >::operator= (const T *& realPointer) [inline]
Definition at line 102 of file Ptr.h.
References Ptr< T >::Init(), and Ptr< T >::m_realPointer.
template<class T> T * Ptr< T >::operator-> () const [inline]
Definition at line 115 of file Ptr.h.
References Ptr< T >::m_realPointer.
template<class T> T & Ptr< T >::operator* () const [inline]
Definition at line 121 of file Ptr.h.
References Ptr< T >::m_realPointer.
template<class T> Ptr< T >::operator bool () const [inline]
Definition at line 53 of file Ptr.h.
template<class T> void Ptr< T >::ShowCount () const [inline]
Definition at line 127 of file Ptr.h.
References Ptr< T >::m_realPointer.
template<class T> void Ptr< T >::Init () [inline, private]
Definition at line 76 of file Ptr.h.
References Ptr< T >::m_realPointer.
Referenced by Ptr< T >::operator=(), and Ptr< T >::Ptr().
Member Data Documentation
template<class T> T* Ptr< T >::m_realPointer [private]
Definition at line 58 of file Ptr.h.
Referenced by Ptr< T >::Init(), Ptr< Matrix4x4 >::operator bool(), Ptr< T >::operator*(), Ptr< T >::operator->(), Ptr< T >::operator=(), Ptr< T >::ShowCount(), and Ptr< T >::~Ptr().
The documentation for this class was generated from the following file:
C:/eclipse/workspace/Tonatiuh/src/Ptr.h