Tonatiuh: SunPositionDialog Class Reference
SunPositionDialog Class Reference
Public Member Functions
SunPositionDialog (QWidget *parent=0)
~SunPositionDialog ()
double GetAzimuth ()
double GetDistance ()
double GetElevation ()
Constructor & Destructor Documentation
SunPositionDialog::SunPositionDialog (QWidget * parent = 0)
SunPositionDialog::~SunPositionDialog ()
Member Function Documentation
double SunPositionDialog::GetAzimuth ()
References tgc::Pi.
Referenced by MainWindow::on_actionDefineSunPosition_triggered().
double SunPositionDialog::GetDistance ()
Referenced by MainWindow::on_actionDefineSunPosition_triggered().
double SunPositionDialog::GetElevation ()
References tgc::Pi.
Referenced by MainWindow::on_actionDefineSunPosition_triggered().
The documentation for this class was generated from the following files:
SunPositionDialog.h
SunPositionDialog.cpp