Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/Point3D.cpp File Reference
C:/eclipse/workspace/Tonatiuh/src/Point3D.cpp File Reference
#include "Point3D.h"
#include "Vector3D.h"
Functions
Point3D operator+ (const Point3D &lhs, const Point3D &rhs)
Point3D operator+ (const Point3D &lhs, const Vector3D &rhs)
Vector3D operator- (const Point3D &lhs, const Point3D &rhs)
Point3D operator- (const Point3D &lhs, const Vector3D &rhs)
Point3D operator* (const Point3D &point, double scalar)
Point3D operator* (double scalar, const Point3D &point)
Point3D operator/ (const Point3D &point, double scalar)
std::ostream & operator<< (std::ostream &os, const Point3D &pA)
double Distance (const Point3D &pA, const Point3D &pB)
double DistanceSquared (const Point3D &pA, const Point3D &pB)
Function Documentation
double Distance (const Point3D & pA, const Point3D & pB)
Definition at line 158 of file Point3D.cpp.
Referenced by BBox::BoundingSphere(), and PhotonMap::fluxAtPoint().
double DistanceSquared (const Point3D & pA, const Point3D & pB)
Definition at line 163 of file Point3D.cpp.
Referenced by PhotonMap::locatePhotons().
Point3D operator* (double scalar, const Point3D & point)
Definition at line 141 of file Point3D.cpp.
References Point3D::Point3D(), Point3D::x, Point3D::y, and Point3D::z.
Point3D operator* (const Point3D & point, double scalar)
Definition at line 136 of file Point3D.cpp.
References Point3D::Point3D(), Point3D::x, Point3D::y, and Point3D::z.
Point3D operator+ (const Point3D & lhs, const Vector3D & rhs)
Definition at line 121 of file Point3D.cpp.
References Point3D::Point3D(), Vector3D::x, Point3D::x, Vector3D::y, Point3D::y, Vector3D::z, and Point3D::z.
Point3D operator+ (const Point3D & lhs, const Point3D & rhs)
Definition at line 116 of file Point3D.cpp.
References Point3D::Point3D(), Point3D::x, Point3D::y, and Point3D::z.
Point3D operator- (const Point3D & lhs, const Vector3D & rhs)
Definition at line 131 of file Point3D.cpp.
References Point3D::Point3D(), Vector3D::x, Point3D::x, Vector3D::y, Point3D::y, Vector3D::z, and Point3D::z.
Vector3D operator- (const Point3D & lhs, const Point3D & rhs)
Definition at line 126 of file Point3D.cpp.
References Point3D::x, Point3D::y, and Point3D::z.
Point3D operator/ (const Point3D & point, double scalar)
Definition at line 146 of file Point3D.cpp.
References Point3D::Point3D(), Point3D::x, Point3D::y, and Point3D::z.
std::ostream& operator<< (std::ostream & os, const Point3D & pA)
Definition at line 152 of file Point3D.cpp.
References Point3D::x, Point3D::y, and Point3D::z.