Tonatiuh: TTrackerFactory Class Reference
TTrackerFactory Class Reference
#include <TTrackerFactory.h>
Public Member Functions
virtual ~TTrackerFactory ()
virtual QString TTrackerName () const =0
virtual QIcon TTrackerIcon () const =0
virtual TTracker * CreateTTracker () const =0
Detailed Description
Definition at line 48 of file TTrackerFactory.h.
Constructor & Destructor Documentation
virtual TTrackerFactory::~TTrackerFactory () [inline, virtual]
Definition at line 51 of file TTrackerFactory.h.
Member Function Documentation
virtual QString TTrackerFactory::TTrackerName () const [pure virtual]
Referenced by MainWindow::CreateTracker(), and MainWindow::SetupActionInsertTracker().
virtual QIcon TTrackerFactory::TTrackerIcon () const [pure virtual]
Referenced by MainWindow::SetupActionInsertTracker().
virtual TTracker* TTrackerFactory::CreateTTracker () const [pure virtual]
Referenced by MainWindow::CreateTracker(), and MainWindow::LoadPlugins().
The documentation for this class was generated from the following file:
C:/eclipse/workspace/Tonatiuh/src/TTrackerFactory.h