Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/sunpos.h File Reference
C:/eclipse/workspace/Tonatiuh/src/sunpos.h File Reference
Classes
struct cTime
struct cLocation
struct cSunCoordinates
Defines
#define pi 3.14159265358979323846
#define twopi (2*pi)
#define rad (pi/180)
#define dEarthMeanRadius 6371.01
#define dAstronomicalUnit 149597890
Functions
void sunpos (cTime udtTime, cLocation udtLocation, cSunCoordinates *udtSunCoordinates)
Define Documentation
#define dAstronomicalUnit 149597890
Definition at line 52 of file sunpos.h.
Referenced by sunpos().
#define dEarthMeanRadius 6371.01
Definition at line 51 of file sunpos.h.
Referenced by sunpos().
#define pi 3.14159265358979323846
Definition at line 48 of file sunpos.h.
#define rad (pi/180)
Definition at line 50 of file sunpos.h.
Referenced by sunpos().
#define twopi (2*pi)
Definition at line 49 of file sunpos.h.
Referenced by sunpos().
Function Documentation
void sunpos (cTime udtTime, cLocation udtLocation, cSunCoordinates * udtSunCoordinates)
Definition at line 47 of file sunpos.cpp.
References dAstronomicalUnit, cSunCoordinates::dAzimuth, dEarthMeanRadius, cTime::dHours, cSunCoordinates::dJuliano, cLocation::dLatitude, cLocation::dLongitude, cTime::dMinutes, cTime::dSeconds, cSunCoordinates::dZenithAngle, cTime::iDay, cTime::iMonth, cTime::iYear, rad, and twopi.
Referenced by SunPosDialog::CalculateSunPosition(), TLightKit::ChangePosition(), MainWindow::on_actionSunPosition_triggered(), and SunDialog::SetAngles().