Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/sunpos.cpp File Reference
C:/eclipse/workspace/Tonatiuh/src/sunpos.cpp File Reference
#include "sunpos.h"
#include <math.h>
Functions
void sunpos (cTime udtTime, cLocation udtLocation, cSunCoordinates *udtSunCoordinates)
Function Documentation
void sunpos (cTime udtTime, cLocation udtLocation, cSunCoordinates * udtSunCoordinates)
Definition at line 47 of file sunpos.cpp.
References dAstronomicalUnit, cSunCoordinates::dAzimuth, dEarthMeanRadius, cTime::dHours, cSunCoordinates::dJuliano, cLocation::dLatitude, cLocation::dLongitude, cTime::dMinutes, cTime::dSeconds, cSunCoordinates::dZenithAngle, cTime::iDay, cTime::iMonth, cTime::iYear, rad, and twopi.
Referenced by SunPosDialog::CalculateSunPosition(), TLightKit::ChangePosition(), MainWindow::on_actionSunPosition_triggered(), and SunDialog::SetAngles().