Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/MainWindow.cpp File Reference
C:/eclipse/workspace/Tonatiuh/src/MainWindow.cpp File Reference
#include <QCloseEvent>
#include <QFileDialog>
#include <QItemSelectionModel>
#include <QItemSelection>
#include <QList>
#include <QLineEdit>
#include <QMenu>
#include <QMessageBox>
#include <QPluginLoader>
#include <QProgressDialog>
#include <QSettings>
#include <QString>
#include <QTextStream>
#include <QTime>
#include <QUndoStack>
#include <QUndoView>
#include <Inventor/SbBox.h>
#include <Inventor/SbString.h>
#include <Inventor/SbLinear.h>
#include <Inventor/SoOutput.h>
#include <Inventor/SoPickedPoint.h>
#include <Inventor/actions/SoBoxHighlightRenderAction.h>
#include <Inventor/actions/SoGetBoundingBoxAction.h>
#include <Inventor/actions/SoGetMatrixAction.h>
#include <Inventor/actions/SoRayPickAction.h>
#include <Inventor/actions/SoSearchAction.h>
#include <Inventor/draggers/SoDragger.h>
#include <Inventor/engines/SoGate.h>
#include <Inventor/events/SoMouseButtonEvent.h>
#include <Inventor/fields/SoFieldContainer.h>
#include <Inventor/lists/SoPickedPointList.h>
#include <Inventor/manips/SoTransformManip.h>
#include <Inventor/manips/SoCenterballManip.h>
#include <Inventor/manips/SoHandleBoxManip.h>
#include <Inventor/manips/SoJackManip.h>
#include <Inventor/manips/SoTabBoxManip.h>
#include <Inventor/manips/SoTrackballManip.h>
#include <Inventor/manips/SoTransformBoxManip.h>
#include <Inventor/manips/SoTransformerManip.h>
#include <Inventor/nodes/SoEventCallback.h>
#include <Inventor/nodes/SoIndexedLineSet.h>
#include <Inventor/nodes/SoSelection.h>
#include <Inventor/nodes/SoTransform.h>
#include <Inventor/nodes/SoCoordinate3.h>
#include <Inventor/nodes/SoDrawStyle.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoPointSet.h>
#include <Inventor/nodekits/SoBaseKit.h>
#include <Inventor/nodekits/SoNodekitCatalog.h>
#include <Inventor/nodekits/SoSceneKit.h>
#include <Inventor/Qt/SoQtRenderArea.h>
#include <Inventor/Qt/viewers/SoQtExaminerViewer.h>
#include <Inventor/VRMLnodes/SoVRMLBackground.h>
#include <qwt3d_types.h>
#include <dirent.h>
#include <sstream>
#include <string>
#include <vector>
#include "ActionInsertMaterial.h"
#include "ActionInsertShape.h"
#include "ActionInsertSunShape.h"
#include "ActionInsertTracker.h"
#include "AnalyzerWindow.h"
#include "CmdCopy.h"
#include "CmdCut.h"
#include "CmdDelete.h"
#include "CmdDeleteTracker.h"
#include "CmdLightKitModified.h"
#include "CmdLightPositionModified.h"
#include "CmdInsertMaterial.h"
#include "CmdInsertShape.h"
#include "CmdInsertShapeKit.h"
#include "CmdInsertSeparatorKit.h"
#include "CmdInsertTracker.h"
#include "CmdParameterModified.h"
#include "CmdPaste.h"
#include "Document.h"
#include "InstanceNode.h"
#include "MainWindow.h"
#include "NodeNameDelegate.h"
#include "ParametersDelegate.h"
#include "ParametersView.h"
#include "ParametersItem.h"
#include "Ptr.h"
#include "RayTraceDialog.h"
#include "SceneModel.h"
#include "SunDialog.h"
#include "SunPosDialog.h"
#include "SunPositionCalculatorDialog.h"
#include "tgf.h"
#include "TDefaultMaterial.h"
#include "TDefaultTracker.h"
#include "TGateEngine.h"
#include "TLightKit.h"
#include "TMaterial.h"
#include "TMaterialFactory.h"
#include "TSeparatorKit.h"
#include "TShapeFactory.h"
#include "TShapeKit.h"
#include "TShape.h"
#include "TSunShapeFactory.h"
#include "TSunShape.h"
#include "TTrackerFactory.h"
#include "TTracker.h"
#include "Trace.h"
#include "tgc.h"
Functions
void startManipulator (void *data, SoDragger *dragger)
void finishManipulator (void *data, SoDragger *)
Variables
const long unsigned int Max_Photon = 10000000
Function Documentation
void finishManipulator (void * data, SoDragger *)
Definition at line 163 of file MainWindow.cpp.
References MainWindow::FinishManipulation().
Referenced by MainWindow::SoTransform_to_SoCenterballManip(), MainWindow::SoTransform_to_SoHandleBoxManip(), MainWindow::SoTransform_to_SoJackManip(), MainWindow::SoTransform_to_SoTabBoxManip(), MainWindow::SoTransform_to_SoTrackballManip(), MainWindow::SoTransform_to_SoTransformBoxManip(), and MainWindow::SoTransform_to_SoTransformerManip().
void startManipulator (void * data, SoDragger * dragger)
Definition at line 155 of file MainWindow.cpp.
References MainWindow::StartManipulation().
Referenced by MainWindow::SoTransform_to_SoCenterballManip(), MainWindow::SoTransform_to_SoHandleBoxManip(), MainWindow::SoTransform_to_SoJackManip(), MainWindow::SoTransform_to_SoTabBoxManip(), MainWindow::SoTransform_to_SoTrackballManip(), MainWindow::SoTransform_to_SoTransformBoxManip(), and MainWindow::SoTransform_to_SoTransformerManip().
Variable Documentation
const long unsigned int Max_Photon = 10000000
Definition at line 153 of file MainWindow.cpp.
Referenced by MainWindow::on_actionRayTraceRun_triggered().