Tonatiuh: ParametersDelegate Class Reference
ParametersDelegate Class Reference
#include <ParametersDelegate.h>
Public Member Functions
ParametersDelegate (QObject *parent=0)
~ParametersDelegate ()
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
void setEditorData (QWidget *editor, const QModelIndex &index) const
Detailed Description
Definition at line 45 of file ParametersDelegate.h.
Constructor & Destructor Documentation
ParametersDelegate::ParametersDelegate (QObject * parent = 0)
Definition at line 51 of file ParametersDelegate.cpp.
ParametersDelegate::~ParametersDelegate ()
Definition at line 57 of file ParametersDelegate.cpp.
Member Function Documentation
QWidget * ParametersDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const
Definition at line 62 of file ParametersDelegate.cpp.
References ParametersItem::GetField(), and ParametersModel::ModelItem().
void ParametersDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const
Definition at line 88 of file ParametersDelegate.cpp.
References ParametersItem::GetField(), and ParametersModel::ModelItem().
The documentation for this class was generated from the following files:
C:/eclipse/workspace/Tonatiuh/src/ParametersDelegate.h
C:/eclipse/workspace/Tonatiuh/src/ParametersDelegate.cpp