Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/Transform.cpp File Reference
C:/eclipse/workspace/Tonatiuh/src/Transform.cpp File Reference
#include <cmath>
#include <cfloat>
#include "Transform.h"
#include "Normal.h"
#include "Ray.h"
#include "BBox.h"
Functions
Transform Translate (const Vector3D &delta)
Transform Translate (double x, double y, double z)
Transform Scale (double sx, double sy, double sz)
Transform RotateX (double angle)
Transform RotateY (double angle)
Transform RotateZ (double angle)
Transform Rotate (double angle, const Vector3D &axis)
Transform LookAt (const Point3D &pos, const Point3D &look, const Vector3D &up)
std::ostream & operator<< (std::ostream &os, const Transform &tran)
Function Documentation
Transform LookAt (const Point3D & pos, const Point3D & look, const Vector3D & up)
Definition at line 382 of file Transform.cpp.
References CrossProduct(), Normalize(), Transform::Transform(), Vector3D::x, Point3D::x, Vector3D::y, Point3D::y, Vector3D::z, and Point3D::z.
std::ostream& operator<< (std::ostream & os, const Transform & tran)
Definition at line 413 of file Transform.cpp.
References Transform::GetMatrix().
Transform Rotate (double angle, const Vector3D & axis)
Definition at line 350 of file Transform.cpp.
References Normalize(), Transform::Transform(), Vector3D::x, Vector3D::y, and Vector3D::z.
Transform RotateX (double angle)
Definition at line 307 of file Transform.cpp.
References Transform::Transform().
Transform RotateY (double angle)
Definition at line 321 of file Transform.cpp.
References Transform::Transform().
Transform RotateZ (double angle)
Definition at line 336 of file Transform.cpp.
References Transform::Transform().
Transform Scale (double sx, double sy, double sz)
Definition at line 292 of file Transform.cpp.
References Transform::Transform().
Transform Translate (double x, double y, double z)
Definition at line 277 of file Transform.cpp.
References Transform::Transform().
Transform Translate (const Vector3D & delta)
Definition at line 262 of file Transform.cpp.
References Transform::Transform(), Vector3D::x, Vector3D::y, and Vector3D::z.