Tonatiuh: C:/eclipse/workspace/Tonatiuh/src/Vector3D.cpp File Reference
C:/eclipse/workspace/Tonatiuh/src/Vector3D.cpp File Reference
#include <cmath>
#include <float.h>
#include "Vector3D.h"
#include "Point3D.h"
#include "Normal.h"
Functions
Vector3D operator- (const Vector3D &vector)
Vector3D operator+ (const Vector3D &lhs, const Vector3D &rhs)
Vector3D operator- (const Vector3D &lhs, const Vector3D &rhs)
Vector3D operator* (const Vector3D &vector, double scalar)
Vector3D operator* (double scalar, const Vector3D &vector)
Vector3D operator/ (const Vector3D &vector, double scalar)
std::ostream & operator<< (std::ostream &os, const Vector3D &vector)
double DotProduct (const Vector3D &vA, const Vector3D &vB)
double DotProduct (const Vector3D &vA, const Normal &nB)
double DotProduct (const Normal &nA, const Vector3D &vB)
double AbsDotProduct (const Vector3D &vA, const Vector3D &vB)
double AbsDotProduct (const Vector3D &vA, const Normal &nB)
double AbsDotProduct (const Normal &nA, const Vector3D &vB)
Vector3D CrossProduct (const Vector3D &vA, const Vector3D &vB)
Vector3D CrossProduct (const Vector3D &vA, const Normal &nB)
Vector3D CrossProduct (const Normal &nA, const Vector3D &vB)
Vector3D Normalize (const Vector3D &vA)
bool SameHemisphere (const Vector3D &vA, const Vector3D &vB)
Function Documentation
double AbsDotProduct (const Normal & nA, const Vector3D & vB)
Definition at line 217 of file Vector3D.cpp.
References DotProduct().
double AbsDotProduct (const Vector3D & vA, const Normal & nB)
Definition at line 212 of file Vector3D.cpp.
References DotProduct().
double AbsDotProduct (const Vector3D & vA, const Vector3D & vB)
Definition at line 207 of file Vector3D.cpp.
References DotProduct().
Vector3D CrossProduct (const Normal & nA, const Vector3D & vB)
Definition at line 236 of file Vector3D.cpp.
References Vector3D::Vector3D(), Normal::x, Vector3D::x, Vector3D::y, Normal::y, Normal::z, and Vector3D::z.
Vector3D CrossProduct (const Vector3D & vA, const Normal & nB)
Definition at line 229 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Normal::x, Normal::y, Vector3D::y, Vector3D::z, and Normal::z.
Vector3D CrossProduct (const Vector3D & vA, const Vector3D & vB)
Definition at line 222 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Vector3D::y, and Vector3D::z.
Referenced by DifferentialGeometry::DifferentialGeometry(), and LookAt().
double DotProduct (const Normal & nA, const Vector3D & vB)
Definition at line 202 of file Vector3D.cpp.
References Vector3D::x, Normal::x, Vector3D::y, Normal::y, Vector3D::z, and Normal::z.
double DotProduct (const Vector3D & vA, const Normal & nB)
Definition at line 197 of file Vector3D.cpp.
References Normal::x, Vector3D::x, Normal::y, Vector3D::y, Normal::z, and Vector3D::z.
double DotProduct (const Vector3D & vA, const Vector3D & vB)
Definition at line 192 of file Vector3D.cpp.
References Vector3D::x, Vector3D::y, and Vector3D::z.
Vector3D Normalize (const Vector3D & vA)
Definition at line 243 of file Vector3D.cpp.
References Vector3D::Length().
Vector3D operator* (double scalar, const Vector3D & vector)
Definition at line 175 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Vector3D::y, and Vector3D::z.
Vector3D operator* (const Vector3D & vector, double scalar)
Definition at line 170 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Vector3D::y, and Vector3D::z.
Vector3D operator+ (const Vector3D & lhs, const Vector3D & rhs)
Definition at line 160 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Vector3D::y, and Vector3D::z.
Vector3D operator- (const Vector3D & lhs, const Vector3D & rhs)
Definition at line 165 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Vector3D::y, and Vector3D::z.
Vector3D operator- (const Vector3D & vector)
Definition at line 155 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Vector3D::y, and Vector3D::z.
Vector3D operator/ (const Vector3D & vector, double scalar)
Definition at line 180 of file Vector3D.cpp.
References Vector3D::Vector3D(), Vector3D::x, Vector3D::y, and Vector3D::z.
std::ostream& operator<< (std::ostream & os, const Vector3D & vector)
Definition at line 186 of file Vector3D.cpp.
References Vector3D::x, Vector3D::y, and Vector3D::z.
bool SameHemisphere (const Vector3D & vA, const Vector3D & vB)
Definition at line 248 of file Vector3D.cpp.
References Vector3D::z.