Tonatiuh: TShapeKit Class Reference
TShapeKit Class Reference
#include <TShapeKit.h>
Public Member Functions
TShapeKit ()
void SetBoundigBox (SbXfBox3f boundingBox)
bool IntersectP (const Ray &ray) const
Ray * Intersect (const Ray &ray, RandomDeviate &rand) const
Static Public Member Functions
static void initClass ()
Private Member Functions
SO_KIT_HEADER (TShapeKit)
virtual ~TShapeKit ()
Private Attributes
SbXfBox3f m_boundigBox
Detailed Description
Definition at line 52 of file TShapeKit.h.
Constructor & Destructor Documentation
TShapeKit::TShapeKit ()
Definition at line 61 of file TShapeKit.cpp.
TShapeKit::~TShapeKit () [private, virtual]
Definition at line 76 of file TShapeKit.cpp.
Member Function Documentation
TShapeKit::SO_KIT_HEADER (TShapeKit) [private]
void TShapeKit::initClass () [static]
Definition at line 56 of file TShapeKit.cpp.
Referenced by main().
void TShapeKit::SetBoundigBox (SbXfBox3f boundingBox)
Definition at line 81 of file TShapeKit.cpp.
References m_boundigBox.
Referenced by MainWindow::SetBoundigBoxes().
bool TShapeKit::IntersectP (const Ray & ray) const
Definition at line 87 of file TShapeKit.cpp.
Ray * TShapeKit::Intersect (const Ray & ray, RandomDeviate & rand) const
Definition at line 92 of file TShapeKit.cpp.
References Ray::direction, Transform::GetInverse(), TMaterial::GetReflectedRay(), TShape::Intersect(), m_boundigBox, Ray::maxt, Ray::mint, Ray::origin, and swap.
Referenced by TSeparatorKit::Intersect().
Member Data Documentation
SbXfBox3f TShapeKit::m_boundigBox [private]
Definition at line 68 of file TShapeKit.h.
Referenced by Intersect(), and SetBoundigBox().
The documentation for this class was generated from the following files:
C:/eclipse/workspace/Tonatiuh/src/TShapeKit.h
C:/eclipse/workspace/Tonatiuh/src/TShapeKit.cpp