######################################################################
# Automatically generated by qmake (2.01a) jue 1. mar 13:04:12 2007
######################################################################


TEMPLATE = app
TARGET = 
CONFIG	+= debug_and_release
CONFIG	-= app_bundle
DEPENDPATH += . \
				src

win32	{
	DEFINES+= COIN_DLL SOQT_DLL
	INCLUDEPATH += . \
				src \
				../TonatiuhProject/Tonatiuh/src \ 
				../TonatiuhProject/ShapeCone/src \ 
				C:/msys/usr/local/include \

	LIBS += -L"c:\msys\usr\local\lib" -lqxcppunitd -lqxrunnerd 
	LIBS +=	-L"c:\msys\usr\local\lib" -lcppunit
	LIBS += -L"c:\msys\usr\local\lib" -lSoQt -lCoin
}

unix	{

	INCLUDEPATH += 	src \
				../TonatiuhProject/Tonatiuh/src \ 
				../TonatiuhProject/ShapeCone/src \
				/usr/local/include 

	LIBS +=-L/usr/local/lib  -lSoQt -lCoin -lqxcppunitd -lqxrunnerd -lcppunit
	
    CONFIG(debug, debug|release) {
        DESTDIR = ../ConeUnitTest/debug/
    }
    else {
        DESTDIR  = ../ConeUnitTest/release/
    }
}

# Input
HEADERS +=	*.h\
			../TonatiuhProject/Tonatiuh/src/BBox.h \
			../TonatiuhProject/Tonatiuh/src/InstanceNode.h \
			../TonatiuhProject/Tonatiuh/src/Matrix4x4.h \
			../TonatiuhProject/Tonatiuh/src/MersenneTwister.h \
			../TonatiuhProject/Tonatiuh/src/NormalVector.h \
			../TonatiuhProject/Tonatiuh/src/Photon.h \
			../TonatiuhProject/Tonatiuh/src/PhotonMap.h \
			../TonatiuhProject/Tonatiuh/src/Point3D.h \
			../TonatiuhProject/Tonatiuh/src/Ray.h \
			../TonatiuhProject/Tonatiuh/src/RefCount.h \
			../TonatiuhProject/Tonatiuh/src/tgf.h \
			../TonatiuhProject/Tonatiuh/src/Transform.h \
			../TonatiuhProject/Tonatiuh/src/Trace.h \
			../TonatiuhProject/Tonatiuh/src/TSeparatorKit.h \
			../TonatiuhProject/Tonatiuh/src/TShape.h \
			../TonatiuhProject/Tonatiuh/src/TShapeKit.h \
			../TonatiuhProject/Tonatiuh/src/Vector3D.h \
           	../TonatiuhProject/ShapeCone/src/ShapeCone.h
           	           	
SOURCES += *.cpp\
			../TonatiuhProject/Tonatiuh/src/DifferentialGeometry.cpp \
			../TonatiuhProject/Tonatiuh/src/BBox.cpp \
			../TonatiuhProject/Tonatiuh/src/InstanceNode.cpp \
			../TonatiuhProject/Tonatiuh/src/Matrix4x4.cpp \
			../TonatiuhProject/Tonatiuh/src/MersenneTwister.cpp \
			../TonatiuhProject/Tonatiuh/src/NormalVector.cpp \
			../TonatiuhProject/Tonatiuh/src/Photon.cpp \
			../TonatiuhProject/Tonatiuh/src/PhotonMap.cpp \
			../TonatiuhProject/Tonatiuh/src/Point3D.cpp \
			../TonatiuhProject/Tonatiuh/src/Ray.cpp \
			../TonatiuhProject/Tonatiuh/src/RefCount.cpp \
			../TonatiuhProject/Tonatiuh/src/tgf.cpp \
			../TonatiuhProject/Tonatiuh/src/Trace.cpp \
			../TonatiuhProject/Tonatiuh/src/Transform.cpp \
			../TonatiuhProject/Tonatiuh/src/TSeparatorKit.cpp \
			../TonatiuhProject/Tonatiuh/src/TShape.cpp \
			../TonatiuhProject/Tonatiuh/src/TShapeKit.cpp \
			../TonatiuhProject/Tonatiuh/src/Vector3D.cpp \
           	../TonatiuhProject/ShapeCone/src/ShapeCone.cpp
           	