Tonatiuh: ParametersModel Class Reference
ParametersModel Class Reference
#include <ParametersModel.h>
Public Member Functions
ParametersModel (QObject *parent=0)
~ParametersModel ()
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Qt::ItemFlags flags (const QModelIndex &index) const
ParametersItem * ModelItem (const QModelIndex &index) const
void SetEditable (bool editable)
Private Attributes
bool m_editable
Detailed Description
Definition at line 46 of file ParametersModel.h.
Constructor & Destructor Documentation
ParametersModel::ParametersModel (QObject * parent = 0)
Definition at line 42 of file ParametersModel.cpp.
ParametersModel::~ParametersModel ()
Definition at line 47 of file ParametersModel.cpp.
Member Function Documentation
QVariant ParametersModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 52 of file ParametersModel.cpp.
References ParametersItem::data().
bool ParametersModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Definition at line 57 of file ParametersModel.cpp.
References ParametersItem::setData().
Referenced by FieldContainerWidget::EditorClosed().
Qt::ItemFlags ParametersModel::flags (const QModelIndex & index) const
Definition at line 69 of file ParametersModel.cpp.
References m_editable.
ParametersItem * ParametersModel::ModelItem (const QModelIndex & index) const
Definition at line 77 of file ParametersModel.cpp.
Referenced by ParametersDelegate::createEditor(), FieldContainerWidget::EditorClosed(), and ParametersDelegate::setEditorData().
void ParametersModel::SetEditable (bool editable)
Definition at line 83 of file ParametersModel.cpp.
References m_editable.
Referenced by FieldContainerWidget::FieldContainerWidget(), and FieldContainerWidget::SetEditable().
Member Data Documentation
bool ParametersModel::m_editable [private]
Definition at line 62 of file ParametersModel.h.
Referenced by flags(), and SetEditable().
The documentation for this class was generated from the following files:
C:/eclipse/workspace/Tonatiuh/src/ParametersModel.h
C:/eclipse/workspace/Tonatiuh/src/ParametersModel.cpp