Tonatiuh: PhotonMap Class Reference
PhotonMap Class Reference
#include <PhotonMap.h>
Public Member Functions
PhotonMap (long unsigned maxPhotons)
~PhotonMap ()
void savePhotonMap (const char *filename)
void loadPhotonMap (char *filename)
void locatePhotons (NearestPhotons *const np, const long unsigned index) const
double fluxAtPoint (const Point3D &point, int maxClosest) const
void store (Photon *photon)
void balance ()
long unsigned StoredPhotons () const
Photon * GetPhoton (int index) const
Private Member Functions
void balanceSegment (Photon ***pbal, Photon ***porg, const long unsigned index, const long unsigned start, const long unsigned end)
void medianSplit (Photon ***p, const long unsigned start, const long unsigned end, const long unsigned median, const long unsigned axis)
Private Attributes
Photon ** m_photons
long unsigned m_storedPhotons
long unsigned m_halfStoredPhotons
long unsigned m_maxPhotons
long unsigned m_prevScale
long unsigned m_axis
BBox m_bbox
Detailed Description
Definition at line 60 of file PhotonMap.h.
Constructor & Destructor Documentation
PhotonMap::PhotonMap (long unsigned maxPhotons)
Definition at line 60 of file PhotonMap.cpp.
References m_axis, m_bbox, m_maxPhotons, m_photons, m_prevScale, m_storedPhotons, and tgf::SevereError().
PhotonMap::~PhotonMap ()
Definition at line 74 of file PhotonMap.cpp.
References m_photons, and m_storedPhotons.
Member Function Documentation
void PhotonMap::savePhotonMap (const char * filename)
Definition at line 85 of file PhotonMap.cpp.
References m_photons, and m_storedPhotons.
void PhotonMap::loadPhotonMap (char * filename)
Definition at line 92 of file PhotonMap.cpp.
References m_halfStoredPhotons, m_maxPhotons, m_photons, and m_storedPhotons.
void PhotonMap::locatePhotons (NearestPhotons *const np, const long unsigned index) const
Definition at line 109 of file PhotonMap.cpp.
References DistanceSquared(), NearestPhotons::m_dist2, NearestPhotons::m_found, NearestPhotons::m_gotHeap, m_halfStoredPhotons, NearestPhotons::m_index, NearestPhotons::m_max, m_photons, Photon::m_plane, Photon::m_pos, and NearestPhotons::m_pos.
Referenced by fluxAtPoint().
double PhotonMap::fluxAtPoint (const Point3D & point, int maxClosest) const
Definition at line 190 of file PhotonMap.cpp.
References Distance(), locatePhotons(), NearestPhotons::m_dist2, NearestPhotons::m_found, NearestPhotons::m_gotHeap, NearestPhotons::m_index, NearestPhotons::m_max, Photon::m_pos, and NearestPhotons::m_pos.
Referenced by Flux::operator()().
void PhotonMap::store (Photon * photon)
Definition at line 210 of file PhotonMap.cpp.
References m_bbox, Photon::m_id, m_maxPhotons, m_photons, Photon::m_pos, m_storedPhotons, and Union().
Referenced by tgf::TraceRay().
void PhotonMap::balance ()
Definition at line 223 of file PhotonMap.cpp.
References balanceSegment(), m_halfStoredPhotons, m_maxPhotons, m_photons, and m_storedPhotons.
long unsigned PhotonMap::StoredPhotons () const [inline]
Definition at line 73 of file PhotonMap.h.
References m_storedPhotons.
Referenced by tgf::DrawPhotonMapPoints(), tgf::DrawPhotonMapRays(), and MainWindow::on_actionResults_triggered().
Photon * PhotonMap::GetPhoton (int index) const
Definition at line 354 of file PhotonMap.cpp.
References m_photons.
Referenced by tgf::DrawPhotonMapPoints(), and tgf::DrawPhotonMapRays().
void PhotonMap::balanceSegment (Photon *** pbal, Photon *** porg, const long unsigned index, const long unsigned start, const long unsigned end) [private]
Definition at line 301 of file PhotonMap.cpp.
References m_axis, m_bbox, Photon::m_plane, Photon::m_pos, medianSplit(), BBox::pMax, and BBox::pMin.
Referenced by balance().
void PhotonMap::medianSplit (Photon *** p, const long unsigned start, const long unsigned end, const long unsigned median, const long unsigned axis) [private]
Definition at line 276 of file PhotonMap.cpp.
References Photon::m_pos, and swap.
Referenced by balanceSegment().
Member Data Documentation
Photon** PhotonMap::m_photons [private]
Definition at line 80 of file PhotonMap.h.
Referenced by balance(), GetPhoton(), loadPhotonMap(), locatePhotons(), PhotonMap(), savePhotonMap(), store(), and ~PhotonMap().
long unsigned PhotonMap::m_storedPhotons [private]
Definition at line 82 of file PhotonMap.h.
Referenced by balance(), loadPhotonMap(), PhotonMap(), savePhotonMap(), store(), StoredPhotons(), and ~PhotonMap().
long unsigned PhotonMap::m_halfStoredPhotons [private]
Definition at line 83 of file PhotonMap.h.
Referenced by balance(), loadPhotonMap(), and locatePhotons().
long unsigned PhotonMap::m_maxPhotons [private]
Definition at line 84 of file PhotonMap.h.
Referenced by balance(), loadPhotonMap(), PhotonMap(), and store().
long unsigned PhotonMap::m_prevScale [private]
Definition at line 85 of file PhotonMap.h.
Referenced by PhotonMap().
long unsigned PhotonMap::m_axis [private]
Definition at line 86 of file PhotonMap.h.
Referenced by balanceSegment(), and PhotonMap().
BBox PhotonMap::m_bbox [private]
Definition at line 87 of file PhotonMap.h.
Referenced by balanceSegment(), PhotonMap(), and store().
The documentation for this class was generated from the following files:
C:/eclipse/workspace/Tonatiuh/src/PhotonMap.h
C:/eclipse/workspace/Tonatiuh/src/PhotonMap.cpp