######################################################################
# Automatically generated by qmake (2.01a) jue 8. feb 13:55:05 2007
######################################################################
 
TEMPLATE = app
CONFIG       += qt warn_on thread debug_and_release 
CONFIG -=app_bundle
TARGET =   
DEPENDPATH += . \
              src 
QT += xml opengl svg

INCLUDEPATH += . \
			src 
 
# Input
HEADERS += *.h
FORMS += *.ui
SOURCES += *.cpp
RESOURCES += *.qrc

	