Tonatiuh: InstanceNode.cpp File Reference
http://tonatiuh.googlecode.com
InstanceNode.cpp File Reference
Functions
QDataStream & operator<< (QDataStream &s, const InstanceNode &node)
QDataStream & operator>> (QDataStream &s, const InstanceNode &node)
bool operator== (const InstanceNode &thisNode, const InstanceNode &otherNode)
Function Documentation
QDataStream& operator<< (QDataStream & s, const InstanceNode & node)
Definition at line 363 of file InstanceNode.cpp.
References InstanceNode::GetNode().
bool operator== (const InstanceNode & thisNode, const InstanceNode & otherNode)
Definition at line 375 of file InstanceNode.cpp.
References InstanceNode::GetNode(), and InstanceNode::GetParent().
QDataStream& operator>> (QDataStream & s, const InstanceNode & node)
Definition at line 369 of file InstanceNode.cpp.