Tonatiuh: Transform.h File Reference
http://tonatiuh.googlecode.com
Transform.h File Reference
Classes
class Transform
Functions
Transform Translate (const Vector3D &delta)
Transform Translate (double x, double y, double z)
Transform Scale (double x, double y, double z)
Transform RotateX (double angle)
Transform RotateY (double angle)
Transform RotateZ (double angle)
Transform Rotate (double angle, const Vector3D &axis)
Transform LookAt (const Point3D &pos, const Point3D &look, const Vector3D &up)
std::ostream & operator<< (std::ostream &os, const Transform &tran)
Function Documentation
Transform LookAt (const Point3D & pos, const Point3D & look, const Vector3D & up)
Definition at line 400 of file Transform.cpp.
References CrossProduct(), Normalize(), Vector3D::x, Point3D::x, Vector3D::y, Point3D::y, Vector3D::z, and Point3D::z.
std::ostream& operator<< (std::ostream & os, const Transform & tran)
Definition at line 431 of file Transform.cpp.
References Transform::GetMatrix().
Transform Rotate (double angle, const Vector3D & axis)
Definition at line 368 of file Transform.cpp.
References Normalize(), Vector3D::x, Vector3D::y, and Vector3D::z.
Transform RotateX (double angle)
Definition at line 325 of file Transform.cpp.
Transform RotateY (double angle)
Definition at line 339 of file Transform.cpp.
Transform RotateZ (double angle)
Definition at line 354 of file Transform.cpp.
Transform Scale (double x, double y, double z)
Definition at line 310 of file Transform.cpp.
Transform Translate (const Vector3D & delta)
Definition at line 280 of file Transform.cpp.
References Vector3D::x, Vector3D::y, and Vector3D::z.
Transform Translate (double x, double y, double z)
Definition at line 295 of file Transform.cpp.