Tonatiuh: Vector3D.h File Reference
http://tonatiuh.googlecode.com
Vector3D.h File Reference
Classes
struct Vector3D
Functions
Vector3D operator+ (Vector3D lhs, const Vector3D &rhs)
Vector3D operator- (Vector3D lhs, const Vector3D &rhs)
Vector3D operator* (double scalar, const Vector3D &vector)
std::ostream & operator<< (std::ostream &os, const Vector3D &vector)
double DotProduct (const Vector3D &vA, const Vector3D &vB)
double DotProduct (const Vector3D &vA, const NormalVector &nB)
double DotProduct (const NormalVector &nA, const Vector3D &vB)
double AbsDotProduct (const Vector3D &vA, const Vector3D &vB)
double AbsDotProduct (const Vector3D &vA, const NormalVector &nB)
double AbsDotProduct (const NormalVector &nA, const Vector3D &vB)
Vector3D CrossProduct (const Vector3D &vA, const Vector3D &vB)
Vector3D CrossProduct (const Vector3D &vA, const NormalVector &nB)
Vector3D CrossProduct (const NormalVector &nA, const Vector3D &vB)
Vector3D Normalize (const Vector3D &vA)
bool SameHemisphere (const Vector3D &vA, const Vector3D &vB)
Function Documentation
double AbsDotProduct (const Vector3D & vA, const Vector3D & vB)
Definition at line 197 of file Vector3D.cpp.
References DotProduct().
double AbsDotProduct (const Vector3D & vA, const NormalVector & nB)
Definition at line 202 of file Vector3D.cpp.
References DotProduct().
double AbsDotProduct (const NormalVector & nA, const Vector3D & vB)
Definition at line 207 of file Vector3D.cpp.
References DotProduct().
Vector3D CrossProduct (const Vector3D & vA, const Vector3D & vB)
Definition at line 212 of file Vector3D.cpp.
References Vector3D::x, Vector3D::y, and Vector3D::z.
Referenced by DifferentialGeometry::DifferentialGeometry(), and LookAt().
Vector3D CrossProduct (const Vector3D & vA, const NormalVector & nB)
Definition at line 219 of file Vector3D.cpp.
References Vector3D::x, NormalVector::x, NormalVector::y, Vector3D::y, Vector3D::z, and NormalVector::z.
Vector3D CrossProduct (const NormalVector & nA, const Vector3D & vB)
Definition at line 226 of file Vector3D.cpp.
References NormalVector::x, Vector3D::x, Vector3D::y, NormalVector::y, NormalVector::z, and Vector3D::z.
double DotProduct (const Vector3D & vA, const NormalVector & nB)
Definition at line 187 of file Vector3D.cpp.
References NormalVector::x, Vector3D::x, NormalVector::y, Vector3D::y, NormalVector::z, and Vector3D::z.
double DotProduct (const Vector3D & vA, const Vector3D & vB)
Definition at line 182 of file Vector3D.cpp.
References Vector3D::x, Vector3D::y, and Vector3D::z.
double DotProduct (const NormalVector & nA, const Vector3D & vB)
Definition at line 192 of file Vector3D.cpp.
References Vector3D::x, NormalVector::x, Vector3D::y, NormalVector::y, Vector3D::z, and NormalVector::z.
Vector3D Normalize (const Vector3D & vA)
Definition at line 233 of file Vector3D.cpp.
References Vector3D::length().
Vector3D operator* (double scalar, const Vector3D & vector)
Definition at line 171 of file Vector3D.cpp.
References Vector3D::x, Vector3D::y, and Vector3D::z.
Vector3D operator+ (Vector3D lhs, const Vector3D & rhs)
Definition at line 159 of file Vector3D.cpp.
Vector3D operator- (Vector3D lhs, const Vector3D & rhs)
Definition at line 165 of file Vector3D.cpp.
std::ostream& operator<< (std::ostream & os, const Vector3D & vector)
Definition at line 176 of file Vector3D.cpp.
References Vector3D::x, Vector3D::y, and Vector3D::z.
bool SameHemisphere (const Vector3D & vA, const Vector3D & vB)
Definition at line 238 of file Vector3D.cpp.
References Vector3D::z.