TSquare Class Reference
http://tonatiuh.googlecode.com
TSquare Class Reference
Public Member Functions
TSquare ()
double GetArea () const
double GetVolume () const
BBox GetBBox () const
QString GetIcon () const
bool Intersect (const Ray &ray, double *tHit, DifferentialGeometry *dg) const
bool IntersectP (const Ray &ray) const
Point3D Sample (double u, double v) const
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFDouble m_sideLength
Protected Member Functions
Point3D GetPoint3D (double u, double v) const
NormalVector GetNormal (double u, double v) const
void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center)
void generatePrimitives (SoAction *action)
~TSquare ()
Private Member Functions
SO_NODE_HEADER (TSquare)
Detailed Description
Definition at line 48 of file TSquare.h.
Constructor & Destructor Documentation
TSquare::TSquare ()
Definition at line 60 of file TSquare.cpp.
References m_sideLength.
TSquare::~TSquare () [protected]
Definition at line 66 of file TSquare.cpp.
Member Function Documentation
void TSquare::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) [protected, virtual]
Implements TShape.
Definition at line 126 of file TSquare.cpp.
References GetBBox(), BBox::pMax, BBox::pMin, Point3D::x, Point3D::y, and Point3D::z.
void TSquare::generatePrimitives (SoAction * action) [protected, virtual]
Implements TShape.
Definition at line 144 of file TSquare.cpp.
References GetNormal(), GetPoint3D(), Point3D::x, NormalVector::x, Point3D::y, NormalVector::y, Point3D::z, and NormalVector::z.
double TSquare::GetArea () const [virtual]
Implements TShape.
Definition at line 71 of file TSquare.cpp.
References m_sideLength.
BBox TSquare::GetBBox () const [virtual]
Implements TShape.
Definition at line 77 of file TSquare.cpp.
References m_sideLength.
Referenced by computeBBox().
QString TSquare::GetIcon () const [virtual]
Implements TShape.
Definition at line 86 of file TSquare.cpp.
NormalVector TSquare::GetNormal (double u, double v) const [protected]
Definition at line 120 of file TSquare.cpp.
Referenced by generatePrimitives().
Point3D TSquare::GetPoint3D (double u, double v) const [protected]
Definition at line 106 of file TSquare.cpp.
References m_sideLength, and tgf::SevereError().
Referenced by generatePrimitives(), and Sample().
double TSquare::GetVolume () const [inline, virtual]
Implements TShape.
Definition at line 55 of file TSquare.h.
void TSquare::initClass () [static]
Reimplemented from TShape.
Definition at line 55 of file TSquare.cpp.
Referenced by main().
bool TSquare::Intersect (const Ray & ray, double * tHit, DifferentialGeometry * dg) const [virtual]
Implements TShape.
Definition at line 91 of file TSquare.cpp.
Referenced by IntersectP().
bool TSquare::IntersectP (const Ray & ray) const [virtual]
Implements TShape.
Definition at line 96 of file TSquare.cpp.
References Intersect().
Point3D TSquare::Sample (double u, double v) const [virtual]
Implements TShape.
Definition at line 101 of file TSquare.cpp.
References GetPoint3D().
TSquare::SO_NODE_HEADER (TSquare) [private]
Member Data Documentation
SoSFDouble TSquare::m_sideLength
Definition at line 63 of file TSquare.h.
Referenced by GetArea(), GetBBox(), GetPoint3D(), and TSquare().
The documentation for this class was generated from the following files:
TSquare.h
TSquare.cpp