Tonatiuh: SunPositionCalculatorDialog Class Reference
http://tonatiuh.googlecode.com
SunPositionCalculatorDialog Class Reference
Signals
void changeRepresentation (cSunCoordinates results)
void changeSunLight (double azimuth, double zenith)
Public Member Functions
SunPositionCalculatorDialog (QWidget *parent=0)
~SunPositionCalculatorDialog ()
Protected Member Functions
void closeEvent (QCloseEvent *event)
Private Slots
void UpdatePosition (QAbstractButton *button)
void ChangeDate ()
void ChangeLongitude (double longitude)
void ChangeLatitude (double latitude)
void ChangeSunTime (QTime time)
void ChangeSunTimeZone (int timeZone)
void on_selectButton_clicked ()
Private Member Functions
void CalculateSunPosition ()
QDateTime GetTime ()
void ReadSettings ()
void WriteSettings ()
Detailed Description
Definition at line 51 of file SunPositionCalculatorDialog.h.
Constructor & Destructor Documentation
SunPositionCalculatorDialog::SunPositionCalculatorDialog (QWidget * parent = 0)
Definition at line 48 of file SunPositionCalculatorDialog.cpp.
References Ui_SunPositionCalculatorDialog::buttonBox, Ui_SunPositionCalculatorDialog::calendarWidget, ChangeDate(), ChangeLatitude(), ChangeLongitude(), changeRepresentation(), ChangeSunTime(), ChangeSunTimeZone(), Ui_SunPositionCalculatorDialog::ctTime, Ui_SunPositionCalculatorDialog::latitudeSpin, Ui_SunPositionCalculatorDialog::longitudeSpin, ReadSettings(), Ui_SunPositionCalculatorDialog::setupUi(), UpdatePosition(), Ui_SunPositionCalculatorDialog::utTime, Ui_SunPositionCalculatorDialog::worldMap, and Ui_SunPositionCalculatorDialog::zoneSpin.
SunPositionCalculatorDialog::~SunPositionCalculatorDialog ()
Definition at line 73 of file SunPositionCalculatorDialog.cpp.
References WriteSettings().
Member Function Documentation
void SunPositionCalculatorDialog::CalculateSunPosition () [private]
Definition at line 154 of file SunPositionCalculatorDialog.cpp.
References changeRepresentation(), GetTime(), Ui_SunPositionCalculatorDialog::latitudeSpin, Ui_SunPositionCalculatorDialog::longitudeSpin, and sunpos().
Referenced by ChangeDate(), ChangeLatitude(), ChangeLongitude(), ChangeSunTime(), and ChangeSunTimeZone().
void SunPositionCalculatorDialog::ChangeDate () [private, slot]
Definition at line 115 of file SunPositionCalculatorDialog.cpp.
References CalculateSunPosition().
Referenced by SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::ChangeLatitude (double latitude) [private, slot]
Definition at line 125 of file SunPositionCalculatorDialog.cpp.
References CalculateSunPosition().
Referenced by SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::ChangeLongitude (double longitude) [private, slot]
Definition at line 120 of file SunPositionCalculatorDialog.cpp.
References CalculateSunPosition().
Referenced by SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::changeRepresentation (cSunCoordinates results) [signal]
Referenced by CalculateSunPosition(), and SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::changeSunLight (double azimuth, double zenith) [signal]
Referenced by UpdatePosition().
void SunPositionCalculatorDialog::ChangeSunTime (QTime time) [private, slot]
Definition at line 130 of file SunPositionCalculatorDialog.cpp.
References CalculateSunPosition().
Referenced by SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::ChangeSunTimeZone (int timeZone) [private, slot]
Definition at line 135 of file SunPositionCalculatorDialog.cpp.
References CalculateSunPosition().
Referenced by SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::closeEvent (QCloseEvent * event) [protected]
Definition at line 78 of file SunPositionCalculatorDialog.cpp.
References WriteSettings().
QDateTime SunPositionCalculatorDialog::GetTime () [private]
Definition at line 181 of file SunPositionCalculatorDialog.cpp.
References Ui_SunPositionCalculatorDialog::calendarWidget, Ui_SunPositionCalculatorDialog::ctTime, Ui_SunPositionCalculatorDialog::utRadio, Ui_SunPositionCalculatorDialog::utTime, and Ui_SunPositionCalculatorDialog::zoneSpin.
Referenced by CalculateSunPosition(), and UpdatePosition().
void SunPositionCalculatorDialog::on_selectButton_clicked () [private, slot]
Definition at line 140 of file SunPositionCalculatorDialog.cpp.
References MapDialog::GetHomePosition(), Ui_SunPositionCalculatorDialog::latitudeSpin, Ui_SunPositionCalculatorDialog::longitudeSpin, and MapDialog::SetHomePosition().
void SunPositionCalculatorDialog::ReadSettings () [private]
Definition at line 191 of file SunPositionCalculatorDialog.cpp.
References Ui_SunPositionCalculatorDialog::calendarWidget, Ui_SunPositionCalculatorDialog::ctRadio, Ui_SunPositionCalculatorDialog::ctTime, Ui_SunPositionCalculatorDialog::latitudeSpin, Ui_SunPositionCalculatorDialog::longitudeSpin, Ui_SunPositionCalculatorDialog::utRadio, Ui_SunPositionCalculatorDialog::utTime, and Ui_SunPositionCalculatorDialog::zoneSpin.
Referenced by SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::UpdatePosition (QAbstractButton * button) [private, slot]
Definition at line 85 of file SunPositionCalculatorDialog.cpp.
References Ui_SunPositionCalculatorDialog::buttonBox, changeSunLight(), cSunCoordinates::dAzimuth, tgc::Degree, cSunCoordinates::dZenithAngle, GetTime(), Ui_SunPositionCalculatorDialog::latitudeSpin, Ui_SunPositionCalculatorDialog::longitudeSpin, and sunpos().
Referenced by SunPositionCalculatorDialog().
void SunPositionCalculatorDialog::WriteSettings () [private]
Definition at line 206 of file SunPositionCalculatorDialog.cpp.
References Ui_SunPositionCalculatorDialog::calendarWidget, Ui_SunPositionCalculatorDialog::ctRadio, Ui_SunPositionCalculatorDialog::ctTime, Ui_SunPositionCalculatorDialog::latitudeSpin, Ui_SunPositionCalculatorDialog::longitudeSpin, Ui_SunPositionCalculatorDialog::utRadio, Ui_SunPositionCalculatorDialog::utTime, and Ui_SunPositionCalculatorDialog::zoneSpin.
Referenced by closeEvent(), and ~SunPositionCalculatorDialog().
The documentation for this class was generated from the following files:
SunPositionCalculatorDialog.h
SunPositionCalculatorDialog.cpp