Tonatiuh: CmdDeleteTracker Class Reference
http://tonatiuh.googlecode.com
CmdDeleteTracker Class Reference
CmdDeleteTracker class is the delete command for trackers nodes stored in the command stack.
Public Member Functions
CmdDeleteTracker (const QModelIndex &selectedIndex, SoSceneKit *scene, SceneModel &model, QUndoCommand *parent=0)
~CmdDeleteTracker ()
virtual void undo ()
virtual void redo ()
Private Attributes
TTracker * m_tracker
TSeparatorKit * m_coinParent
SoSceneKit * m_scene
SceneModel * m_pModel
int m_row
Detailed Description
CmdDeleteTracker class is the delete command for trackers nodes stored in the command stack.
CmdDeleteTracker represents a single tracker node delete action on a scene. Deletes a node from the scene.
See also:
CmdDelete, CmdCopy, CmdCut, CmdPaste
Definition at line 56 of file CmdDeleteTracker.h.
Constructor & Destructor Documentation
CmdDeleteTracker::CmdDeleteTracker (const QModelIndex & selectedIndex, SoSceneKit * scene, SceneModel & model, QUndoCommand * parent = 0)
Contructor.
Definition at line 53 of file CmdDeleteTracker.cpp.
References InstanceNode::children, InstanceNode::GetNode(), InstanceNode::GetParent(), TSeparatorKit::getPart(), m_coinParent, m_pModel, m_row, m_tracker, SceneModel::NodeFromIndex(), and tgf::SevereError().
CmdDeleteTracker::~CmdDeleteTracker ()
Destructor.
Definition at line 76 of file CmdDeleteTracker.cpp.
References m_tracker.
Member Function Documentation
void CmdDeleteTracker::redo () [virtual]
Deletes a tracker from the scene.
See also:
undo
Definition at line 110 of file CmdDeleteTracker.cpp.
References SceneModel::Cut(), TTracker::Disconnect(), TSeparatorKit::getPart(), m_coinParent, m_pModel, m_row, and m_tracker.
void CmdDeleteTracker::undo () [virtual]
Restores the tracker to the state before deletion.
See also:
redo
Definition at line 85 of file CmdDeleteTracker.cpp.
References TLightKit::azimuth, TSeparatorKit::getPart(), m_coinParent, m_pModel, m_row, m_scene, m_tracker, TTracker::outputCenter, TTracker::outputRotation, TTracker::outputScaleFactor, TTracker::outputScaleOrientation, TTracker::outputTranslation, SceneModel::Paste(), TTracker::SetAzimuthAngle(), TTracker::SetZenithAngle(), tgf::SevereError(), tgc::Shared, and TLightKit::zenith.
Member Data Documentation
TSeparatorKit* CmdDeleteTracker::m_coinParent [private]
Definition at line 67 of file CmdDeleteTracker.h.
Referenced by CmdDeleteTracker(), redo(), and undo().
SceneModel* CmdDeleteTracker::m_pModel [private]
Definition at line 69 of file CmdDeleteTracker.h.
Referenced by CmdDeleteTracker(), redo(), and undo().
int CmdDeleteTracker::m_row [private]
Definition at line 70 of file CmdDeleteTracker.h.
Referenced by CmdDeleteTracker(), redo(), and undo().
SoSceneKit* CmdDeleteTracker::m_scene [private]
Definition at line 68 of file CmdDeleteTracker.h.
Referenced by undo().
TTracker* CmdDeleteTracker::m_tracker [private]
Definition at line 66 of file CmdDeleteTracker.h.
Referenced by CmdDeleteTracker(), redo(), undo(), and ~CmdDeleteTracker().
The documentation for this class was generated from the following files:
CmdDeleteTracker.h
CmdDeleteTracker.cpp