Tonatiuh: Document Class Reference
http://tonatiuh.googlecode.com
Document Class Reference
Document class stores the application scene.
Signals
void Warning (QString message)
Public Member Functions
Document ()
~Document ()
void SetDocumentModified (bool status)
void New ()
bool ReadFile (const QString &fileName)
bool WriteFile (const QString &fileName)
bool IsModified ()
TSceneKit * GetSceneKit () const
Private Member Functions
TSceneKit * GetSceneKitFromFile (const QString &fileName)
void InitializeScene ()
void ClearScene ()
Private Attributes
TSceneKit * m_scene
bool m_isModified
Detailed Description
Document class stores the application scene.
This class is not yet documented.
Definition at line 55 of file Document.h.
Constructor & Destructor Documentation
Document::Document ()
Creates a new document object.
Definition at line 56 of file Document.cpp.
References InitializeScene().
Document::~Document ()
Destroys the document object.
Definition at line 67 of file Document.cpp.
Member Function Documentation
void Document::ClearScene () [private]
Clears the scene of the document.
Definition at line 103 of file Document.cpp.
References m_scene.
Referenced by InitializeScene(), and ReadFile().
TSceneKit * Document::GetSceneKit () const
Returns the document scene.
Definition at line 165 of file Document.cpp.
References m_scene.
Referenced by MainWindow::CalculateSunPosition(), MainWindow::ChangeModelScene(), MainWindow::ChangeSunPosition(), MainWindow::CreateTracker(), MainWindow::DefineSunLight(), MainWindow::DefineTransmissivity(), MainWindow::Delete(), MainWindow::ExportAllPhotonMap(), MainWindow::ExportPhotonMap(), MainWindow::on_actionSunPlane_triggered(), MainWindow::ReadyForRaytracing(), MainWindow::SelectionFinish(), MainWindow::SetSunshape(), MainWindow::SetSunshapeParameter(), ScriptRayTracer::SetTonatiuhModelFile(), MainWindow::SetTransmissivity(), MainWindow::SetTransmissivityParameter(), MainWindow::SetupGraphcisRoot(), and MainWindow::SetupModels().
TSceneKit * Document::GetSceneKitFromFile (const QString & fileName) [private]
Reads the scene saved on the file with given filename and return a pointer to the scene.
Returns null on any error.
Definition at line 175 of file Document.cpp.
References Warning().
Referenced by ReadFile().
void Document::InitializeScene () [private]
Initializes a new empty scene a scene and sets it to the document.
Definition at line 82 of file Document.cpp.
References ClearScene(), and m_scene.
Referenced by Document(), and New().
bool Document::IsModified ()
Returns whether the scene was modified.
Definition at line 157 of file Document.cpp.
References m_isModified.
Referenced by MainWindow::OkToContinue().
void Document::New ()
Initializes the document with a empty scene.
Definition at line 94 of file Document.cpp.
References InitializeScene(), and m_isModified.
Referenced by MainWindow::StartOver().
bool Document::ReadFile (const QString & fileName)
Sets the scene form fileName to the document.
Definition at line 116 of file Document.cpp.
References ClearScene(), GetSceneKitFromFile(), m_isModified, and m_scene.
Referenced by ScriptRayTracer::SetTonatiuhModelFile(), and MainWindow::StartOver().
void Document::SetDocumentModified (bool status)
Set the state of the document to status. If the status is true the document have been modified.
Definition at line 74 of file Document.cpp.
References m_isModified.
Referenced by MainWindow::ChangeNodeName(), MainWindow::ChangeSunPosition(), MainWindow::Copy(), MainWindow::CreateAnalyzerNode(), MainWindow::CreateGroupNode(), MainWindow::CreateMaterial(), MainWindow::CreateShape(), MainWindow::CreateSurfaceNode(), MainWindow::CreateTracker(), MainWindow::Cut(), MainWindow::DefineSunLight(), MainWindow::DefineTransmissivity(), MainWindow::Delete(), MainWindow::FinishManipulation(), MainWindow::InsertFileComponent(), MainWindow::ItemDragAndDrop(), MainWindow::ItemDragAndDropCopy(), MainWindow::Paste(), MainWindow::SetCurrentFile(), MainWindow::SetParameterValue(), MainWindow::SetSunshape(), MainWindow::SetSunshapeParameter(), MainWindow::SetTransmissivity(), MainWindow::SetTransmissivityParameter(), MainWindow::SoManip_to_SoTransform(), MainWindow::SoTransform_to_SoCenterballManip(), MainWindow::SoTransform_to_SoHandleBoxManip(), MainWindow::SoTransform_to_SoJackManip(), MainWindow::SoTransform_to_SoTabBoxManip(), MainWindow::SoTransform_to_SoTrackballManip(), MainWindow::SoTransform_to_SoTransformBoxManip(), and MainWindow::SoTransform_to_SoTransformerManip().
void Document::Warning (QString message) [signal]
Referenced by GetSceneKitFromFile(), and WriteFile().
bool Document::WriteFile (const QString & fileName)
Writes the document scene to a file with the given fileName.
Returns true if the scene was successfully written; otherwise returns false.
Definition at line 134 of file Document.cpp.
References m_isModified, m_scene, and Warning().
Referenced by ScriptRayTracer::Save(), and MainWindow::SaveFile().
Member Data Documentation
bool Document::m_isModified [private]
Definition at line 79 of file Document.h.
Referenced by IsModified(), New(), ReadFile(), SetDocumentModified(), and WriteFile().
TSceneKit* Document::m_scene [private]
Definition at line 78 of file Document.h.
Referenced by ClearScene(), GetSceneKit(), InitializeScene(), ReadFile(), and WriteFile().
The documentation for this class was generated from the following files:
Document.h
Document.cpp