Tonatiuh: ScriptRayTracer Class Reference
http://tonatiuh.googlecode.com
ScriptRayTracer Class Reference
Public Member Functions
ScriptRayTracer (QVector< TPhotonMapFactory * > listTPhotonMapFactory, QVector< RandomDeviateFactory * > listRandomDeviateFactory)
~ScriptRayTracer ()
void Clear ()
QString GetDir ()
bool IsValidPhotonMapType (QString type)
bool IsValidRandomGeneratorType (QString type)
bool IsValidSurface (QString surfaceName)
double GetArea ()
double GetNumrays ()
int SetDir (QString dir)
int SetExportAll (QString filename)
int SetExportSurface (QString filename, QString surfaceName, bool globalCoordinates)
int SetIrradiance (double irradiance)
int SetNumberOfRays (double nrays)
int SetNumberOfWidthDivisions (int wdivisions)
int SetNumberOfHeightDivisions (int hdivisions)
int SetPhotonMapType (QString typeName)
int SetRandomDeviateType (QString typeName)
void SetSunAzimtuh (double azimuth)
void SetSunElevation (double elevation)
void SetupGraphcisRoot ()
void SetupModels ()
int SetTonatiuhModelFile (QString filename)
int Trace ()
int SetSunPositionToScene ()
int SetDisconnectAllTrackers (bool disconnect)
int Save (const QString &fileName)
Private Attributes
Document * m_document
double m_irradiance
unsigned long m_numberOfRays
QVector< TPhotonMapFactory * > m_TPhotonMapFactoryList
int m_selectedPhotonMap
TPhotonMap * m_photonMap
QVector< RandomDeviateFactory * > m_RandomDeviateFactoryList
RandomDeviate * m_randomDeviate
SceneModel * m_sceneModel
double m_area
int m_widthDivisions
int m_heightDivisions
bool m_sunPosistionChanged
double m_sunAzimuth
double m_sunElevation
double m_wPhoton
QString m_dirName
Detailed Description
Definition at line 60 of file ScriptRayTracer.h.
Constructor & Destructor Documentation
ScriptRayTracer::ScriptRayTracer (QVector< TPhotonMapFactory * > listTPhotonMapFactory, QVector< RandomDeviateFactory * > listRandomDeviateFactory)
Definition at line 69 of file ScriptRayTracer.cpp.
ScriptRayTracer::~ScriptRayTracer ()
Definition at line 91 of file ScriptRayTracer.cpp.
References m_document, m_photonMap, m_randomDeviate, and m_sceneModel.
Member Function Documentation
void ScriptRayTracer::Clear ()
Definition at line 99 of file ScriptRayTracer.cpp.
References m_dirName, m_document, m_irradiance, m_numberOfRays, m_photonMap, m_randomDeviate, m_sceneModel, m_selectedPhotonMap, m_sunAzimuth, m_sunElevation, and m_wPhoton.
Referenced by tonatiuh_script::init().
double ScriptRayTracer::GetArea ()
Definition at line 448 of file ScriptRayTracer.cpp.
References m_area.
QString ScriptRayTracer::GetDir ()
Definition at line 118 of file ScriptRayTracer.cpp.
References m_dirName.
Referenced by tonatiuh_script::tonatiuh_export(), tonatiuh_script::tonatiuh_exportAll(), tonatiuh_script::tonatiuh_filename(), and tonatiuh_script::tonatiuh_saveas().
double ScriptRayTracer::GetNumrays ()
Definition at line 452 of file ScriptRayTracer.cpp.
References m_numberOfRays.
bool ScriptRayTracer::IsValidPhotonMapType (QString type)
Definition at line 123 of file ScriptRayTracer.cpp.
References m_TPhotonMapFactoryList.
Referenced by tonatiuh_script::tonatiuh_photon_map().
bool ScriptRayTracer::IsValidRandomGeneratorType (QString type)
Definition at line 138 of file ScriptRayTracer.cpp.
References m_RandomDeviateFactoryList.
Referenced by tonatiuh_script::tonatiuh_random_generator().
bool ScriptRayTracer::IsValidSurface (QString surfaceName)
Definition at line 153 of file ScriptRayTracer.cpp.
References SceneModel::IndexFromNodeUrl(), m_sceneModel, and SceneModel::NodeFromIndex().
Referenced by tonatiuh_script::tonatiuh_export().
int ScriptRayTracer::Save (const QString & fileName)
Definition at line 292 of file ScriptRayTracer.cpp.
References m_document, and Document::WriteFile().
Referenced by tonatiuh_script::tonatiuh_saveas().
int ScriptRayTracer::SetDir (QString dir)
Definition at line 164 of file ScriptRayTracer.cpp.
References m_dirName.
Referenced by ScriptEditorDialog::RunScript().
int ScriptRayTracer::SetDisconnectAllTrackers (bool disconnect)
Definition at line 280 of file ScriptRayTracer.cpp.
References SceneModel::DisconnectAllTrackers(), m_sceneModel, and SceneModel::ReconnectAllTrackers().
Referenced by tonatiuh_script::tonatiuh_setdisconnectalltrackers().
int ScriptRayTracer::SetExportAll (QString filename)
Definition at line 170 of file ScriptRayTracer.cpp.
References trf::ExportAll(), m_photonMap, and m_wPhoton.
Referenced by tonatiuh_script::tonatiuh_exportAll().
int ScriptRayTracer::SetExportSurface (QString filename, QString surfaceName, bool globalCoordinates)
Definition at line 175 of file ScriptRayTracer.cpp.
References trf::ExportSurfaceGlobalCoordinates(), trf::ExportSurfaceLocalCoordinates(), SceneModel::IndexFromNodeUrl(), m_photonMap, m_sceneModel, m_wPhoton, and SceneModel::NodeFromIndex().
Referenced by tonatiuh_script::tonatiuh_export().
int ScriptRayTracer::SetIrradiance (double irradiance)
Definition at line 187 of file ScriptRayTracer.cpp.
References m_irradiance.
Referenced by tonatiuh_script::tonatiuh_irradiance().
int ScriptRayTracer::SetNumberOfHeightDivisions (int hdivisions)
Definition at line 205 of file ScriptRayTracer.cpp.
References m_heightDivisions.
Referenced by tonatiuh_script::tonatiuh_numdivisions().
int ScriptRayTracer::SetNumberOfRays (double nrays)
Definition at line 193 of file ScriptRayTracer.cpp.
References m_numberOfRays.
Referenced by tonatiuh_script::tonatiuh_numrays().
int ScriptRayTracer::SetNumberOfWidthDivisions (int wdivisions)
Definition at line 199 of file ScriptRayTracer.cpp.
References m_widthDivisions.
Referenced by tonatiuh_script::tonatiuh_numdivisions().
int ScriptRayTracer::SetPhotonMapType (QString typeName)
Definition at line 210 of file ScriptRayTracer.cpp.
References m_selectedPhotonMap, and m_TPhotonMapFactoryList.
Referenced by tonatiuh_script::tonatiuh_photon_map().
int ScriptRayTracer::SetRandomDeviateType (QString typeName)
Definition at line 223 of file ScriptRayTracer.cpp.
References m_randomDeviate, and m_RandomDeviateFactoryList.
Referenced by tonatiuh_script::tonatiuh_random_generator().
void ScriptRayTracer::SetSunAzimtuh (double azimuth)
Saves the sun position azimuth value. azimuth is in degrees.
Definition at line 243 of file ScriptRayTracer.cpp.
References tgc::Degree, m_sunAzimuth, and m_sunPosistionChanged.
Referenced by tonatiuh_script::tonatiuh_calculatesun(), and tonatiuh_script::tonatiuh_sunposition().
void ScriptRayTracer::SetSunElevation (double elevation)
Saves the sun position elevation value. elevation is in degrees.
Definition at line 253 of file ScriptRayTracer.cpp.
References tgc::Degree, m_sunElevation, and m_sunPosistionChanged.
Referenced by tonatiuh_script::tonatiuh_calculatesun(), and tonatiuh_script::tonatiuh_sunposition().
int ScriptRayTracer::SetSunPositionToScene ()
Definition at line 259 of file ScriptRayTracer.cpp.
References TLightKit::ChangePosition(), InstanceNode::GetNode(), m_sceneModel, m_sunAzimuth, m_sunElevation, m_sunPosistionChanged, SceneModel::NodeFromIndex(), and tgc::Pi.
Referenced by tonatiuh_script::tonatiuh_calculatesun(), and tonatiuh_script::tonatiuh_setsunpositiontoscene().
int ScriptRayTracer::SetTonatiuhModelFile (QString filename)
Definition at line 305 of file ScriptRayTracer.cpp.
References Document::GetSceneKit(), m_document, m_sceneModel, Document::ReadFile(), and SceneModel::SetCoinScene().
Referenced by tonatiuh_script::tonatiuh_filename().
void ScriptRayTracer::SetupGraphcisRoot ()
void ScriptRayTracer::SetupModels ()
int ScriptRayTracer::Trace ()
Definition at line 322 of file ScriptRayTracer.cpp.
References TLightKit::ChangePosition(), InstanceNode::children, TLightKit::ComputeLightSourceArea(), trf::ComputeSceneTreeMap(), trf::CreatePhotonMap(), TSunShape::GetIrradiance(), InstanceNode::GetNode(), TLightShape::GetValidArea(), m_area, m_heightDivisions, m_irradiance, m_numberOfRays, m_photonMap, m_randomDeviate, m_sceneModel, m_selectedPhotonMap, m_sunAzimuth, m_sunElevation, m_sunPosistionChanged, m_TPhotonMapFactoryList, m_widthDivisions, m_wPhoton, SceneModel::NodeFromIndex(), tgc::Pi, SceneModel::PrepareAnalyze(), InstanceNode::SetIntersectionTransform(), TPhotonMap::StoredPhotons(), tgf::TransformFromSoTransform(), and SceneModel::UpdateSceneModel().
Referenced by tonatiuh_script::tonatiuh_trace().
Member Data Documentation
double ScriptRayTracer::m_area [private]
Definition at line 124 of file ScriptRayTracer.h.
Referenced by GetArea(), and Trace().
QString ScriptRayTracer::m_dirName [private]
Definition at line 133 of file ScriptRayTracer.h.
Referenced by Clear(), GetDir(), and SetDir().
Document* ScriptRayTracer::m_document [private]
Definition at line 109 of file ScriptRayTracer.h.
Referenced by Clear(), Save(), SetTonatiuhModelFile(), and ~ScriptRayTracer().
int ScriptRayTracer::m_heightDivisions [private]
Definition at line 126 of file ScriptRayTracer.h.
Referenced by SetNumberOfHeightDivisions(), and Trace().
double ScriptRayTracer::m_irradiance [private]
Definition at line 111 of file ScriptRayTracer.h.
Referenced by Clear(), SetIrradiance(), and Trace().
unsigned long ScriptRayTracer::m_numberOfRays [private]
Definition at line 113 of file ScriptRayTracer.h.
Referenced by Clear(), GetNumrays(), SetNumberOfRays(), and Trace().
TPhotonMap* ScriptRayTracer::m_photonMap [private]
Definition at line 117 of file ScriptRayTracer.h.
Referenced by Clear(), SetExportAll(), SetExportSurface(), Trace(), and ~ScriptRayTracer().
RandomDeviate* ScriptRayTracer::m_randomDeviate [private]
Definition at line 120 of file ScriptRayTracer.h.
Referenced by Clear(), SetRandomDeviateType(), Trace(), and ~ScriptRayTracer().
QVector< RandomDeviateFactory* > ScriptRayTracer::m_RandomDeviateFactoryList [private]
Definition at line 119 of file ScriptRayTracer.h.
Referenced by IsValidRandomGeneratorType(), and SetRandomDeviateType().
SceneModel* ScriptRayTracer::m_sceneModel [private]
Definition at line 122 of file ScriptRayTracer.h.
Referenced by Clear(), IsValidSurface(), SetDisconnectAllTrackers(), SetExportSurface(), SetSunPositionToScene(), SetTonatiuhModelFile(), Trace(), and ~ScriptRayTracer().
int ScriptRayTracer::m_selectedPhotonMap [private]
Definition at line 116 of file ScriptRayTracer.h.
Referenced by Clear(), SetPhotonMapType(), and Trace().
double ScriptRayTracer::m_sunAzimuth [private]
Definition at line 128 of file ScriptRayTracer.h.
Referenced by Clear(), SetSunAzimtuh(), SetSunPositionToScene(), and Trace().
double ScriptRayTracer::m_sunElevation [private]
Definition at line 129 of file ScriptRayTracer.h.
Referenced by Clear(), SetSunElevation(), SetSunPositionToScene(), and Trace().
bool ScriptRayTracer::m_sunPosistionChanged [private]
Definition at line 127 of file ScriptRayTracer.h.
Referenced by SetSunAzimtuh(), SetSunElevation(), SetSunPositionToScene(), and Trace().
QVector< TPhotonMapFactory* > ScriptRayTracer::m_TPhotonMapFactoryList [private]
Definition at line 115 of file ScriptRayTracer.h.
Referenced by IsValidPhotonMapType(), SetPhotonMapType(), and Trace().
int ScriptRayTracer::m_widthDivisions [private]
Definition at line 125 of file ScriptRayTracer.h.
Referenced by SetNumberOfWidthDivisions(), and Trace().
double ScriptRayTracer::m_wPhoton [private]
Definition at line 131 of file ScriptRayTracer.h.
Referenced by Clear(), SetExportAll(), SetExportSurface(), and Trace().
The documentation for this class was generated from the following files:
ScriptRayTracer.h
ScriptRayTracer.cpp