Tonatiuh: GraphicRoot Class Reference
http://tonatiuh.googlecode.com
GraphicRoot Class Reference
Signals
void ChangeSelection (SoSelection *selection)
Public Member Functions
GraphicRoot ()
~GraphicRoot ()
void AddGrid (SoSeparator *grid)
void AddRays (SoSeparator *rays)
void AddModel (TSceneKit *sceneModel)
void DeselectAll ()
SoSeparator * GetNode () const
void RemoveGrid ()
void RemoveRays ()
void RemoveModel ()
void Select (const SoPath *path)
void SelectionChanged (SoSelection *selection)
void ShowBackground (bool view)
void ShowGrid (bool view)
void ShowRays (bool view)
Private Member Functions
SoSeparator * CreateGrid (int xDimension, int zDimension, double xSpacing, double zSpacing)
Private Attributes
SoSeparator * m_graphicsRoot
SoSeparator * m_pGrid
SoSeparator * m_pRays
SoTransform * m_pRootTransform
SoSeparator * m_pSceneSeparator
SoSelection * m_pSelectionNode
GraphicRootTracker * m_pTracker
Detailed Description
Definition at line 52 of file GraphicRoot.h.
Constructor & Destructor Documentation
GraphicRoot::GraphicRoot ()
Definition at line 58 of file GraphicRoot.cpp.
References TTracker::ConnectParentTranform(), m_graphicsRoot, m_pRootTransform, m_pSceneSeparator, m_pSelectionNode, m_pTracker, and selectionFinishCallback().
GraphicRoot::~GraphicRoot ()
Definition at line 107 of file GraphicRoot.cpp.
References m_graphicsRoot, m_pGrid, m_pRays, m_pRootTransform, m_pSelectionNode, and m_pTracker.
Member Function Documentation
void GraphicRoot::AddGrid (SoSeparator * grid)
Definition at line 118 of file GraphicRoot.cpp.
References m_pGrid.
Referenced by MainWindow::ChangeGridSettings(), and MainWindow::SetupGraphcisRoot().
void GraphicRoot::AddModel (TSceneKit * sceneModel)
Definition at line 131 of file GraphicRoot.cpp.
References TSceneKit::azimuth, m_pSelectionNode, m_pTracker, TTracker::SetAzimuthAngle(), TTracker::SetSceneKit(), TTracker::SetZenithAngle(), and TSceneKit::zenith.
Referenced by MainWindow::ChangeModelScene(), and MainWindow::SetupGraphcisRoot().
void GraphicRoot::AddRays (SoSeparator * rays)
Definition at line 125 of file GraphicRoot.cpp.
References m_pRays, and RemoveRays().
Referenced by MainWindow::ShowRaysIn3DView().
void GraphicRoot::ChangeSelection (SoSelection * selection) [signal]
Referenced by SelectionChanged().
SoSeparator* GraphicRoot::CreateGrid (int xDimension, int zDimension, double xSpacing, double zSpacing) [private]
void GraphicRoot::DeselectAll ()
Definition at line 143 of file GraphicRoot.cpp.
References m_pSelectionNode.
Referenced by GraphicView::currentChanged().
SoSeparator * GraphicRoot::GetNode () const
Definition at line 148 of file GraphicRoot.cpp.
References m_graphicsRoot.
Referenced by MainWindow::on_actionSunPlane_triggered(), GraphicView::SetSceneGraph(), MainWindow::SetupModels(), and MainWindow::StartManipulation().
void GraphicRoot::RemoveGrid ()
Definition at line 153 of file GraphicRoot.cpp.
References m_pGrid, tgf::SevereError(), and ShowGrid().
Referenced by MainWindow::ChangeGridSettings().
void GraphicRoot::RemoveModel ()
Definition at line 180 of file GraphicRoot.cpp.
References TTracker::Disconnect(), m_pSelectionNode, m_pTracker, and TTracker::SetSceneKit().
Referenced by MainWindow::StartOver().
void GraphicRoot::RemoveRays ()
Definition at line 168 of file GraphicRoot.cpp.
References m_pRays, and tgf::SevereError().
Referenced by AddRays(), and MainWindow::StartOver().
void GraphicRoot::Select (const SoPath * path)
Definition at line 191 of file GraphicRoot.cpp.
References m_pSelectionNode.
Referenced by GraphicView::currentChanged().
void GraphicRoot::SelectionChanged (SoSelection * selection)
Definition at line 198 of file GraphicRoot.cpp.
References ChangeSelection().
Referenced by selectionFinishCallback().
void GraphicRoot::ShowBackground (bool view)
Definition at line 204 of file GraphicRoot.cpp.
References m_graphicsRoot.
Referenced by MainWindow::ShowBackground().
void GraphicRoot::ShowGrid (bool view)
Definition at line 232 of file GraphicRoot.cpp.
References m_graphicsRoot, and m_pGrid.
Referenced by MainWindow::ChangeGridSettings(), RemoveGrid(), and MainWindow::ShowGrid().
void GraphicRoot::ShowRays (bool view)
Definition at line 241 of file GraphicRoot.cpp.
References m_pRays, and m_pSceneSeparator.
Referenced by MainWindow::DisplayRays().
Member Data Documentation
SoSeparator* GraphicRoot::m_graphicsRoot [private]
Definition at line 85 of file GraphicRoot.h.
Referenced by GetNode(), GraphicRoot(), ShowBackground(), ShowGrid(), and ~GraphicRoot().
SoSeparator* GraphicRoot::m_pGrid [private]
Definition at line 86 of file GraphicRoot.h.
Referenced by AddGrid(), RemoveGrid(), ShowGrid(), and ~GraphicRoot().
SoSeparator* GraphicRoot::m_pRays [private]
Definition at line 87 of file GraphicRoot.h.
Referenced by AddRays(), RemoveRays(), ShowRays(), and ~GraphicRoot().
SoTransform* GraphicRoot::m_pRootTransform [private]
Definition at line 88 of file GraphicRoot.h.
Referenced by GraphicRoot(), and ~GraphicRoot().
SoSeparator* GraphicRoot::m_pSceneSeparator [private]
Definition at line 89 of file GraphicRoot.h.
Referenced by GraphicRoot(), and ShowRays().
SoSelection* GraphicRoot::m_pSelectionNode [private]
Definition at line 90 of file GraphicRoot.h.
Referenced by AddModel(), DeselectAll(), GraphicRoot(), RemoveModel(), Select(), and ~GraphicRoot().
GraphicRootTracker* GraphicRoot::m_pTracker [private]
Definition at line 91 of file GraphicRoot.h.
Referenced by AddModel(), GraphicRoot(), RemoveModel(), and ~GraphicRoot().
The documentation for this class was generated from the following files:
GraphicRoot.h
GraphicRoot.cpp