Tonatiuh: ParametersView Class Reference
http://tonatiuh.googlecode.com
ParametersView Class Reference
The ParametersView class provides a tabbed view for nodes parameters.
Public Slots
void SetValue (SoNode *node, QString paramenterName, QString newValue)
Signals
void valueModificated (SoNode *coinNode, QString parameterName, QString newValue)
Public Member Functions
ParametersView (QWidget *parent=0)
~ParametersView ()
void SelectionChangedToPart (SoNode *coinPart)
void SelectionChangedToKit (SoBaseKit *coinNode)
void UpdateView ()
Private Member Functions
void AddTab (SoNode *coinNode, QString partName)
QStringList ContainerNodeParts (SoBaseKit *coinNode)
Private Attributes
SoNode * m_actualCoinNode
bool m_isPart
Detailed Description
The ParametersView class provides a tabbed view for nodes parameters.
ParametersView provides a page for each of the parts of a node. The tab bar shows the node part name and the tab area shows the part parameters list.
The tab area containes a FieldContainerWidget.
See also:
FieldContainerWidget
Definition at line 57 of file ParametersView.h.
Constructor & Destructor Documentation
ParametersView::ParametersView (QWidget * parent = 0)
Creates a new ParametersView with parent parent.
Definition at line 49 of file ParametersView.cpp.
ParametersView::~ParametersView ()
Destroys the parameters view widget.
Definition at line 60 of file ParametersView.cpp.
Member Function Documentation
void ParametersView::AddTab (SoNode * coinNode, QString partName) [private]
Adds a new tab to the view with coinNode partName parameters.
Definition at line 155 of file ParametersView.cpp.
References SetValue(), and valueModificated().
Referenced by SelectionChangedToKit(), and SelectionChangedToPart().
QStringList ParametersView::ContainerNodeParts (SoBaseKit * coinNode) [private]
Returns the names of the parts of the coinNode that the view shows.
If the coinNode is not a container node, return a empty list.
Definition at line 170 of file ParametersView.cpp.
Referenced by SelectionChangedToKit().
void ParametersView::SelectionChangedToKit (SoBaseKit * coinNode)
Changes the parameters view to show coinNode parts parameters.
Definition at line 98 of file ParametersView.cpp.
References AddTab(), ContainerNodeParts(), m_actualCoinNode, and m_isPart.
Referenced by MainWindow::ChangeSelection(), and UpdateView().
void ParametersView::SelectionChangedToPart (SoNode * coinPart)
Changes the parameters view to show coinNode parts parameters.
Definition at line 69 of file ParametersView.cpp.
References AddTab(), m_actualCoinNode, and m_isPart.
Referenced by MainWindow::ChangeSelection(), and UpdateView().
void ParametersView::SetValue (SoNode * node, QString paramenterName, QString newValue) [slot]
Emits a valueModificated signal with node as the actual node, paramenterName and newValue.
Definition at line 147 of file ParametersView.cpp.
References valueModificated().
Referenced by AddTab().
void ParametersView::UpdateView ()
Updates selected node parametes views.
Definition at line 138 of file ParametersView.cpp.
References m_actualCoinNode, m_isPart, SelectionChangedToKit(), and SelectionChangedToPart().
Referenced by MainWindow::DefineSunLight().
void ParametersView::valueModificated (SoNode * coinNode, QString parameterName, QString newValue) [signal]
Emmits a signal when a parameters of the view is modified.
The modified paramenters is a coinNode paramenter named parameterName.
The new value for the parameter is newValue.
Referenced by AddTab(), and SetValue().
Member Data Documentation
SoNode* ParametersView::m_actualCoinNode [private]
Definition at line 86 of file ParametersView.h.
Referenced by SelectionChangedToKit(), SelectionChangedToPart(), and UpdateView().
bool ParametersView::m_isPart [private]
Definition at line 87 of file ParametersView.h.
Referenced by SelectionChangedToKit(), SelectionChangedToPart(), and UpdateView().
The documentation for this class was generated from the following files:
ParametersView.h
ParametersView.cpp