Tonatiuh: TPhotonMap Class Reference
http://tonatiuh.googlecode.com
TPhotonMap Class Reference
TPhotonMap is the interface of the structures to store photons.
Public Member Functions
TPhotonMap ()
virtual ~TPhotonMap ()
virtual QString GetIcon ()=0
virtual std::vector< Photon * > GetAllPhotons () const =0
virtual std::vector< Photon * > GetSurfacePhotons (InstanceNode *instance) const =0
virtual void StoreRay (Photon *rayFirstPhoton, int rayLength)=0
virtual unsigned long StoredPhotons () const =0
Detailed Description
TPhotonMap is the interface of the structures to store photons.
This interface define the functions needed to a correct use and access to the photon map.
Definition at line 58 of file TPhotonMap.h.
Constructor & Destructor Documentation
TPhotonMap::TPhotonMap ()
Constructor.
Definition at line 46 of file TPhotonMap.cpp.
TPhotonMap::~TPhotonMap () [virtual]
Destructor.
Definition at line 55 of file TPhotonMap.cpp.
Member Function Documentation
virtual std::vector< Photon* > TPhotonMap::GetAllPhotons () const [pure virtual]
Referenced by trf::DrawPhotonMapPoints(), trf::DrawPhotonMapRays(), and trf::ExportAll().
virtual QString TPhotonMap::GetIcon () [pure virtual]
virtual std::vector< Photon* > TPhotonMap::GetSurfacePhotons (InstanceNode * instance) const [pure virtual]
Referenced by trf::ExportSurfaceGlobalCoordinates(), and trf::ExportSurfaceLocalCoordinates().
virtual unsigned long TPhotonMap::StoredPhotons () const [pure virtual]
Referenced by ScriptRayTracer::Trace().
virtual void TPhotonMap::StoreRay (Photon * rayFirstPhoton, int rayLength) [pure virtual]
Referenced by trf::CreatePhotonMap().
The documentation for this class was generated from the following files:
TPhotonMap.h
TPhotonMap.cpp