Tonatiuh: NodeNameDelegate Class Reference
http://tonatiuh.googlecode.com
NodeNameDelegate Class Reference
NodeNameDelegate class to facility editing the name of a node.
Public Member Functions
NodeNameDelegate (QObject *parent=0)
~NodeNameDelegate ()
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
void setEditorData (QWidget *editor, const QModelIndex &index) const
Detailed Description
NodeNameDelegate class to facility editing the name of a node.
NodeNameDelegate can be used to display and edit the name of a selected node. When a node is selected to edit this class shows an editor with a validator to enable only names with a valid regular expresion.
Definition at line 51 of file NodeNameDelegate.h.
Constructor & Destructor Documentation
NodeNameDelegate::NodeNameDelegate (QObject * parent = 0)
Creates a new delegate to facilitate editing node names.
Definition at line 54 of file NodeNameDelegate.cpp.
NodeNameDelegate::~NodeNameDelegate ()
Destroys the NodeNameDelegate.
Definition at line 63 of file NodeNameDelegate.cpp.
Member Function Documentation
QWidget * NodeNameDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const
Returns a line edit editor with a validates the input names. The names must start with a alphabetic character and optionally followed with some alphanumeric characters.
Definition at line 72 of file NodeNameDelegate.cpp.
void NodeNameDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const
Takes the name of the selected node and sets to de editor to display it.
Definition at line 86 of file NodeNameDelegate.cpp.
References SceneModel::data(), InstanceNode::GetNode(), and SceneModel::NodeFromIndex().
The documentation for this class was generated from the following files:
NodeNameDelegate.h
NodeNameDelegate.cpp