Tonatiuh: LineNumberWidget Class Reference
http://tonatiuh.googlecode.com
LineNumberWidget Class Reference
Public Slots
void UpdateLineNumberArea (const QRect &rect, int dy)
Public Member Functions
LineNumberWidget (QWidget *parent=0, Qt::WindowFlags f=0)
~LineNumberWidget ()
void SetCodeEditor (CodeEditArea *editor)
QSize sizeHint () const
int LineNumberAreaWidth () const
Protected Member Functions
void paintEvent (QPaintEvent *event)
Private Attributes
CodeEditArea * m_codeEditArea
Detailed Description
Definition at line 47 of file LineNumberWidget.h.
Constructor & Destructor Documentation
LineNumberWidget::LineNumberWidget (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 46 of file LineNumberWidget.cpp.
LineNumberWidget::~LineNumberWidget ()
Definition at line 53 of file LineNumberWidget.cpp.
Member Function Documentation
int LineNumberWidget::LineNumberAreaWidth () const
Definition at line 68 of file LineNumberWidget.cpp.
References m_codeEditArea.
Referenced by sizeHint(), CodeEditorWidget::UpdateCodeEditorWidth(), and UpdateLineNumberArea().
void LineNumberWidget::paintEvent (QPaintEvent * event) [protected]
Definition at line 93 of file LineNumberWidget.cpp.
References CodeEditArea::BlockHeight(), CodeEditArea::BlockTop(), and m_codeEditArea.
void LineNumberWidget::SetCodeEditor (CodeEditArea * editor)
Definition at line 58 of file LineNumberWidget.cpp.
References m_codeEditArea.
Referenced by CodeEditorWidget::CodeEditorWidget().
QSize LineNumberWidget::sizeHint () const
Definition at line 63 of file LineNumberWidget.cpp.
References LineNumberAreaWidth().
void LineNumberWidget::UpdateLineNumberArea (const QRect & rect, int dy) [slot]
Definition at line 83 of file LineNumberWidget.cpp.
References LineNumberAreaWidth(), and m_codeEditArea.
Member Data Documentation
CodeEditArea* LineNumberWidget::m_codeEditArea [private]
Definition at line 67 of file LineNumberWidget.h.
Referenced by LineNumberAreaWidth(), paintEvent(), SetCodeEditor(), and UpdateLineNumberArea().
The documentation for this class was generated from the following files:
LineNumberWidget.h
LineNumberWidget.cpp