Tonatiuh: MainWindow Class Reference
http://tonatiuh.googlecode.com
MainWindow Class Reference
Main window class.
Public Slots
void ChangeSunPosition (double azimuth, double elevation)
void ChangeSunPosition (int year, int month, int day, double hours, double minutes, double seconds, double latitude, double longitude)
void Copy ()
void Copy (QString nodeURL)
void CreateGroupNode ()
void CreateAnalyzerNode ()
void CreateMaterial (QString materialType)
void CreateShape (QString shapeType)
void CreateSurfaceNode ()
void CreateTracker (QString trackerType)
void Cut ()
void Cut (QString nodeURL)
void Delete ()
void Delete (QString nodeURL)
int ExportAllPhotonMap (QString fileName)
int ExportPhotonMap (QString fileName, QString nodeUrl, bool globalCoord)
void InsertFileComponent (QString componentFileName=QString(""))
void New ()
void Open (QString fileName)
void Paste (QString nodeURL, QString pasteType=QString("Shared"))
void PasteCopy ()
void PasteLink ()
void Run ()
void ResetAnalyzerValues ()
void SaveAs (QString fileName)
void SelectNode (QString nodeUrl)
void SetAimingPointAbsolute ()
void SetAimingPointRelative ()
void SetIncreasePhtonMap (bool increase)
void SetNodeName (QString nodeName)
void SetPhotonMapType (QString typeName)
void SetRandomDeviateType (QString typeName)
void SetRayCastingGrid (int widthDivisions, int heightDivisions)
void SetRaysDrawingOptions (double raysFaction, bool drawPhotons)
void SetRaysPerIteration (unsigned int rays)
void SetSunshape (QString sunshapeType)
void SetSunshapeParameter (QString parameter, QString value)
void SetTransmissivity (QString transmissivityType)
void SetTransmissivityParameter (QString parameter, QString value)
void SetValue (QString nodeUrl, QString parameter, QString value)
Signals
void Abort (QString error)
Public Member Functions
MainWindow (QString tonatiuhFile=0, QWidget *parent=0, Qt::WindowFlags flags=0)
~MainWindow ()
void FinishManipulation ()
void StartManipulation (SoDragger *dragger)
Protected Member Functions
void closeEvent (QCloseEvent *event)
void mousePressEvent (QMouseEvent *e)
Private Types
enum { m_maxRecentFiles = 7 }
Private Slots
void CalculateSunPosition ()
void ChangeGridSettings ()
void ChangeNodeName (const QModelIndex &index, const QString &newName)
void ChangeSelection (const QModelIndex &current)
void CreateMaterial (TMaterialFactory *pTMaterialFactory)
void CreateShape (TShapeFactory *pTShapeFactory)
void CreateTracker (TTrackerFactory *pTTrackerFactory)
void DefineSunLight ()
void DefineTransmissivity ()
void DisconnectAllTrackers (bool disconnect)
void DisplayRays (bool display)
void ExportPhotonMap ()
void InsertUserDefinedComponent ()
void ItemDragAndDrop (const QModelIndex &newParent, const QModelIndex &node)
void ItemDragAndDropCopy (const QModelIndex &newParent, const QModelIndex &node)
void Open ()
void OpenRecentFile ()
void Redo ()
bool Save ()
bool SaveAs ()
bool SaveComponent ()
void SelectionFinish (SoSelection *selection)
void SetParameterValue (SoNode *node, QString paramenterName, QString newValue)
void SetSunPositionCalculatorEnabled (int enabled)
void ShowBackground ()
void ShowCommandView ()
void ShowGrid ()
void ShowMenu (const QModelIndex &index)
void ShowRayTracerOptionsDialog ()
void ShowWarning (QString message)
void Undo ()
SbVec3f getTargetOfCamera (SoCamera *cam)
void SoTransform_to_SoCenterballManip ()
void SoTransform_to_SoJackManip ()
void SoTransform_to_SoHandleBoxManip ()
void SoTransform_to_SoTabBoxManip ()
void SoTransform_to_SoTrackballManip ()
void SoTransform_to_SoTransformBoxManip ()
void SoTransform_to_SoTransformerManip ()
void SoManip_to_SoTransform ()
void on_actionAxis_toggled ()
void on_actionEdit_Mode_toggled ()
void on_actionSunPlane_triggered ()
void on_action_X_Y_Plane_triggered ()
void on_action_X_Z_Plane_triggered ()
void on_action_Y_Z_Plane_triggered ()
void on_actionOpenScriptEditor_triggered ()
void on_actionAbout_triggered ()
void on_actionCheckForUpdates_triggered ()
Private Member Functions
void ChangeModelScene ()
SoSeparator * CreateGrid (int xDimension, int zDimension, double xSpacing, double zSpacing)
QToolBar * CreateMaterialsTooBar (QMenu *pMaterialsMenu)
QToolBar * CreateTrackerTooBar (QMenu *pMaterialsMenu)
bool Delete (QModelIndex index)
QSplitter * GetHorizontalSplitterPointer ()
bool OkToContinue ()
bool Paste (QModelIndex nodeIndex, tgc::PasteType type)
void SetAimingPointRelativity (bool relative)
bool SetAimingPointRelativity (QModelIndex nodeIndex, bool relative)
QDir PluginDirectory ()
void ReadSettings ()
bool ReadyForRaytracing (InstanceNode *&rootSeparatorInstance, InstanceNode *&lightInstance, SoTransform *&lightTransform, TSunShape *&sunShape, TLightShape *&shape, TTransmissivity *&transmissivity)
bool SaveFile (const QString &fileName)
void SetCurrentFile (const QString &fileName)
void SetupActions ()
void SetupActionsInsertMaterial ()
void SetupActionsInsertShape ()
void SetupActionsInsertTracker ()
void SetupCommandView ()
void SetupDocument ()
void SetupGraphcisRoot ()
void SetupGraphicView ()
void SetupMenus ()
void SetupModels ()
void SetupParametersView ()
void SetupPluginsManager ()
void SetupTreeView ()
void SetupTriggers ()
void SetupViews ()
void SetupUpdateManager ()
void ShowRaysIn3DView ()
bool StartOver (const QString &fileName)
QString StrippedName (const QString &fullFileName)
void UpdateRecentFileActions ()
void WriteSettings ()
Private Attributes
QUndoStack * m_commandStack
QUndoView * m_commandView
QString m_currentFile
Document * m_document
QStringList m_recentFiles
QAction ** m_recentFileActions
QToolBar * m_materialsToolBar
QToolBar * m_photonMapToolBar
QToolBar * m_shapeToolBar
QToolBar * m_trackersToolBar
PluginManager * m_pluginManager
UpdatesManager * m_updateManager
SceneModel * m_sceneModel
QItemSelectionModel * m_selectionModel
RandomDeviate * m_rand
int m_selectedRandomDeviate
TPhotonMap * m_photonMap
int m_selectedPhotonMap
bool m_increasePhotonMap
QString m_lastExportFileName
QString m_lastExportSurfaceUrl
bool m_lastExportInGlobal
GraphicRoot * m_graphicsRoot
SoNode * m_coinNode_Buffer
QStringList * m_manipulators_Buffer
unsigned long m_tracedRays
unsigned long m_raysPerIteration
double m_fraction
bool m_drawPhotons
int m_gridXElements
int m_gridZElements
double m_gridXSpacing
double m_gridZSpacing
std::vector< GraphicView * > m_graphicView
int m_focusView
int m_heightDivisions
int m_widthDivisions
Detailed Description
Main window class.
Tonatiuh's main window class. It includes the menu bars and all the actions, signals and slots to provide user interaction with the program.
Definition at line 78 of file MainWindow.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
m_maxRecentFiles
Definition at line 244 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QString tonatiuhFile = 0, QWidget * parent = 0, Qt::WindowFlags flags = 0)
Creates a new MainWindow object.
Definition at line 153 of file MainWindow.cpp.
References ReadSettings(), SetupActions(), SetupDocument(), SetupGraphcisRoot(), SetupMenus(), SetupModels(), SetupPluginsManager(), SetupTriggers(), SetupUpdateManager(), SetupViews(), and StartOver().
MainWindow::~MainWindow ()
Destroyes MainWindow object.
Definition at line 212 of file MainWindow.cpp.
References m_commandStack, m_commandView, m_document, m_photonMap, m_pluginManager, m_rand, m_recentFileActions, m_sceneModel, and m_updateManager.
Member Function Documentation
void MainWindow::Abort (QString error) [signal]
Referenced by Copy(), CreateAnalyzerNode(), CreateGroupNode(), CreateMaterial(), CreateShape(), CreateTracker(), Cut(), Delete(), InsertFileComponent(), New(), Open(), Paste(), PasteCopy(), PasteLink(), Run(), SaveAs(), SetNodeName(), SetPhotonMapType(), SetRandomDeviateType(), SetSunshape(), SetSunshapeParameter(), SetTransmissivity(), SetTransmissivityParameter(), and SetValue().
void MainWindow::CalculateSunPosition () [private, slot]
Shows a dialog to allow define current light position with a position calculator.
Definition at line 2602 of file MainWindow.cpp.
References ChangeSunPosition(), Document::GetSceneKit(), and m_document.
Referenced by SetupTriggers().
void MainWindow::ChangeGridSettings () [private, slot]
Changes the number of the grid cells and grid cell dimensions.
Definition at line 1025 of file MainWindow.cpp.
References GraphicRoot::AddGrid(), InstanceNode::children, CreateGrid(), InstanceNode::GetNode(), GridSettingsDialog::GetXDimension(), GridSettingsDialog::GetXSpacing(), GridSettingsDialog::GetZDimension(), GridSettingsDialog::GetZSpacing(), GridSettingsDialog::IsSizeDefined(), m_graphicsRoot, m_gridXElements, m_gridXSpacing, m_gridZElements, m_gridZSpacing, m_sceneModel, SceneModel::NodeFromIndex(), GraphicRoot::RemoveGrid(), and GraphicRoot::ShowGrid().
Referenced by SetupTriggers().
void MainWindow::ChangeModelScene () [private]
Set current document coin scene into Tonatiuh Models and views.
Definition at line 2582 of file MainWindow.cpp.
References GraphicRoot::AddModel(), InstanceNode::children, InstanceNode::GetNodeURL(), Document::GetSceneKit(), SceneModel::IndexFromNodeUrl(), m_document, m_graphicsRoot, m_sceneModel, m_selectionModel, SceneModel::NodeFromIndex(), and SceneModel::SetCoinScene().
Referenced by StartOver().
void MainWindow::ChangeNodeName (const QModelIndex & index, const QString & newName) [private, slot]
Definition at line 1078 of file MainWindow.cpp.
References InstanceNode::GetNode(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), and Document::SetDocumentModified().
Referenced by SetNodeName(), and SetupTreeView().
void MainWindow::ChangeSelection (const QModelIndex & current) [private, slot]
Definition at line 2393 of file MainWindow.cpp.
References InstanceNode::GetNode(), m_sceneModel, and SceneModel::NodeFromIndex().
Referenced by SetupGraphcisRoot(), SetupParametersView(), SoManip_to_SoTransform(), SoTransform_to_SoCenterballManip(), SoTransform_to_SoHandleBoxManip(), SoTransform_to_SoJackManip(), SoTransform_to_SoTabBoxManip(), SoTransform_to_SoTrackballManip(), SoTransform_to_SoTransformBoxManip(), and SoTransform_to_SoTransformerManip().
void MainWindow::ChangeSunPosition (double azimuth, double elevation) [slot]
Changes the light position to the position defined by azimuth and elevation. The parameters are defined in degree.
Definition at line 1099 of file MainWindow.cpp.
References tgc::Degree, Document::GetSceneKit(), m_commandStack, m_document, m_sceneModel, Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
Referenced by CalculateSunPosition(), and ChangeSunPosition().
void MainWindow::ChangeSunPosition (int year, int month, int day, double hours, double minutes, double seconds, double latitude, double longitude) [slot]
Sets the sun position for the localitation given by latitude and longitude coordinates. Latitude is positive for North and positive longitude for east. The time defined by year, month and day, hours, minustes and seconds is ut time.
Definition at line 1123 of file MainWindow.cpp.
References ChangeSunPosition(), cSunCoordinates::dAzimuth, cSunCoordinates::dZenithAngle, and sunpos().
void MainWindow::closeEvent (QCloseEvent * event) [protected]
Definition at line 2533 of file MainWindow.cpp.
References OkToContinue(), and WriteSettings().
void MainWindow::Copy () [slot]
Copies current node to the clipboard. The current node cannot be the model root node or concentrator node.
Definition at line 1148 of file MainWindow.cpp.
References Abort(), m_coinNode_Buffer, m_commandStack, m_document, m_sceneModel, m_selectionModel, and Document::SetDocumentModified().
Referenced by SetupTriggers().
void MainWindow::Copy (QString nodeURL) [slot]
Copies the node defined with the nodeURL to the clipboard.
The current node cannot be the model root node or concentrator node.
Definition at line 1177 of file MainWindow.cpp.
References Abort(), SceneModel::IndexFromNodeUrl(), m_coinNode_Buffer, m_commandStack, m_document, m_sceneModel, and Document::SetDocumentModified().
void MainWindow::CreateAnalyzerNode () [slot]
Creates a new analyzer node as a selected node child.
Definition at line 1259 of file MainWindow.cpp.
References Abort(), InstanceNode::GetNode(), SceneModel::index(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), SceneModel::SetNodeName(), and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
SoSeparator * MainWindow::CreateGrid (int xDimension, int zDimension, double xSpacing, double zSpacing) [private]
Creates a xDimension by zDimension grid and shows in the 3D view. Each grid cell is a xSpacing x zSpacing.
Definition at line 2620 of file MainWindow.cpp.
Referenced by ChangeGridSettings(), and SetupGraphcisRoot().
void MainWindow::CreateGroupNode () [slot]
Creates a new group node as a selected node child.
Definition at line 1203 of file MainWindow.cpp.
References Abort(), InstanceNode::GetNode(), SceneModel::index(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), SceneModel::SetNodeName(), and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
void MainWindow::CreateMaterial (QString materialType) [slot]
Creates a materialType material node from the as current selected node child.
If the current node is not a surface type node or materialType is not a valid type, the material node will not be created.
Definition at line 1305 of file MainWindow.cpp.
References Abort(), PluginManager::GetMaterialFactories(), and m_pluginManager.
Referenced by SetupActionsInsertMaterial().
void MainWindow::CreateMaterial (TMaterialFactory * pTMaterialFactory) [private, slot]
Creates a material node from the pTMaterialFactory as current selected node child.
If the current node is not a surface type node, the material node will not be created.
Definition at line 2417 of file MainWindow.cpp.
References TMaterialFactory::CreateTMaterial(), InstanceNode::GetNode(), SceneModel::index(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), TMaterialFactory::TMaterialName(), and SceneModel::UpdateSceneModel().
QToolBar * MainWindow::CreateMaterialsTooBar (QMenu * pMaterialsMenu) [private]
Creates a toolbar for insert material actions.
Definition at line 2684 of file MainWindow.cpp.
References tgf::SevereError().
Referenced by SetupActionsInsertMaterial().
void MainWindow::CreateShape (QString shapeType) [slot]
Creates a shapeType shape node from the as current selected node child.
If the current node is not a valid parent node or shapeType is not a valid type, the shape node will not be created.
Definition at line 1330 of file MainWindow.cpp.
References Abort(), PluginManager::GetShapeFactories(), and m_pluginManager.
Referenced by SetupActionsInsertShape().
void MainWindow::CreateShape (TShapeFactory * pTShapeFactory) [private, slot]
Creates a shape node from the pTShapeFactory as current selected node child.
If the current node is not a surface type node, the shape node will not be created.
Creates a shape node from the pTTrackerFactory as current selected node child.
Definition at line 2459 of file MainWindow.cpp.
References TShapeFactory::CreateTShape(), InstanceNode::GetNode(), SceneModel::index(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), TShapeFactory::TShapeName(), and SceneModel::UpdateSceneModel().
void MainWindow::CreateSurfaceNode () [slot]
Creates a surface node as selected node child.
Definition at line 1352 of file MainWindow.cpp.
References InstanceNode::GetNode(), SceneModel::index(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), SceneModel::SetNodeName(), and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
void MainWindow::CreateTracker (QString trackerType) [slot]
Creates a trackerType shape node from the as current selected node child.
If the current node is not a valid parent node or trackerType is not a valid type, the shape node will not be created.
Definition at line 1396 of file MainWindow.cpp.
References Abort(), PluginManager::GetTrackerFactories(), and m_pluginManager.
Referenced by SetupActionsInsertTracker().
void MainWindow::CreateTracker (TTrackerFactory * pTTrackerFactory) [private, slot]
Definition at line 2494 of file MainWindow.cpp.
References TTrackerFactory::CreateTTracker(), InstanceNode::GetNode(), TSeparatorKit::getPart(), Document::GetSceneKit(), SceneModel::index(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), TTracker::SetSceneKit(), TTrackerFactory::TTrackerName(), and SceneModel::UpdateSceneModel().
QToolBar * MainWindow::CreateTrackerTooBar (QMenu * pTrackersMenu) [private]
Creates a toolbar for insert trackers actions.
Definition at line 2698 of file MainWindow.cpp.
References tgf::SevereError().
Referenced by SetupActionsInsertTracker().
void MainWindow::Cut () [slot]
If there is a node selected and this node is not the root node, cuts current selected node from the model. Otherwise, nothing is done.
Definition at line 1418 of file MainWindow.cpp.
References Abort(), m_coinNode_Buffer, m_commandStack, m_document, m_sceneModel, m_selectionModel, Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
void MainWindow::Cut (QString nodeURL) [slot]
If there nodeURL is a valid node url and this node is not the root node, cuts current selected node from the model. Otherwise, nothing is done.
Definition at line 1439 of file MainWindow.cpp.
References Abort(), SceneModel::IndexFromNodeUrl(), m_coinNode_Buffer, m_commandStack, m_document, m_sceneModel, Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
void MainWindow::DefineSunLight () [private, slot]
Defines Tonatiuh model light paramenters with a dilog window.
Definition at line 299 of file MainWindow.cpp.
References InstanceNode::children, InstanceNode::GetNodeURL(), Document::GetSceneKit(), PluginManager::GetShapeFactories(), PluginManager::GetSunShapeFactories(), LightDialog::GetTLightKit(), SceneModel::IndexFromNodeUrl(), m_commandStack, m_document, m_pluginManager, m_sceneModel, m_selectionModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
void MainWindow::DefineTransmissivity () [private, slot]
Defines Tonatiuh model light parameters using a script.
Opens a dialog to define the scene transmissivity.
Definition at line 403 of file MainWindow.cpp.
References Document::GetSceneKit(), PluginManager::GetTransmissivityFactories(), m_commandStack, m_document, m_pluginManager, and Document::SetDocumentModified().
Referenced by SetupTriggers().
void MainWindow::Delete () [slot]
* Deletes selected node if there is a valid node to delete.
Definition at line 1476 of file MainWindow.cpp.
References Abort(), InstanceNode::GetNodeURL(), InstanceNode::GetParent(), SceneModel::IndexFromNodeUrl(), m_sceneModel, m_selectionModel, and SceneModel::NodeFromIndex().
Referenced by Delete(), and SetupTriggers().
void MainWindow::Delete (QString nodeURL) [slot]
Creates a new delete command, where the node with the nodeURL was deleted.
If nodeURL is not a valid node url, nothing is done.
Definition at line 1498 of file MainWindow.cpp.
References Abort(), Delete(), SceneModel::IndexFromNodeUrl(), m_sceneModel, and m_selectionModel.
bool MainWindow::Delete (QModelIndex index) [private]
Creates a new delete command, where the index node was deleted.
Returns true if the node was successfully deleted, otherwise returns false.
Definition at line 2714 of file MainWindow.cpp.
References InstanceNode::GetNode(), Document::GetSceneKit(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
void MainWindow::DisconnectAllTrackers (bool disconnect) [private, slot]
Define the scene transmissivity without opening a dialog.
Definition at line 447 of file MainWindow.cpp.
References SceneModel::DisconnectAllTrackers(), m_sceneModel, and SceneModel::ReconnectAllTrackers().
Referenced by SetupTriggers().
void MainWindow::DisplayRays (bool display) [private, slot]
If actionDisplay_rays is checked the 3D view shows rays representation. Otherwise the representation is hidden.
Definition at line 457 of file MainWindow.cpp.
References m_graphicsRoot, and GraphicRoot::ShowRays().
Referenced by SetupTriggers().
int MainWindow::ExportAllPhotonMap (QString fileName) [slot]
Save all photon map data into fileName file.
Definition at line 1514 of file MainWindow.cpp.
References trf::ExportAll(), TSunShape::GetIrradiance(), Document::GetSceneKit(), TLightShape::GetValidArea(), m_document, m_lastExportFileName, m_photonMap, and m_tracedRays.
Referenced by ExportPhotonMap().
int MainWindow::ExportPhotonMap (QString fileName, QString nodeUrl, bool globalCoord) [slot]
Writes the nodeUrl surface photon's data at file fileName. If globalCoord is true the photon coordinates will be written in scene coordintes. Otherwise, in surface local coordinates.
Definition at line 1546 of file MainWindow.cpp.
References trf::ExportSurfaceGlobalCoordinates(), trf::ExportSurfaceLocalCoordinates(), TSunShape::GetIrradiance(), Document::GetSceneKit(), TLightShape::GetValidArea(), SceneModel::IndexFromNodeUrl(), m_document, m_lastExportFileName, m_lastExportInGlobal, m_lastExportSurfaceUrl, m_photonMap, m_sceneModel, m_tracedRays, and SceneModel::NodeFromIndex().
void MainWindow::ExportPhotonMap () [private, slot]
Writes the photons stored at the photon map at user defined file. Creates a dialog to define the export paramenters.
Definition at line 469 of file MainWindow.cpp.
References ExportAllPhotonMap(), ExportDialog::ExportAllPhotonMap(), ExportDialog::ExportPhotonsInGlobal(), ExportDialog::GetExportFileName(), ExportDialog::GetSelectedSurface(), m_lastExportFileName, m_lastExportInGlobal, m_lastExportSurfaceUrl, m_photonMap, and m_sceneModel.
Referenced by SetupTriggers().
void MainWindow::FinishManipulation ()
Finish the manipulation of the current selected node.
Definition at line 228 of file MainWindow.cpp.
References InstanceNode::GetNode(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
Referenced by finishManipulator().
QSplitter * MainWindow::GetHorizontalSplitterPointer () [private]
Return horizontalSplitter splitter object.
Definition at line 2747 of file MainWindow.cpp.
References tgf::SevereError().
SbVec3f MainWindow::getTargetOfCamera (SoCamera * cam) [private, slot]
Definition at line 943 of file MainWindow.cpp.
Referenced by on_action_X_Y_Plane_triggered(), on_action_X_Z_Plane_triggered(), on_action_Y_Z_Plane_triggered(), and on_actionSunPlane_triggered().
void MainWindow::InsertFileComponent (QString componentFileName = QString("")) [slot]
Inserts an existing tonatiuh component into the tonatiuh model as a selected node child.
The component is saved into componentFileName file.
Definition at line 1619 of file MainWindow.cpp.
References Abort(), InstanceNode::GetNode(), SceneModel::index(), m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
Referenced by InsertUserDefinedComponent().
void MainWindow::InsertUserDefinedComponent () [private, slot]
Inserts an existing tonatiuh component into the tonatiuh model as a selected node child.
A open file dialog is opened to select the file where the existing component is saved.
Definition at line 513 of file MainWindow.cpp.
References InstanceNode::GetNode(), SceneModel::index(), InsertFileComponent(), m_sceneModel, and SceneModel::NodeFromIndex().
Referenced by SetupTriggers().
void MainWindow::ItemDragAndDrop (const QModelIndex & newParent, const QModelIndex & node) [private, slot]
Moves the scene node with index node to the parent with index newParent.
Definition at line 537 of file MainWindow.cpp.
References tgc::Copied, InstanceNode::GetNode(), InstanceNode::GetParent(), m_coinNode_Buffer, m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
Referenced by SetupTreeView().
void MainWindow::ItemDragAndDropCopy (const QModelIndex & newParent, const QModelIndex & node) [private, slot]
Inserts a copy of the node node as a newParent child.
Definition at line 564 of file MainWindow.cpp.
References InstanceNode::GetNode(), m_coinNode_Buffer, m_commandStack, m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), tgc::Shared, and SceneModel::UpdateSceneModel().
Referenced by SetupTreeView().
void MainWindow::mousePressEvent (QMouseEvent * e) [protected]
Receives mouse press event e, an sets as active 3D view the view that contains the mouse press position.
Definition at line 2546 of file MainWindow.cpp.
References m_focusView.
void MainWindow::New () [slot]
Starts new tonatiuh empty model.
Definition at line 1670 of file MainWindow.cpp.
References Abort(), OkToContinue(), and StartOver().
Referenced by SetupTriggers().
bool MainWindow::OkToContinue () [private]
Returns true if the application is ready to start with other model. Otherwise, returns false.
Definition at line 2758 of file MainWindow.cpp.
References Document::IsModified(), m_document, and Save().
Referenced by closeEvent(), New(), Open(), and OpenRecentFile().
void MainWindow::on_action_X_Y_Plane_triggered () [private, slot]
Definition at line 955 of file MainWindow.cpp.
References getTargetOfCamera(), m_focusView, and m_graphicView.
Referenced by SetupGraphicView().
void MainWindow::on_action_X_Z_Plane_triggered () [private, slot]
Definition at line 969 of file MainWindow.cpp.
References getTargetOfCamera(), m_focusView, and m_graphicView.
Referenced by SetupGraphicView().
void MainWindow::on_action_Y_Z_Plane_triggered () [private, slot]
Definition at line 981 of file MainWindow.cpp.
References getTargetOfCamera(), m_focusView, and m_graphicView.
Referenced by SetupGraphicView().
void MainWindow::on_actionAbout_triggered () [private, slot]
Definition at line 1007 of file MainWindow.cpp.
void MainWindow::on_actionAxis_toggled () [private, slot]
Definition at line 874 of file MainWindow.cpp.
References m_graphicView.
void MainWindow::on_actionCheckForUpdates_triggered () [private, slot]
Checks for Stephanie's updates and installs them.
Definition at line 1002 of file MainWindow.cpp.
References UpdatesManager::CheckForUpdates(), and m_updateManager.
void MainWindow::on_actionEdit_Mode_toggled () [private, slot]
Definition at line 882 of file MainWindow.cpp.
References m_focusView, and m_graphicView.
void MainWindow::on_actionOpenScriptEditor_triggered () [private, slot]
Definition at line 990 of file MainWindow.cpp.
References PluginManager::GetPhotonMapFactories(), PluginManager::GetRandomDeviateFactories(), and m_pluginManager.
void MainWindow::on_actionSunPlane_triggered () [private, slot]
Definition at line 899 of file MainWindow.cpp.
References GraphicRoot::GetNode(), Document::GetSceneKit(), getTargetOfCamera(), m_document, m_focusView, m_graphicsRoot, m_graphicView, tgf::SevereError(), tgf::TransformFromMatrix(), Point3D::x, Point3D::y, and Point3D::z.
void MainWindow::Open (QString fileName) [slot]
Opens fileName file is there is a valid tonatiuh file.
Definition at line 1684 of file MainWindow.cpp.
References Abort(), and StartOver().
void MainWindow::Open () [private, slot]
Shows a dialog to the user to open a existing tonatiuh file.
Definition at line 583 of file MainWindow.cpp.
References OkToContinue(), and StartOver().
Referenced by SetupTriggers().
void MainWindow::OpenRecentFile () [private, slot]
Opens selected tonatiuh file from the recent file menu.
Definition at line 605 of file MainWindow.cpp.
References OkToContinue(), and StartOver().
Referenced by SetupActions().
bool MainWindow::Paste (QModelIndex nodeIndex, tgc::PasteType type) [private]
Creates a new type paste command. The clipboard node is inserted as nodeIndex node child.
Returns true if the node was successfully pasted, otherwise returns false.
Definition at line 2781 of file MainWindow.cpp.
References InstanceNode::GetNode(), InstanceNode::GetParent(), m_coinNode_Buffer, m_commandStack, m_document, m_sceneModel, m_selectionModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
void MainWindow::Paste (QString nodeURL, QString pasteType = QString("Shared")) [slot]
Inserts a new node as a nodeURL node child. The new node is a copy to node saved into the clipboard. The pasteType take "Shared" or "Copied" values.
Definition at line 1710 of file MainWindow.cpp.
References Abort(), tgc::Copied, SceneModel::IndexFromNodeUrl(), m_coinNode_Buffer, m_sceneModel, and tgc::Shared.
Referenced by PasteCopy(), and PasteLink().
void MainWindow::PasteCopy () [slot]
Inserts a new node as a current node child. The new node is a copy to node saved into the clipboard.
Definition at line 1736 of file MainWindow.cpp.
References Abort(), tgc::Copied, m_selectionModel, and Paste().
Referenced by SetupTriggers().
void MainWindow::PasteLink () [slot]
Inserts a new node as a current node child. The new node is a link to node saved into the clipboard.
Definition at line 1749 of file MainWindow.cpp.
References Abort(), m_selectionModel, Paste(), and tgc::Shared.
Referenced by SetupTriggers().
QDir MainWindow::PluginDirectory () [private]
Returns the directory of where the plugins are saved.
Definition at line 2812 of file MainWindow.cpp.
Referenced by SetupPluginsManager().
void MainWindow::ReadSettings () [private]
Restores application settings.
Definition at line 2826 of file MainWindow.cpp.
References m_recentFiles, and UpdateRecentFileActions().
Referenced by MainWindow().
bool MainWindow::ReadyForRaytracing (InstanceNode *& rootSeparatorInstance, InstanceNode *& lightInstance, SoTransform *& lightTransform, TSunShape *& sunShape, TLightShape *& raycastingShape, TTransmissivity *& transmissivity) [private]
Checks whether a ray tracing can be started with the current light and model.
Definition at line 2847 of file MainWindow.cpp.
References InstanceNode::children, InstanceNode::GetParent(), PluginManager::GetPhotonMapFactories(), PluginManager::GetRandomDeviateFactories(), Document::GetSceneKit(), m_document, m_increasePhotonMap, m_photonMap, m_pluginManager, m_rand, m_sceneModel, m_selectedPhotonMap, m_selectedRandomDeviate, m_tracedRays, and SceneModel::NodeFromIndex().
Referenced by Run().
void MainWindow::Redo () [private, slot]
Applies las reverted command action changes to Tonatiuh.
Definition at line 622 of file MainWindow.cpp.
References m_commandStack, m_sceneModel, and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
void MainWindow::ResetAnalyzerValues () [slot]
Definition at line 1868 of file MainWindow.cpp.
References m_sceneModel, and SceneModel::ResetAnalyzeValues().
Referenced by SetupTriggers().
void MainWindow::Run () [slot]
Runs ray tracer to defined model and paramenters.
Definition at line 1762 of file MainWindow.cpp.
References Abort(), TLightKit::ComputeLightSourceArea(), trf::ComputeSceneTreeMap(), trf::CreatePhotonMap(), InstanceNode::GetNode(), m_heightDivisions, m_photonMap, m_rand, m_raysPerIteration, m_sceneModel, m_tracedRays, m_widthDivisions, SceneModel::PrepareAnalyze(), ReadyForRaytracing(), ShowRaysIn3DView(), tgf::TransformFromSoTransform(), and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
bool MainWindow::Save () [private, slot]
Returns true if the tonatiuh model is correctly saved in the current file. Otherwise, returns false.
If a current file is not defined, it calls to SaveAs funtios.
See also:
SaveAs, SaveFile.
Definition at line 634 of file MainWindow.cpp.
References m_currentFile, SaveAs(), and SaveFile().
Referenced by OkToContinue(), and SetupTriggers().
bool MainWindow::SaveAs () [private, slot]
Returns true if the tonatiuh model is correctly saved. Otherwise, returns false. A file dialog is created to select a file.
See also:
Save, SaveFile.
Definition at line 645 of file MainWindow.cpp.
References SaveFile().
Referenced by Save(), and SetupTriggers().
void MainWindow::SaveAs (QString fileName) [slot]
Saves current tonatiuh model into fileName file.
Definition at line 1850 of file MainWindow.cpp.
References Abort(), and SaveFile().
bool MainWindow::SaveComponent () [private, slot]
Saves selected node subtree as a component in a file. A dialog is opened to select a file name and its location.
Definition at line 670 of file MainWindow.cpp.
References InstanceNode::GetNode(), m_sceneModel, m_selectionModel, and SceneModel::NodeFromIndex().
Referenced by SetupTriggers().
bool MainWindow::SaveFile (const QString & fileName) [private]
Returns true if the tonatiuh model is correctly saved into the the given fileName. Otherwise, returns false.
See also:
Save, SaveAs.
Definition at line 2932 of file MainWindow.cpp.
References m_document, SetCurrentFile(), and Document::WriteFile().
Referenced by Save(), and SaveAs().
void MainWindow::SelectionFinish (SoSelection * selection) [private, slot]
Changes the selected elements to the nodes into selection.
Definition at line 719 of file MainWindow.cpp.
References Document::GetSceneKit(), SceneModel::IndexFromPath(), m_document, m_sceneModel, and m_selectionModel.
Referenced by SetupGraphcisRoot().
void MainWindow::SelectNode (QString nodeUrl) [slot]
Changes selected node to the node with nodeUrl. If model does not contains a node with defined url, the selection will be null.
Definition at line 1877 of file MainWindow.cpp.
References SceneModel::IndexFromNodeUrl(), m_sceneModel, and m_selectionModel.
void MainWindow::SetAimingPointAbsolute () [slot]
Sets current tracker aiming .
Definition at line 1886 of file MainWindow.cpp.
References SetAimingPointRelativity().
Referenced by SetupTriggers().
void MainWindow::SetAimingPointRelative () [slot]
Disables current tracker aiming.
Definition at line 1894 of file MainWindow.cpp.
References SetAimingPointRelativity().
Referenced by SetupTriggers().
void MainWindow::SetAimingPointRelativity (bool relative) [private]
Definition at line 1590 of file MainWindow.cpp.
References m_selectionModel.
Referenced by SetAimingPointAbsolute(), and SetAimingPointRelative().
bool MainWindow::SetAimingPointRelativity (QModelIndex nodeIndex, bool relative) [private]
* Set all subnodes as relative or absolute.
If nodeURL is not a valid node url, nothing is done.
Definition at line 1602 of file MainWindow.cpp.
References m_sceneModel, SceneModel::NodeFromIndex(), and InstanceNode::SetAimingPointRelativity().
void MainWindow::SetCurrentFile (const QString & fileName) [private]
Sets fileName files as current file.
Definition at line 2948 of file MainWindow.cpp.
References m_currentFile, m_document, m_recentFiles, Document::SetDocumentModified(), StrippedName(), and UpdateRecentFileActions().
Referenced by SaveFile(), and StartOver().
void MainWindow::SetIncreasePhtonMap (bool increase) [slot]
If increase is false, starts with a new photon map every ray tracer. Otherwise, the photon map increases.
Definition at line 1902 of file MainWindow.cpp.
References m_increasePhotonMap.
Referenced by ShowRayTracerOptionsDialog().
void MainWindow::SetNodeName (QString nodeName) [slot]
Sets nodeName as the current node name.
Definition at line 1910 of file MainWindow.cpp.
References Abort(), ChangeNodeName(), and m_selectionModel.
void MainWindow::SetParameterValue (SoNode * node, QString paramenterName, QString newValue) [private, slot]
Changes to the node defined by node the value of the parameter to value.
Definition at line 751 of file MainWindow.cpp.
References m_commandStack, m_document, m_sceneModel, Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
Referenced by SetupParametersView(), and SetValue().
void MainWindow::SetPhotonMapType (QString typeName) [slot]
Sets the photon map type, typeName, for ray tracing.
Definition at line 1930 of file MainWindow.cpp.
References Abort(), PluginManager::GetPhotonMapFactories(), m_pluginManager, and m_selectedPhotonMap.
Referenced by ShowRayTracerOptionsDialog().
void MainWindow::SetRandomDeviateType (QString typeName) [slot]
Sets the random number generator type, typeName, for ray tracing.
Definition at line 1951 of file MainWindow.cpp.
References Abort(), PluginManager::GetRandomDeviateFactories(), m_pluginManager, m_rand, and m_selectedRandomDeviate.
Referenced by ShowRayTracerOptionsDialog().
void MainWindow::SetRayCastingGrid (int widthDivisions, int heightDivisions) [slot]
Sets the ray casting surface grid elemets to widthDivisions x heightDivisions.
Definition at line 1979 of file MainWindow.cpp.
References m_heightDivisions, and m_widthDivisions.
Referenced by ShowRayTracerOptionsDialog().
void MainWindow::SetRaysDrawingOptions (double raysFaction, bool drawPhotons) [slot]
Sets the parameters to represent the ray tracer results. Tonatiuh draws the raysFaction faction of traced rays. If drawPhotons is true all photons are represented.
Definition at line 1990 of file MainWindow.cpp.
References m_drawPhotons, and m_fraction.
Referenced by ShowRayTracerOptionsDialog().
void MainWindow::SetRaysPerIteration (unsigned int rays) [slot]
Sets rays as the number of rays to trace for each run action.
Definition at line 1999 of file MainWindow.cpp.
References m_raysPerIteration.
Referenced by ShowRayTracerOptionsDialog().
void MainWindow::SetSunPositionCalculatorEnabled (int enabled) [private, slot]
This property holds whether the SunPositionCalculator action is enabled. If the action is disabled, it does not disappear from menu, but it is displayed in a way which indicates that they are unavailable.
Definition at line 765 of file MainWindow.cpp.
Referenced by SetupModels(), and StartOver().
void MainWindow::SetSunshape (QString sunshapeType) [slot]
Set selected sunshape, sunshapeType, to the sun.
Definition at line 2007 of file MainWindow.cpp.
References Abort(), Document::GetSceneKit(), PluginManager::GetSunShapeFactories(), m_commandStack, m_document, m_pluginManager, m_sceneModel, Document::SetDocumentModified(), and SceneModel::UpdateSceneModel().
void MainWindow::SetSunshapeParameter (QString parameter, QString value) [slot]
Set the value for the sunshape parameter parameter.
Definition at line 2053 of file MainWindow.cpp.
References Abort(), Document::GetSceneKit(), m_commandStack, m_document, m_sceneModel, and Document::SetDocumentModified().
void MainWindow::SetTransmissivity (QString transmissivityType) [slot]
Set selected transmissivity, transmissivityType, to the scene.
Definition at line 2078 of file MainWindow.cpp.
References Abort(), Document::GetSceneKit(), PluginManager::GetTransmissivityFactories(), m_commandStack, m_document, m_pluginManager, and Document::SetDocumentModified().
void MainWindow::SetTransmissivityParameter (QString parameter, QString value) [slot]
Set the value for the transmissivity parameter parameter.
Definition at line 2123 of file MainWindow.cpp.
References Abort(), Document::GetSceneKit(), m_commandStack, m_document, m_sceneModel, and Document::SetDocumentModified().
void MainWindow::SetupActions () [private]
Creates actions form recent files.
Definition at line 2968 of file MainWindow.cpp.
References m_maxRecentFiles, m_recentFileActions, and OpenRecentFile().
Referenced by MainWindow().
void MainWindow::SetupActionsInsertMaterial () [private]
Definition at line 2980 of file MainWindow.cpp.
References CreateMaterial(), CreateMaterialsTooBar(), PluginManager::GetMaterialFactories(), m_materialsToolBar, m_pluginManager, TMaterialFactory::TMaterialIcon(), and TMaterialFactory::TMaterialName().
Referenced by SetupPluginsManager().
void MainWindow::SetupActionsInsertShape () [private]
Creates an action for the /a pTShapeFactory and adds to shape insert menu and toolbar.
Definition at line 3016 of file MainWindow.cpp.
References CreateShape(), PluginManager::GetShapeFactories(), m_pluginManager, m_shapeToolBar, tgf::SevereError(), TShapeFactory::TShapeIcon(), and TShapeFactory::TShapeName().
Referenced by SetupPluginsManager().
void MainWindow::SetupActionsInsertTracker () [private]
Definition at line 3052 of file MainWindow.cpp.
References CreateTracker(), CreateTrackerTooBar(), PluginManager::GetTrackerFactories(), m_pluginManager, m_trackersToolBar, TTrackerFactory::TTrackerIcon(), and TTrackerFactory::TTrackerName().
Referenced by SetupPluginsManager().
void MainWindow::SetupCommandView () [private]
Creates a view for visualize user done last actions.
Definition at line 3094 of file MainWindow.cpp.
References m_commandStack, and m_commandView.
Referenced by SetupViews().
void MainWindow::SetupDocument () [private]
Initializes tonatiuh document object.
Definition at line 3158 of file MainWindow.cpp.
References m_document, ShowWarning(), and tgf::Warning().
Referenced by MainWindow().
void MainWindow::SetupGraphcisRoot () [private]
Defines 3D view background.
Definition at line 3169 of file MainWindow.cpp.
References GraphicRoot::AddGrid(), GraphicRoot::AddModel(), ChangeSelection(), CreateGrid(), Document::GetSceneKit(), m_document, m_graphicsRoot, m_gridXElements, m_gridXSpacing, m_gridZElements, m_gridZSpacing, SelectionFinish(), and tgf::SevereError().
Referenced by MainWindow().
void MainWindow::SetupGraphicView () [private]
Initializates tonatiuh graphic view.
Definition at line 3196 of file MainWindow.cpp.
References m_focusView, m_graphicsRoot, m_graphicView, m_sceneModel, m_selectionModel, on_action_X_Y_Plane_triggered(), on_action_X_Z_Plane_triggered(), on_action_Y_Z_Plane_triggered(), and tgf::SevereError().
Referenced by SetupViews().
void MainWindow::SetupMenus () [private]
Creates a menu for last used files
Definition at line 3307 of file MainWindow.cpp.
References m_maxRecentFiles, and m_recentFileActions.
Referenced by MainWindow().
void MainWindow::SetupModels () [private]
Initializes Tonatiuh models.
Definition at line 3316 of file MainWindow.cpp.
References GraphicRoot::GetNode(), Document::GetSceneKit(), m_document, m_graphicsRoot, m_sceneModel, m_selectionModel, SceneModel::SetCoinRoot(), SceneModel::SetCoinScene(), and SetSunPositionCalculatorEnabled().
Referenced by MainWindow().
void MainWindow::SetupParametersView () [private]
Initializes the tonatiuh objects parameters view.
Definition at line 3331 of file MainWindow.cpp.
References ChangeSelection(), m_selectionModel, and SetParameterValue().
Referenced by SetupViews().
void MainWindow::SetupPluginsManager () [private]
Initializes plugin manager and load available plugins.
Definition at line 3343 of file MainWindow.cpp.
References PluginManager::LoadAvailablePlugins(), m_pluginManager, PluginDirectory(), SetupActionsInsertMaterial(), SetupActionsInsertShape(), and SetupActionsInsertTracker().
Referenced by MainWindow().
void MainWindow::SetupTreeView () [private]
Initializates Tonatiuh objectes tree view.
Definition at line 3356 of file MainWindow.cpp.
References ChangeNodeName(), SceneModel::IndexFromNodeUrl(), ItemDragAndDrop(), ItemDragAndDropCopy(), m_sceneModel, m_selectionModel, and ShowMenu().
Referenced by SetupViews().
void MainWindow::SetupTriggers () [private]
Defines slots function for main window signals.
Definition at line 3377 of file MainWindow.cpp.
References CalculateSunPosition(), ChangeGridSettings(), Copy(), CreateAnalyzerNode(), CreateGroupNode(), CreateSurfaceNode(), Cut(), DefineSunLight(), DefineTransmissivity(), Delete(), DisconnectAllTrackers(), DisplayRays(), ExportPhotonMap(), InsertUserDefinedComponent(), New(), Open(), PasteCopy(), PasteLink(), Redo(), ResetAnalyzerValues(), Run(), Save(), SaveAs(), SaveComponent(), SetAimingPointAbsolute(), SetAimingPointRelative(), ShowBackground(), ShowCommandView(), ShowGrid(), ShowRayTracerOptionsDialog(), and Undo().
Referenced by MainWindow().
void MainWindow::SetupUpdateManager () [private]
Initializates tonatiuh update manager.
Definition at line 3428 of file MainWindow.cpp.
References m_updateManager.
Referenced by MainWindow().
void MainWindow::SetupViews () [private]
Starts MainWindow views.
Definition at line 3436 of file MainWindow.cpp.
References SetupCommandView(), SetupGraphicView(), SetupParametersView(), and SetupTreeView().
Referenced by MainWindow().
void MainWindow::SetValue (QString nodeUrl, QString parameter, QString value) [slot]
Sets to the parameter of the node nodeUrl the value defined at value.
Definition at line 2141 of file MainWindow.cpp.
References Abort(), InstanceNode::GetNode(), TSeparatorKit::getPart(), SceneModel::IndexFromNodeUrl(), m_sceneModel, SceneModel::NodeFromIndex(), and SetParameterValue().
void MainWindow::ShowBackground () [private, slot]
Action slot to show/hide viewer background.
Definition at line 3085 of file MainWindow.cpp.
References m_graphicsRoot, and GraphicRoot::ShowBackground().
Referenced by SetupTriggers().
void MainWindow::ShowCommandView () [private, slot]
Shows a windows with the applied commands. The most recently executed command is always selected. When a different command is selected the model returns to the state after selected command was applied.
Definition at line 775 of file MainWindow.cpp.
References m_commandView.
Referenced by SetupTriggers().
void MainWindow::ShowGrid () [private, slot]
Action slot to show/hide a grid with the scene dimensions.
Definition at line 3109 of file MainWindow.cpp.
References m_graphicsRoot, and GraphicRoot::ShowGrid().
Referenced by SetupTriggers().
void MainWindow::ShowMenu (const QModelIndex & index) [private, slot]
Shows selected node right menu.
Definition at line 783 of file MainWindow.cpp.
References InstanceNode::GetNode(), InstanceNode::GetParent(), TSeparatorKit::getPart(), m_sceneModel, m_selectionModel, SceneModel::NodeFromIndex(), SoManip_to_SoTransform(), SoTransform_to_SoCenterballManip(), SoTransform_to_SoHandleBoxManip(), SoTransform_to_SoJackManip(), SoTransform_to_SoTabBoxManip(), SoTransform_to_SoTrackballManip(), SoTransform_to_SoTransformBoxManip(), and SoTransform_to_SoTransformerManip().
Referenced by SetupTreeView().
void MainWindow::ShowRaysIn3DView () [private]
Shows the rays and photons stored at the photon map in the 3D view.
Definition at line 3447 of file MainWindow.cpp.
References GraphicRoot::AddRays(), trf::DrawPhotonMapPoints(), trf::DrawPhotonMapRays(), m_drawPhotons, m_fraction, m_graphicsRoot, m_photonMap, and m_tracedRays.
Referenced by Run().
void MainWindow::ShowRayTracerOptionsDialog () [private, slot]
Shows a dialog with ray tracer options and modifies the ray tracer parameters if changes are done.
Definition at line 839 of file MainWindow.cpp.
References RayTraceDialog::DrawPhotons(), RayTraceDialog::GetHeightDivisions(), RayTraceDialog::GetNumRays(), PluginManager::GetPhotonMapFactories(), RayTraceDialog::GetPhotonMapFactoryIndex(), PluginManager::GetRandomDeviateFactories(), RayTraceDialog::GetRandomDeviateFactoryIndex(), RayTraceDialog::GetRaysFactionToDraw(), RayTraceDialog::GetWidthDivisions(), RayTraceDialog::IncreasePhotonMap(), m_drawPhotons, m_fraction, m_heightDivisions, m_increasePhotonMap, m_pluginManager, m_raysPerIteration, m_selectedPhotonMap, m_selectedRandomDeviate, m_widthDivisions, SetIncreasePhtonMap(), SetPhotonMapType(), SetRandomDeviateType(), SetRayCastingGrid(), SetRaysDrawingOptions(), and SetRaysPerIteration().
Referenced by SetupTriggers().
void MainWindow::ShowWarning (QString message) [private, slot]
Definition at line 859 of file MainWindow.cpp.
Referenced by SetupDocument().
void MainWindow::SoManip_to_SoTransform () [private, slot]
Definition at line 2370 of file MainWindow.cpp.
References ChangeSelection(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), and Document::SetDocumentModified().
Referenced by ShowMenu().
void MainWindow::SoTransform_to_SoCenterballManip () [private, slot]
Definition at line 2185 of file MainWindow.cpp.
References ChangeSelection(), finishManipulator(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and startManipulator().
Referenced by ShowMenu().
void MainWindow::SoTransform_to_SoHandleBoxManip () [private, slot]
Definition at line 2237 of file MainWindow.cpp.
References ChangeSelection(), finishManipulator(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and startManipulator().
Referenced by ShowMenu().
void MainWindow::SoTransform_to_SoJackManip () [private, slot]
Definition at line 2211 of file MainWindow.cpp.
References ChangeSelection(), finishManipulator(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and startManipulator().
Referenced by ShowMenu().
void MainWindow::SoTransform_to_SoTabBoxManip () [private, slot]
Definition at line 2263 of file MainWindow.cpp.
References ChangeSelection(), finishManipulator(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and startManipulator().
Referenced by ShowMenu().
void MainWindow::SoTransform_to_SoTrackballManip () [private, slot]
Definition at line 2289 of file MainWindow.cpp.
References ChangeSelection(), finishManipulator(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and startManipulator().
Referenced by ShowMenu().
void MainWindow::SoTransform_to_SoTransformBoxManip () [private, slot]
Definition at line 2315 of file MainWindow.cpp.
References ChangeSelection(), finishManipulator(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and startManipulator().
Referenced by ShowMenu().
void MainWindow::SoTransform_to_SoTransformerManip () [private, slot]
Definition at line 2342 of file MainWindow.cpp.
References ChangeSelection(), finishManipulator(), InstanceNode::GetNode(), m_document, m_sceneModel, SceneModel::NodeFromIndex(), Document::SetDocumentModified(), and startManipulator().
Referenced by ShowMenu().
void MainWindow::StartManipulation (SoDragger * dragger)
Starts manipulating current selected node with dragger.
Definition at line 251 of file MainWindow.cpp.
References GraphicRoot::GetNode(), SceneModel::IndexFromPath(), m_graphicsRoot, m_manipulators_Buffer, m_sceneModel, m_selectionModel, and tgf::SevereError().
Referenced by startManipulator().
bool MainWindow::StartOver (const QString & fileName) [private]
Returns to the start origin state and starts with a new model defined in fileName. If the file name is not defined, it starts with an empty scene.
Definition at line 3481 of file MainWindow.cpp.
References ChangeModelScene(), InstanceNode::children, SceneModel::Clear(), SceneModel::DisplayAnalyzeResults(), InstanceNode::GetNodeURL(), SceneModel::IndexFromNodeUrl(), m_commandStack, m_document, m_graphicsRoot, m_sceneModel, m_selectionModel, Document::New(), SceneModel::NodeFromIndex(), Document::ReadFile(), GraphicRoot::RemoveModel(), GraphicRoot::RemoveRays(), SetCurrentFile(), and SetSunPositionCalculatorEnabled().
Referenced by MainWindow(), New(), Open(), and OpenRecentFile().
QString MainWindow::StrippedName (const QString & fullFileName) [private]
Returns the fullFileName files name, without path.
Definition at line 3544 of file MainWindow.cpp.
Referenced by SetCurrentFile(), and UpdateRecentFileActions().
void MainWindow::Undo () [private, slot]
Reverts a change to Tonatiuh model. The model is returne to the previous state before the command is applied.
Definition at line 867 of file MainWindow.cpp.
References m_commandStack, m_sceneModel, and SceneModel::UpdateSceneModel().
Referenced by SetupTriggers().
void MainWindow::UpdateRecentFileActions () [private]
Updates the recently opened files actions list.
Definition at line 3552 of file MainWindow.cpp.
References m_maxRecentFiles, m_recentFileActions, m_recentFiles, and StrippedName().
Referenced by ReadSettings(), and SetCurrentFile().
void MainWindow::WriteSettings () [private]
Saves application settings.
Definition at line 3578 of file MainWindow.cpp.
References m_recentFiles.
Referenced by closeEvent().
Member Data Documentation
SoNode* MainWindow::m_coinNode_Buffer [private]
Definition at line 274 of file MainWindow.h.
Referenced by Copy(), Cut(), ItemDragAndDrop(), ItemDragAndDropCopy(), and Paste().
QUndoStack* MainWindow::m_commandStack [private]
Definition at line 245 of file MainWindow.h.
Referenced by ChangeNodeName(), ChangeSunPosition(), Copy(), CreateAnalyzerNode(), CreateGroupNode(), CreateMaterial(), CreateShape(), CreateSurfaceNode(), CreateTracker(), Cut(), DefineSunLight(), DefineTransmissivity(), Delete(), FinishManipulation(), InsertFileComponent(), ItemDragAndDrop(), ItemDragAndDropCopy(), Paste(), Redo(), SetParameterValue(), SetSunshape(), SetSunshapeParameter(), SetTransmissivity(), SetTransmissivityParameter(), SetupCommandView(), StartOver(), Undo(), and ~MainWindow().
QUndoView* MainWindow::m_commandView [private]
Definition at line 246 of file MainWindow.h.
Referenced by SetupCommandView(), ShowCommandView(), and ~MainWindow().
QString MainWindow::m_currentFile [private]
Definition at line 247 of file MainWindow.h.
Referenced by Save(), and SetCurrentFile().
Document* MainWindow::m_document [private]
Definition at line 248 of file MainWindow.h.
Referenced by CalculateSunPosition(), ChangeModelScene(), ChangeNodeName(), ChangeSunPosition(), Copy(), CreateAnalyzerNode(), CreateGroupNode(), CreateMaterial(), CreateShape(), CreateSurfaceNode(), CreateTracker(), Cut(), DefineSunLight(), DefineTransmissivity(), Delete(), ExportAllPhotonMap(), ExportPhotonMap(), FinishManipulation(), InsertFileComponent(), ItemDragAndDrop(), ItemDragAndDropCopy(), OkToContinue(), on_actionSunPlane_triggered(), Paste(), ReadyForRaytracing(), SaveFile(), SelectionFinish(), SetCurrentFile(), SetParameterValue(), SetSunshape(), SetSunshapeParameter(), SetTransmissivity(), SetTransmissivityParameter(), SetupDocument(), SetupGraphcisRoot(), SetupModels(), SoManip_to_SoTransform(), SoTransform_to_SoCenterballManip(), SoTransform_to_SoHandleBoxManip(), SoTransform_to_SoJackManip(), SoTransform_to_SoTabBoxManip(), SoTransform_to_SoTrackballManip(), SoTransform_to_SoTransformBoxManip(), SoTransform_to_SoTransformerManip(), StartOver(), and ~MainWindow().
bool MainWindow::m_drawPhotons [private]
Definition at line 279 of file MainWindow.h.
Referenced by SetRaysDrawingOptions(), ShowRaysIn3DView(), and ShowRayTracerOptionsDialog().
int MainWindow::m_focusView [private]
Definition at line 285 of file MainWindow.h.
Referenced by mousePressEvent(), on_action_X_Y_Plane_triggered(), on_action_X_Z_Plane_triggered(), on_action_Y_Z_Plane_triggered(), on_actionEdit_Mode_toggled(), on_actionSunPlane_triggered(), and SetupGraphicView().
double MainWindow::m_fraction [private]
Definition at line 278 of file MainWindow.h.
Referenced by SetRaysDrawingOptions(), ShowRaysIn3DView(), and ShowRayTracerOptionsDialog().
GraphicRoot* MainWindow::m_graphicsRoot [private]
Definition at line 273 of file MainWindow.h.
Referenced by ChangeGridSettings(), ChangeModelScene(), DisplayRays(), on_actionSunPlane_triggered(), SetupGraphcisRoot(), SetupGraphicView(), SetupModels(), ShowBackground(), ShowGrid(), ShowRaysIn3DView(), StartManipulation(), and StartOver().
std::vector<GraphicView*> MainWindow::m_graphicView [private]
Definition at line 284 of file MainWindow.h.
Referenced by on_action_X_Y_Plane_triggered(), on_action_X_Z_Plane_triggered(), on_action_Y_Z_Plane_triggered(), on_actionAxis_toggled(), on_actionEdit_Mode_toggled(), on_actionSunPlane_triggered(), and SetupGraphicView().
int MainWindow::m_gridXElements [private]
Definition at line 280 of file MainWindow.h.
Referenced by ChangeGridSettings(), and SetupGraphcisRoot().
double MainWindow::m_gridXSpacing [private]
Definition at line 282 of file MainWindow.h.
Referenced by ChangeGridSettings(), and SetupGraphcisRoot().
int MainWindow::m_gridZElements [private]
Definition at line 281 of file MainWindow.h.
Referenced by ChangeGridSettings(), and SetupGraphcisRoot().
double MainWindow::m_gridZSpacing [private]
Definition at line 283 of file MainWindow.h.
Referenced by ChangeGridSettings(), and SetupGraphcisRoot().
int MainWindow::m_heightDivisions [private]
Definition at line 286 of file MainWindow.h.
Referenced by Run(), SetRayCastingGrid(), and ShowRayTracerOptionsDialog().
bool MainWindow::m_increasePhotonMap [private]
Definition at line 267 of file MainWindow.h.
Referenced by ReadyForRaytracing(), SetIncreasePhtonMap(), and ShowRayTracerOptionsDialog().
QString MainWindow::m_lastExportFileName [private]
Definition at line 269 of file MainWindow.h.
Referenced by ExportAllPhotonMap(), and ExportPhotonMap().
bool MainWindow::m_lastExportInGlobal [private]
Definition at line 271 of file MainWindow.h.
Referenced by ExportPhotonMap().
QString MainWindow::m_lastExportSurfaceUrl [private]
Definition at line 270 of file MainWindow.h.
Referenced by ExportPhotonMap().
QStringList* MainWindow::m_manipulators_Buffer [private]
Definition at line 275 of file MainWindow.h.
Referenced by StartManipulation().
QToolBar* MainWindow::m_materialsToolBar [private]
Definition at line 251 of file MainWindow.h.
Referenced by SetupActionsInsertMaterial().
TPhotonMap* MainWindow::m_photonMap [private]
Definition at line 265 of file MainWindow.h.
Referenced by ExportAllPhotonMap(), ExportPhotonMap(), ReadyForRaytracing(), Run(), ShowRaysIn3DView(), and ~MainWindow().
QToolBar* MainWindow::m_photonMapToolBar [private]
Definition at line 252 of file MainWindow.h.
PluginManager* MainWindow::m_pluginManager [private]
Definition at line 256 of file MainWindow.h.
Referenced by CreateMaterial(), CreateShape(), CreateTracker(), DefineSunLight(), DefineTransmissivity(), on_actionOpenScriptEditor_triggered(), ReadyForRaytracing(), SetPhotonMapType(), SetRandomDeviateType(), SetSunshape(), SetTransmissivity(), SetupActionsInsertMaterial(), SetupActionsInsertShape(), SetupActionsInsertTracker(), SetupPluginsManager(), ShowRayTracerOptionsDialog(), and ~MainWindow().
RandomDeviate* MainWindow::m_rand [private]
Definition at line 262 of file MainWindow.h.
Referenced by ReadyForRaytracing(), Run(), SetRandomDeviateType(), and ~MainWindow().
unsigned long MainWindow::m_raysPerIteration [private]
Definition at line 277 of file MainWindow.h.
Referenced by Run(), SetRaysPerIteration(), and ShowRayTracerOptionsDialog().
QAction** MainWindow::m_recentFileActions [private]
Definition at line 250 of file MainWindow.h.
Referenced by SetupActions(), SetupMenus(), UpdateRecentFileActions(), and ~MainWindow().
QStringList MainWindow::m_recentFiles [private]
Definition at line 249 of file MainWindow.h.
Referenced by ReadSettings(), SetCurrentFile(), UpdateRecentFileActions(), and WriteSettings().
SceneModel* MainWindow::m_sceneModel [private]
Definition at line 259 of file MainWindow.h.
Referenced by ChangeGridSettings(), ChangeModelScene(), ChangeNodeName(), ChangeSelection(), ChangeSunPosition(), Copy(), CreateAnalyzerNode(), CreateGroupNode(), CreateMaterial(), CreateShape(), CreateSurfaceNode(), CreateTracker(), Cut(), DefineSunLight(), Delete(), DisconnectAllTrackers(), ExportPhotonMap(), FinishManipulation(), InsertFileComponent(), InsertUserDefinedComponent(), ItemDragAndDrop(), ItemDragAndDropCopy(), Paste(), ReadyForRaytracing(), Redo(), ResetAnalyzerValues(), Run(), SaveComponent(), SelectionFinish(), SelectNode(), SetAimingPointRelativity(), SetParameterValue(), SetSunshape(), SetSunshapeParameter(), SetTransmissivityParameter(), SetupGraphicView(), SetupModels(), SetupTreeView(), SetValue(), ShowMenu(), SoManip_to_SoTransform(), SoTransform_to_SoCenterballManip(), SoTransform_to_SoHandleBoxManip(), SoTransform_to_SoJackManip(), SoTransform_to_SoTabBoxManip(), SoTransform_to_SoTrackballManip(), SoTransform_to_SoTransformBoxManip(), SoTransform_to_SoTransformerManip(), StartManipulation(), StartOver(), Undo(), and ~MainWindow().
int MainWindow::m_selectedPhotonMap [private]
Definition at line 266 of file MainWindow.h.
Referenced by ReadyForRaytracing(), SetPhotonMapType(), and ShowRayTracerOptionsDialog().
int MainWindow::m_selectedRandomDeviate [private]
Definition at line 263 of file MainWindow.h.
Referenced by ReadyForRaytracing(), SetRandomDeviateType(), and ShowRayTracerOptionsDialog().
QItemSelectionModel* MainWindow::m_selectionModel [private]
Definition at line 260 of file MainWindow.h.
Referenced by ChangeModelScene(), Copy(), Cut(), DefineSunLight(), Delete(), Paste(), PasteCopy(), PasteLink(), SaveComponent(), SelectionFinish(), SelectNode(), SetAimingPointRelativity(), SetNodeName(), SetupGraphicView(), SetupModels(), SetupParametersView(), SetupTreeView(), ShowMenu(), StartManipulation(), and StartOver().
QToolBar* MainWindow::m_shapeToolBar [private]
Definition at line 253 of file MainWindow.h.
Referenced by SetupActionsInsertShape().
unsigned long MainWindow::m_tracedRays [private]
Definition at line 276 of file MainWindow.h.
Referenced by ExportAllPhotonMap(), ExportPhotonMap(), ReadyForRaytracing(), Run(), and ShowRaysIn3DView().
QToolBar* MainWindow::m_trackersToolBar [private]
Definition at line 254 of file MainWindow.h.
Referenced by SetupActionsInsertTracker().
UpdatesManager* MainWindow::m_updateManager [private]
Definition at line 257 of file MainWindow.h.
Referenced by on_actionCheckForUpdates_triggered(), SetupUpdateManager(), and ~MainWindow().
int MainWindow::m_widthDivisions [private]
Definition at line 287 of file MainWindow.h.
Referenced by Run(), SetRayCastingGrid(), and ShowRayTracerOptionsDialog().
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp