RayTracerNoTr Class Reference
http://tonatiuh.googlecode.com
RayTracerNoTr Class Reference
Public Types
typedef QPair< TPhotonMap
*, std::vector
< RayTracerPhoton > > result_type
Public Member Functions
RayTracerNoTr (InstanceNode *rootNode, InstanceNode *lightNode, TLightShape *lightShape, TSunShape *const lightSunShape, Transform lightToWorld, RandomDeviate &rand, QMutex *mutex, TPhotonMap *photonMap)
QPair< TPhotonMap
*, std::vector
< RayTracerPhoton > > operator() (QPair< double, QPoint > pixel)
Private Member Functions
bool NewPrimitiveRay (Ray *ray, ParallelRandomDeviate &rand, int a, int b)
Private Attributes
InstanceNode * m_rootNode
InstanceNode * m_lightNode
TLightShape * m_lightShape
const TSunShape * m_lightSunShape
Transform m_lightToWorld
RandomDeviate * m_pRand
QMutex * m_mutex
TPhotonMap * m_photonMap
Detailed Description
Definition at line 63 of file RayTracerNoTr.h.
Member Typedef Documentation
typedef QPair< TPhotonMap*, std::vector< RayTracerPhoton > > RayTracerNoTr::result_type
Definition at line 77 of file RayTracerNoTr.h.
Constructor & Destructor Documentation
RayTracerNoTr::RayTracerNoTr (InstanceNode * rootNode, InstanceNode * lightNode, TLightShape * lightShape, TSunShape *const lightSunShape, Transform lightToWorld, RandomDeviate & rand, QMutex * mutex, TPhotonMap * photonMap)
Definition at line 51 of file RayTracerNoTr.cpp.
Member Function Documentation
bool RayTracerNoTr::NewPrimitiveRay (Ray * ray, ParallelRandomDeviate & rand, int a, int b) [private]
Definition at line 73 of file RayTracerNoTr.cpp.
References TSunShape::GenerateRayDirection(), m_lightShape, m_lightSunShape, m_lightToWorld, RandomDeviate::RandomDouble(), and TLightShape::Sample().
Referenced by operator()().
QPair< TPhotonMap *, std::vector< RayTracerPhoton > > RayTracerNoTr::operator() (QPair< double, QPoint > pixel)
Definition at line 87 of file RayTracerNoTr.cpp.
References InstanceNode::Analyze(), InstanceNode::Intersect(), m_lightNode, m_mutex, m_photonMap, m_pRand, m_rootNode, Ray::maxt, NewPrimitiveRay(), and Ray::origin.
Member Data Documentation
InstanceNode* RayTracerNoTr::m_lightNode [private]
Definition at line 85 of file RayTracerNoTr.h.
Referenced by operator()().
TLightShape* RayTracerNoTr::m_lightShape [private]
Definition at line 86 of file RayTracerNoTr.h.
Referenced by NewPrimitiveRay().
const TSunShape* RayTracerNoTr::m_lightSunShape [private]
Definition at line 87 of file RayTracerNoTr.h.
Referenced by NewPrimitiveRay().
Transform RayTracerNoTr::m_lightToWorld [private]
Definition at line 88 of file RayTracerNoTr.h.
Referenced by NewPrimitiveRay().
QMutex* RayTracerNoTr::m_mutex [private]
Definition at line 90 of file RayTracerNoTr.h.
Referenced by operator()().
TPhotonMap* RayTracerNoTr::m_photonMap [private]
Definition at line 91 of file RayTracerNoTr.h.
Referenced by operator()().
RandomDeviate* RayTracerNoTr::m_pRand [private]
Definition at line 89 of file RayTracerNoTr.h.
Referenced by operator()().
InstanceNode* RayTracerNoTr::m_rootNode [private]
Definition at line 84 of file RayTracerNoTr.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
RayTracerNoTr.h
RayTracerNoTr.cpp