Tonatiuh: TTrackerForAiming Class Reference
http://tonatiuh.googlecode.com
TTrackerForAiming Class Reference
Public Types
enum AimingPointType { Absolute = 0, Relative = 1 }
Public Member Functions
virtual void SwitchAimingPointType ()=0
void SetAimingPointRelativity (bool relative)
Static Public Member Functions
static void initClass ()
static void updateTypeOfAimingPoint (void *data, SoSensor *)
Public Attributes
SoSFEnum typeOfAimingPoint
Protected Member Functions
TTrackerForAiming ()
virtual ~TTrackerForAiming ()
Private Member Functions
SO_NODEENGINE_ABSTRACT_HEADER (TTrackerForAiming)
Detailed Description
Definition at line 49 of file TTrackerForAiming.h.
Member Enumeration Documentation
enum TTrackerForAiming::AimingPointType
Enumerator:
Absolute
Relative
Definition at line 55 of file TTrackerForAiming.h.
Constructor & Destructor Documentation
TTrackerForAiming::TTrackerForAiming () [protected]
Definition at line 18 of file TTrackerForAiming.cpp.
TTrackerForAiming::~TTrackerForAiming () [protected, virtual]
Definition at line 31 of file TTrackerForAiming.cpp.
Member Function Documentation
void TTrackerForAiming::initClass () [static]
Reimplemented from TTracker.
Definition at line 11 of file TTrackerForAiming.cpp.
Referenced by main().
void TTrackerForAiming::SetAimingPointRelativity (bool relative)
Definition at line 36 of file TTrackerForAiming.cpp.
References typeOfAimingPoint.
TTrackerForAiming::SO_NODEENGINE_ABSTRACT_HEADER (TTrackerForAiming) [private]
virtual void TTrackerForAiming::SwitchAimingPointType () [pure virtual]
Referenced by updateTypeOfAimingPoint().
void TTrackerForAiming::updateTypeOfAimingPoint (void * data, SoSensor *) [static]
Definition at line 52 of file TTrackerForAiming.cpp.
References SwitchAimingPointType().
Member Data Documentation
SoSFEnum TTrackerForAiming::typeOfAimingPoint
Definition at line 60 of file TTrackerForAiming.h.
Referenced by SetAimingPointRelativity().
The documentation for this class was generated from the following files:
TTrackerForAiming.h
TTrackerForAiming.cpp