Tonatiuh: GraphicView Class Reference
http://tonatiuh.googlecode.com
GraphicView Class Reference
GraphicView class implements a 3D representation of items from a model.
Public Member Functions
GraphicView (QWidget *parent=0)
~GraphicView ()
void SetSceneGraph (GraphicRoot *sceneGraphRoot)
SbViewportRegion GetViewportRegion () const
SoCamera * GetCamera () const
virtual QModelIndex indexAt (const QPoint &point) const
virtual void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
virtual QRect visualRect (const QModelIndex &index) const
void ViewDecoration (bool view)
void ViewCoordinateSystem (bool view)
Protected Slots
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
void rowsInserted (const QModelIndex &parent, int start, int end)
void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Protected Member Functions
virtual void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags flags)
virtual int horizontalOffset () const
virtual int verticalOffset () const
virtual bool isIndexHidden (const QModelIndex &index) const
virtual QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
virtual QRegion visualRegionForSelection (const QItemSelection &selection) const
Private Attributes
GraphicRoot * m_sceneGraphRoot
SoQtExaminerViewer * m_myRenderArea
Detailed Description
GraphicView class implements a 3D representation of items from a model.
GraphicView provides a model/view implementation of a 3D view. Implements the interfaces defined by the QAbstractItemView class to allow it to display data provided by models derived from the QAbstractItemModel class.
Definition at line 57 of file GraphicView.h.
Constructor & Destructor Documentation
GraphicView::GraphicView (QWidget * parent = 0)
Creates a new GraphicView with a parerent for the model data 3D representation.
Use setModel() to set the model.
Definition at line 55 of file GraphicView.cpp.
GraphicView::~GraphicView ()
Definition at line 63 of file GraphicView.cpp.
References m_myRenderArea.
Member Function Documentation
void GraphicView::currentChanged (const QModelIndex & current, const QModelIndex & previous) [protected, slot]
Definition at line 159 of file GraphicView.cpp.
References GraphicRoot::DeselectAll(), m_sceneGraphRoot, and GraphicRoot::Select().
void GraphicView::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) [protected, slot]
Definition at line 114 of file GraphicView.cpp.
SoCamera * GraphicView::GetCamera () const
Definition at line 85 of file GraphicView.cpp.
References m_myRenderArea.
SbViewportRegion GraphicView::GetViewportRegion () const
Definition at line 80 of file GraphicView.cpp.
References m_myRenderArea.
int GraphicView::horizontalOffset () const [protected, virtual]
Definition at line 134 of file GraphicView.cpp.
QModelIndex GraphicView::indexAt (const QPoint & point) const [virtual]
Definition at line 90 of file GraphicView.cpp.
bool GraphicView::isIndexHidden (const QModelIndex & index) const [protected, virtual]
Definition at line 144 of file GraphicView.cpp.
QModelIndex GraphicView::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) [protected, virtual]
Definition at line 149 of file GraphicView.cpp.
void GraphicView::rowsAboutToBeRemoved (const QModelIndex & parent, int start, int end) [protected, slot]
Definition at line 124 of file GraphicView.cpp.
void GraphicView::rowsInserted (const QModelIndex & parent, int start, int end) [protected, slot]
Definition at line 119 of file GraphicView.cpp.
void GraphicView::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) [virtual]
Definition at line 95 of file GraphicView.cpp.
void GraphicView::SetSceneGraph (GraphicRoot * sceneGraphRoot)
Definition at line 68 of file GraphicView.cpp.
References GraphicRoot::GetNode(), m_myRenderArea, m_sceneGraphRoot, and ViewCoordinateSystem().
void GraphicView::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags flags) [protected, virtual]
Definition at line 129 of file GraphicView.cpp.
int GraphicView::verticalOffset () const [protected, virtual]
Definition at line 139 of file GraphicView.cpp.
void GraphicView::ViewCoordinateSystem (bool view)
Definition at line 104 of file GraphicView.cpp.
References m_myRenderArea.
Referenced by SetSceneGraph().
void GraphicView::ViewDecoration (bool view)
Definition at line 109 of file GraphicView.cpp.
References m_myRenderArea.
QRect GraphicView::visualRect (const QModelIndex & index) const [virtual]
Definition at line 99 of file GraphicView.cpp.
QRegion GraphicView::visualRegionForSelection (const QItemSelection & selection) const [protected, virtual]
Definition at line 154 of file GraphicView.cpp.
Member Data Documentation
SoQtExaminerViewer* GraphicView::m_myRenderArea [private]
Definition at line 92 of file GraphicView.h.
Referenced by GetCamera(), GetViewportRegion(), SetSceneGraph(), ViewCoordinateSystem(), ViewDecoration(), and ~GraphicView().
GraphicRoot* GraphicView::m_sceneGraphRoot [private]
Definition at line 91 of file GraphicView.h.
Referenced by currentChanged(), and SetSceneGraph().
The documentation for this class was generated from the following files:
GraphicView.h
GraphicView.cpp