Tonatiuh: CelestialWidget Class Reference
http://tonatiuh.googlecode.com
CelestialWidget Class Reference
Public Slots
void CoordinatesChanged (cSunCoordinates coordinates)
Public Member Functions
CelestialWidget (QWidget *parent=0)
~CelestialWidget ()
double getSphereRadio ()
double getDeclination ()
double getRightAscension ()
Private Member Functions
SoSeparator * CelestialEquator () const
SoSeparator * Declination ()
SoSeparator * Ecliptic () const
SoSeparator * Ejes () const
SoSeparator * Points () const
SoSeparator * RightAscension ()
SoSeparator * Sphere () const
SoSeparator * Star ()
Private Attributes
QLabel * m_rightValue
QLabel * m_declinationValue
SoSeparator * m_rootNode
const double sphereRadio
double m_declination
double m_rightAscension
Detailed Description
Definition at line 50 of file CelestialWidget.h.
Constructor & Destructor Documentation
CelestialWidget::CelestialWidget (QWidget * parent = 0)
Definition at line 64 of file CelestialWidget.cpp.
References CelestialEquator(), Declination(), Ecliptic(), Ejes(), m_declination, m_declinationValue, m_rightAscension, m_rightValue, m_rootNode, Points(), RightAscension(), Sphere(), and Star().
CelestialWidget::~CelestialWidget ()
Definition at line 113 of file CelestialWidget.cpp.
Member Function Documentation
SoSeparator * CelestialWidget::CelestialEquator () const [private]
Definition at line 137 of file CelestialWidget.cpp.
References tgc::Pi, and sphereRadio.
Referenced by CelestialWidget().
void CelestialWidget::CoordinatesChanged (cSunCoordinates coordinates) [slot]
Definition at line 117 of file CelestialWidget.cpp.
References cSunCoordinates::dDeclination, Declination(), cSunCoordinates::dRightAscension, m_declination, m_declinationValue, m_rightAscension, m_rightValue, m_rootNode, RightAscension(), and Star().
SoSeparator * CelestialWidget::Declination () [private]
Definition at line 170 of file CelestialWidget.cpp.
References m_declination, m_rightAscension, sphereRadio, Point3D::x, Point3D::y, and Point3D::z.
Referenced by CelestialWidget(), and CoordinatesChanged().
SoSeparator * CelestialWidget::Ecliptic () const [private]
Definition at line 252 of file CelestialWidget.cpp.
References tgc::Ecliptic, tgc::Pi, and sphereRadio.
Referenced by CelestialWidget().
SoSeparator * CelestialWidget::Ejes () const [private]
Definition at line 284 of file CelestialWidget.cpp.
References sphereRadio.
Referenced by CelestialWidget().
double CelestialWidget::getDeclination () [inline]
Definition at line 58 of file CelestialWidget.h.
References m_declination.
double CelestialWidget::getRightAscension () [inline]
Definition at line 59 of file CelestialWidget.h.
References m_rightAscension.
double CelestialWidget::getSphereRadio () [inline]
Definition at line 57 of file CelestialWidget.h.
References sphereRadio.
SoSeparator * CelestialWidget::Points () const [private]
Definition at line 347 of file CelestialWidget.cpp.
References sphereRadio.
Referenced by CelestialWidget().
SoSeparator * CelestialWidget::RightAscension () [private]
Definition at line 437 of file CelestialWidget.cpp.
References m_rightAscension, sphereRadio, Point3D::x, Point3D::y, and Point3D::z.
Referenced by CelestialWidget(), and CoordinatesChanged().
SoSeparator * CelestialWidget::Sphere () const [private]
Definition at line 519 of file CelestialWidget.cpp.
References sphereRadio.
Referenced by CelestialWidget().
SoSeparator * CelestialWidget::Star () [private]
Definition at line 539 of file CelestialWidget.cpp.
References m_declination, m_rightAscension, and sphereRadio.
Referenced by CelestialWidget(), and CoordinatesChanged().
Member Data Documentation
double CelestialWidget::m_declination [private]
Definition at line 81 of file CelestialWidget.h.
Referenced by CelestialWidget(), CoordinatesChanged(), Declination(), getDeclination(), and Star().
QLabel* CelestialWidget::m_declinationValue [private]
Definition at line 66 of file CelestialWidget.h.
Referenced by CelestialWidget(), and CoordinatesChanged().
double CelestialWidget::m_rightAscension [private]
Definition at line 82 of file CelestialWidget.h.
Referenced by CelestialWidget(), CoordinatesChanged(), Declination(), getRightAscension(), RightAscension(), and Star().
QLabel* CelestialWidget::m_rightValue [private]
Definition at line 65 of file CelestialWidget.h.
Referenced by CelestialWidget(), and CoordinatesChanged().
SoSeparator* CelestialWidget::m_rootNode [private]
Definition at line 77 of file CelestialWidget.h.
Referenced by CelestialWidget(), and CoordinatesChanged().
const double CelestialWidget::sphereRadio [private]
Definition at line 79 of file CelestialWidget.h.
Referenced by CelestialEquator(), Declination(), Ecliptic(), Ejes(), getSphereRadio(), Points(), RightAscension(), Sphere(), and Star().
The documentation for this class was generated from the following files:
CelestialWidget.h
CelestialWidget.cpp