Tonatiuh: LightDialog Class Reference
http://tonatiuh.googlecode.com
LightDialog Class Reference
LightDialog class is the dialog to define the light parameters.
Public Slots
void accept ()
void SetValue (SoNode *node, QString paramenterName, QString newValue)
Public Member Functions
LightDialog (TLightKit *currentLightKit, QVector< TSunShapeFactory * > sunshapeFactoryList, QWidget *parent=0)
~LightDialog ()
TLightKit * GetTLightKit ()
Protected Slots
void ChangeSunshape (int index)
Private Member Functions
void SunPositionTab ()
void SunshapeTab ()
void SunshapeBox ()
Private Attributes
TLightKit * m_currentLightKit
int m_currentSunShapeIndex
TSunShape * m_newSunShape
QMap< QString, TSunShapeFactory * > m_sunshapeList
Detailed Description
LightDialog class is the dialog to define the light parameters.
LightDialog sets light parameters. The parameters that user can define are light suunshape, light input aperture shape and light position.
Definition at line 62 of file LightDialog.h.
Constructor & Destructor Documentation
LightDialog::LightDialog (TLightKit * currentLightKit, QVector< TSunShapeFactory * > sunshapeFactoryList, QWidget * parent = 0)
Creates a new dialog for the light definition.
The dialog present a list given by sunshapeFactoryList to define light sunshape, shapeFactoryList for the light input aperture and shows the the light parameters defined in the light currentLightKit.
Definition at line 57 of file LightDialog.cpp.
References m_newSunShape, m_sunshapeList, Ui_LightDialog::setupUi(), SetValue(), SunPositionTab(), Ui_LightDialog::sunshapeParameters, and SunshapeTab().
LightDialog::~LightDialog ()
Destroys the LightDialog object.
Definition at line 83 of file LightDialog.cpp.
Member Function Documentation
void LightDialog::accept () [slot]
Definition at line 105 of file LightDialog.cpp.
References Ui_LightDialog::sunshapeCombo.
void LightDialog::ChangeSunshape (int index) [protected, slot]
Changes parameters of the shunshape paraneters view to sunshape type given by index.
Definition at line 125 of file LightDialog.cpp.
References TSunShapeFactory::CreateTSunShape(), m_currentLightKit, m_currentSunShapeIndex, m_newSunShape, m_sunshapeList, FieldContainerWidget::SetContainer(), Ui_LightDialog::sunshapeCombo, and Ui_LightDialog::sunshapeParameters.
Referenced by SunshapeBox().
TLightKit * LightDialog::GetTLightKit ()
Returns a lightkit with the parameters defined in the dialog.
Definition at line 91 of file LightDialog.cpp.
References Ui_LightDialog::azimuthSpin, TLightKit::ChangePosition(), tgc::Degree, Ui_LightDialog::elevationSpin, and m_newSunShape.
Referenced by MainWindow::DefineSunLight().
void LightDialog::SetValue (SoNode * node, QString paramenterName, QString newValue) [slot]
Definition at line 114 of file LightDialog.cpp.
Referenced by LightDialog().
void LightDialog::SunPositionTab () [private]
Changes parameters of the shape paraneters view to shape type given by index.
Updates the sun position tab values to the values of the current light.
Definition at line 164 of file LightDialog.cpp.
References TLightKit::azimuth, Ui_LightDialog::azimuthSpin, tgc::Degree, Ui_LightDialog::elevationSpin, m_currentLightKit, and TLightKit::zenith.
Referenced by LightDialog().
void LightDialog::SunshapeBox () [private]
Definition at line 207 of file LightDialog.cpp.
References ChangeSunshape(), m_currentSunShapeIndex, m_newSunShape, m_sunshapeList, and Ui_LightDialog::sunshapeCombo.
Referenced by SunshapeTab().
void LightDialog::SunshapeTab () [private]
Updates the dialog values to the values of the current light.
Definition at line 178 of file LightDialog.cpp.
References SunshapeBox().
Referenced by LightDialog().
Member Data Documentation
TLightKit* LightDialog::m_currentLightKit [private]
Definition at line 85 of file LightDialog.h.
Referenced by ChangeSunshape(), and SunPositionTab().
int LightDialog::m_currentSunShapeIndex [private]
Definition at line 87 of file LightDialog.h.
Referenced by ChangeSunshape(), and SunshapeBox().
TSunShape* LightDialog::m_newSunShape [private]
Definition at line 88 of file LightDialog.h.
Referenced by ChangeSunshape(), GetTLightKit(), LightDialog(), and SunshapeBox().
QMap< QString, TSunShapeFactory* > LightDialog::m_sunshapeList [private]
Definition at line 90 of file LightDialog.h.
Referenced by ChangeSunshape(), LightDialog(), and SunshapeBox().
The documentation for this class was generated from the following files:
LightDialog.h
LightDialog.cpp