Tonatiuh: InstanceNode Class Reference
http://tonatiuh.googlecode.com
InstanceNode Class Reference
InstanceNode class represents a instance of a node in the scene.
Public Member Functions
InstanceNode (SoNode *node)
InstanceNode (const InstanceNode *node)
~InstanceNode ()
void SetNode (SoNode *node)
void SetParent (InstanceNode *parent)
void AddChild (InstanceNode *child)
void InsertChild (int row, InstanceNode *instanceChild)
SoNode * GetNode () const
InstanceNode * GetParent () const
QString GetNodeURL () const
void Print (int level) const
bool Intersect (const Ray &ray, RandomDeviate &rand, bool *isShapeFront, InstanceNode **modelNode, Ray *outputRay)
void Analyze (std::vector< Ray > *raysWay, QMutex *mutex)
template<class T >
void RecursivlyApply (void(T::*func)(void))
template<class T , class Param1 >
void RecursivlyApply (void(T::*func)(Param1), Param1 param1)
template<class T , class Param1 >
void RecursivlyApplyWithMto (void(T::*func)(Param1), Param1 param1)
template<class T , class Param1 , class Param2 >
void RecursivlyApplyWithMto (void(T::*func)(Param1, Param2), Param1 param1, Param1 param2)
void DisconnectAllTrackers ()
void ReconnectAllTrackers (TLightKit *coinLight)
void DisplayAnalyzeResults ()
void ResetAnalyzeValues ()
void UpdateAnalyzerSize (SceneModel *pModel)
void SetAimingPointRelativity (bool relative)
void PrepareAnalyze (SceneModel *pModel)
void FinalyzeAnalyze (double raydensity, TAnalyzerKit *analyzerKit)
void extendBoxForLight (SbBox3f *extendedBox)
bool IsTreeContainAnalyzer ()
BBox GetIntersectionBBox ()
Transform GetIntersectionTransform ()
void SetIntersectionBBox (BBox nodeBBox)
void SetIntersectionTransform (Transform nodeTransform)
Public Attributes
QVector< InstanceNode * > children
Private Attributes
SoNode * m_coinNode
InstanceNode * m_parent
BBox m_bbox
Transform m_transformWTO
Transform m_transformOTW
Detailed Description
InstanceNode class represents a instance of a node in the scene.
In a scene, a node can be shared by more that one parent. Each of these shared instances is represented in a scene as a InstanceNode object. Any change made whitin a shared node is reflected in all node's InstanceNode.
Definition at line 65 of file InstanceNode.h.
Constructor & Destructor Documentation
InstanceNode::InstanceNode (SoNode * node)
Definition at line 60 of file InstanceNode.cpp.
Referenced by InstanceNode().
InstanceNode::InstanceNode (const InstanceNode * node)
Definition at line 65 of file InstanceNode.cpp.
References children, InstanceNode(), m_coinNode, and m_parent.
InstanceNode::~InstanceNode ()
Definition at line 78 of file InstanceNode.cpp.
References children.
Member Function Documentation
void InstanceNode::AddChild (InstanceNode * child)
Appends new child node to the end of the child list.
Definition at line 107 of file InstanceNode.cpp.
References children, and SetParent().
Referenced by SceneModel::AddInstanceNode().
void InstanceNode::Analyze (std::vector< Ray > * raysWay, QMutex * mutex)
Definition at line 199 of file InstanceNode.cpp.
References children, TAnalyzerResultKit::Compute(), GetNode(), and m_transformWTO.
Referenced by RayTracerNoTr::operator()(), and RayTracer::operator()().
void InstanceNode::DisconnectAllTrackers ()
Definition at line 225 of file InstanceNode.cpp.
References TTracker::Disconnect().
Referenced by SceneModel::DisconnectAllTrackers().
void InstanceNode::DisplayAnalyzeResults ()
Definition at line 220 of file InstanceNode.cpp.
References TAnalyzerKit::DisplayResults().
Referenced by SceneModel::DisplayAnalyzeResults().
void InstanceNode::extendBoxForLight (SbBox3f * extendedBox)
Definition at line 279 of file InstanceNode.cpp.
References children, GetNode(), IsTreeContainAnalyzer(), and tgf::MatrixFromSoTransform().
void InstanceNode::FinalyzeAnalyze (double raydensity, TAnalyzerKit * analyzerKit)
Definition at line 251 of file InstanceNode.cpp.
References children, TAnalyzerResultKit::FinalizeCompute(), GetNode(), m_transformOTW, and m_transformWTO.
Referenced by SceneModel::FinalyzeAnalyze().
BBox InstanceNode::GetIntersectionBBox ()
Definition at line 339 of file InstanceNode.cpp.
References m_bbox.
Referenced by trf::ComputeSceneTreeMap().
Transform InstanceNode::GetIntersectionTransform ()
Definition at line 344 of file InstanceNode.cpp.
References m_transformWTO.
Referenced by trf::ExportSurfaceLocalCoordinates().
SoNode * InstanceNode::GetNode () const [inline]
Definition at line 128 of file InstanceNode.h.
References m_coinNode.
Referenced by ExportDialog::accept(), Analyze(), MainWindow::ChangeGridSettings(), MainWindow::ChangeNodeName(), MainWindow::ChangeSelection(), CmdChangeNodeName::CmdChangeNodeName(), CmdCopy::CmdCopy(), CmdCut::CmdCut(), CmdDelete::CmdDelete(), CmdDeleteTracker::CmdDeleteTracker(), CmdInsertAnalyzerKit::CmdInsertAnalyzerKit(), CmdInsertSeparatorKit::CmdInsertSeparatorKit(), CmdInsertShapeKit::CmdInsertShapeKit(), CmdInsertTracker::CmdInsertTracker(), trf::ComputeSceneTreeMap(), MainWindow::CreateAnalyzerNode(), MainWindow::CreateGroupNode(), MainWindow::CreateMaterial(), MainWindow::CreateShape(), MainWindow::CreateSurfaceNode(), MainWindow::CreateTracker(), SceneModel::data(), MainWindow::Delete(), SceneModel::DeleteInstanceTree(), SceneModelView::dropEvent(), trf::ExportSurfaceGlobalCoordinates(), trf::ExportSurfaceLocalCoordinates(), extendBoxForLight(), FinalyzeAnalyze(), MainWindow::FinishManipulation(), SceneModel::GenerateInstanceTree(), ExportDialog::GetSelectedSurface(), MainWindow::InsertFileComponent(), MainWindow::InsertUserDefinedComponent(), Intersect(), IsTreeContainAnalyzer(), MainWindow::ItemDragAndDrop(), MainWindow::ItemDragAndDropCopy(), operator<<(), operator==(), MainWindow::Paste(), SceneModel::PathFromIndex(), RecursivlyApply(), RecursivlyApplyWithMto(), SceneModel::RemoveCoinNode(), SceneModel::rowCount(), MainWindow::Run(), MainWindow::SaveComponent(), NodeNameDelegate::setEditorData(), ScriptRayTracer::SetSunPositionToScene(), MainWindow::SetValue(), MainWindow::ShowMenu(), MainWindow::SoManip_to_SoTransform(), MainWindow::SoTransform_to_SoCenterballManip(), MainWindow::SoTransform_to_SoHandleBoxManip(), MainWindow::SoTransform_to_SoJackManip(), MainWindow::SoTransform_to_SoTabBoxManip(), MainWindow::SoTransform_to_SoTrackballManip(), MainWindow::SoTransform_to_SoTransformBoxManip(), MainWindow::SoTransform_to_SoTransformerManip(), and ScriptRayTracer::Trace().
QString InstanceNode::GetNodeURL () const
Returns node URL.
Definition at line 86 of file InstanceNode.cpp.
References GetNodeURL(), GetParent(), and m_coinNode.
Referenced by MainWindow::ChangeModelScene(), MainWindow::DefineSunLight(), MainWindow::Delete(), GetNodeURL(), ExportDialog::GetSelectedSurface(), and MainWindow::StartOver().
InstanceNode * InstanceNode::GetParent () const [inline]
Returns parent instance.
Definition at line 136 of file InstanceNode.h.
References m_parent.
Referenced by CmdCut::CmdCut(), CmdDelete::CmdDelete(), CmdDeleteTracker::CmdDeleteTracker(), MainWindow::Delete(), SceneModel::DeleteInstanceTree(), GetNodeURL(), MainWindow::ItemDragAndDrop(), operator==(), SceneModel::parent(), MainWindow::Paste(), SceneModel::PathFromIndex(), MainWindow::ReadyForRaytracing(), SceneModel::SetNodeName(), and MainWindow::ShowMenu().
void InstanceNode::InsertChild (int row, InstanceNode * instanceChild)
Inserts the instanceChild node as child number row.
Definition at line 115 of file InstanceNode.cpp.
References children, and SetParent().
Referenced by SceneModel::InsertCoinNode(), SceneModel::InsertLightNode(), and SceneModel::Paste().
bool InstanceNode::Intersect (const Ray & ray, RandomDeviate & rand, bool * isShapeFront, InstanceNode ** modelNode, Ray * outputRay)
Definition at line 124 of file InstanceNode.cpp.
References children, GetNode(), TShape::Intersect(), BBox::IntersectP(), m_bbox, m_transformOTW, m_transformWTO, Ray::maxt, TMaterial::OutputRay(), and DifferentialGeometry::shapeFrontSide.
Referenced by RayTracerNoTr::operator()(), and RayTracer::operator()().
bool InstanceNode::IsTreeContainAnalyzer ()
Definition at line 322 of file InstanceNode.cpp.
References children, and GetNode().
Referenced by extendBoxForLight().
void InstanceNode::PrepareAnalyze (SceneModel * pModel)
Definition at line 245 of file InstanceNode.cpp.
References TAnalyzerResultKit::PrepareCompute(), and TAnalyzerKit::PrepareCompute().
Referenced by SceneModel::PrepareAnalyze().
void InstanceNode::Print (int level) const
Definition at line 94 of file InstanceNode.cpp.
References children, and m_coinNode.
void InstanceNode::ReconnectAllTrackers (TLightKit * coinLight)
Definition at line 231 of file InstanceNode.cpp.
References TTracker::SetLightAngles().
Referenced by SceneModel::ReconnectAllTrackers().
template<class T , class Param1 > void InstanceNode::RecursivlyApply (void(T::*)(Param1) func, Param1 param1)
Definition at line 397 of file InstanceNode.cpp.
References children, and GetNode().
template<class T > void InstanceNode::RecursivlyApply (void(T::*)(void) func)
Definition at line 382 of file InstanceNode.cpp.
References children, and GetNode().
template<class T , class Param1 > void InstanceNode::RecursivlyApplyWithMto (void(T::*)(Param1) func, Param1 param1)
Definition at line 412 of file InstanceNode.cpp.
References children, GetNode(), and m_transformWTO.
template<class T , class Param1 , class Param2 > void InstanceNode::RecursivlyApplyWithMto (void(T::*)(Param1, Param2) func, Param1 param1, Param1 param2)
Definition at line 427 of file InstanceNode.cpp.
References children, GetNode(), and m_transformWTO.
void InstanceNode::ResetAnalyzeValues ()
Definition at line 215 of file InstanceNode.cpp.
References TAnalyzerKit::ResetValues().
Referenced by SceneModel::ResetAnalyzeValues().
void InstanceNode::SetAimingPointRelativity (bool relative)
Definition at line 240 of file InstanceNode.cpp.
Referenced by MainWindow::SetAimingPointRelativity().
void InstanceNode::SetIntersectionBBox (BBox nodeBBox)
Definition at line 349 of file InstanceNode.cpp.
References m_bbox.
Referenced by trf::ComputeSceneTreeMap().
void InstanceNode::SetIntersectionTransform (Transform nodeTransform)
Set node world to object transform to nodeTransform .
Definition at line 356 of file InstanceNode.cpp.
References Transform::GetInverse(), m_transformOTW, and m_transformWTO.
Referenced by trf::ComputeSceneTreeMap(), and ScriptRayTracer::Trace().
void InstanceNode::SetNode (SoNode * node) [inline]
Definition at line 123 of file InstanceNode.h.
References m_coinNode.
void InstanceNode::SetParent (InstanceNode * parent) [inline]
Definition at line 118 of file InstanceNode.h.
References m_parent.
Referenced by AddChild(), and InsertChild().
void InstanceNode::UpdateAnalyzerSize (SceneModel * pModel)
Definition at line 236 of file InstanceNode.cpp.
References TAnalyzerKit::UpdateSize().
Member Data Documentation
QVector< InstanceNode* > InstanceNode::children
Definition at line 104 of file InstanceNode.h.
Referenced by AddChild(), Analyze(), MainWindow::ChangeGridSettings(), MainWindow::ChangeModelScene(), CmdCut::CmdCut(), CmdDelete::CmdDelete(), CmdDeleteTracker::CmdDeleteTracker(), CmdPaste::CmdPaste(), trf::ComputeSceneTreeMap(), SceneModel::Cut(), MainWindow::DefineSunLight(), SceneModel::DeleteInstanceTree(), extendBoxForLight(), FinalyzeAnalyze(), SceneModel::index(), SceneModel::IndexFromNodeUrl(), SceneModel::IndexFromPath(), InsertChild(), SceneModel::InsertLightNode(), InstanceNode(), Intersect(), IsTreeContainAnalyzer(), SceneModel::parent(), Print(), MainWindow::ReadyForRaytracing(), RecursivlyApply(), RecursivlyApplyWithMto(), CmdPaste::redo(), SceneModel::RemoveCoinNode(), SceneModel::RemoveLightNode(), SceneModel::rowCount(), SceneModel::SetNodeName(), MainWindow::StartOver(), ScriptRayTracer::Trace(), CmdPaste::undo(), and ~InstanceNode().
BBox InstanceNode::m_bbox [private]
Definition at line 109 of file InstanceNode.h.
Referenced by GetIntersectionBBox(), Intersect(), and SetIntersectionBBox().
SoNode* InstanceNode::m_coinNode [private]
Definition at line 107 of file InstanceNode.h.
Referenced by GetNode(), GetNodeURL(), InstanceNode(), Print(), and SetNode().
InstanceNode* InstanceNode::m_parent [private]
Definition at line 108 of file InstanceNode.h.
Referenced by GetParent(), InstanceNode(), and SetParent().
Transform InstanceNode::m_transformOTW [private]
Definition at line 111 of file InstanceNode.h.
Referenced by FinalyzeAnalyze(), Intersect(), and SetIntersectionTransform().
Transform InstanceNode::m_transformWTO [private]
Definition at line 110 of file InstanceNode.h.
Referenced by Analyze(), FinalyzeAnalyze(), GetIntersectionTransform(), Intersect(), RecursivlyApplyWithMto(), and SetIntersectionTransform().
The documentation for this class was generated from the following files:
InstanceNode.h
InstanceNode.cpp