Tonatiuh: RandomDeviate Class Reference
http://tonatiuh.googlecode.com
RandomDeviate Class Reference
RandomDeviate is the base class for random generators.
Public Member Functions
RandomDeviate (const unsigned long arraySize=1000000)
virtual ~RandomDeviate ()
virtual void FillArray (double *array, const unsigned long arraySize)=0
unsigned long NumbersGenerated () const
unsigned long NumbersProvided () const
double RandomDouble ()
RandomDeviate (const unsigned long arraySize=100000)
virtual ~RandomDeviate ()
virtual void FillArray (double *array, const unsigned long arraySize)=0
unsigned long NumbersGenerated () const
unsigned long NumbersProvided () const
double RandomDouble ()
Private Attributes
const unsigned long m_arraySize
double * m_randomNumber
unsigned long m_numbersGenerated
unsigned long m_nextRandomNumber
Detailed Description
RandomDeviate is the base class for random generators.
A random generator class can be written based on this class.
Definition at line 47 of file raytracing/RandomDeviate.h.
Constructor & Destructor Documentation
RandomDeviate::RandomDeviate (const unsigned long arraySize = 1000000) [inline]
Definition at line 66 of file raytracing/RandomDeviate.h.
References m_randomNumber.
RandomDeviate::~RandomDeviate () [inline, virtual]
Definition at line 72 of file raytracing/RandomDeviate.h.
References m_randomNumber.
RandomDeviate::RandomDeviate (const unsigned long arraySize = 100000) [explicit]
virtual RandomDeviate::~RandomDeviate () [virtual]
Member Function Documentation
virtual void RandomDeviate::FillArray (double * array, const unsigned long arraySize) [pure virtual]
Implemented in ParallelRandomDeviate.
Referenced by ParallelRandomDeviate::FillArray(), and RandomDouble().
virtual void RandomDeviate::FillArray (double * array, const unsigned long arraySize) [pure virtual]
Implemented in ParallelRandomDeviate.
unsigned long RandomDeviate::NumbersGenerated () const [inline]
Definition at line 88 of file raytracing/RandomDeviate.h.
References m_numbersGenerated.
unsigned long RandomDeviate::NumbersGenerated () const
unsigned long RandomDeviate::NumbersProvided () const
unsigned long RandomDeviate::NumbersProvided () const [inline]
Definition at line 93 of file raytracing/RandomDeviate.h.
References m_arraySize, m_nextRandomNumber, and m_numbersGenerated.
double RandomDeviate::RandomDouble () [inline]
Definition at line 77 of file raytracing/RandomDeviate.h.
References FillArray(), m_arraySize, m_nextRandomNumber, m_numbersGenerated, and m_randomNumber.
Referenced by tgf::AlternateBoxMuller(), RayTracerNoTr::NewPrimitiveRay(), and RayTracer::NewPrimitiveRay().
double RandomDeviate::RandomDouble ()
Member Data Documentation
const unsigned long RandomDeviate::m_arraySize [private]
Definition at line 60 of file raytracing/RandomDeviate.h.
Referenced by NumbersProvided(), and RandomDouble().
unsigned long RandomDeviate::m_nextRandomNumber [private]
Definition at line 63 of file raytracing/RandomDeviate.h.
Referenced by NumbersProvided(), and RandomDouble().
unsigned long RandomDeviate::m_numbersGenerated [private]
Definition at line 62 of file raytracing/RandomDeviate.h.
Referenced by NumbersGenerated(), NumbersProvided(), and RandomDouble().
double * RandomDeviate::m_randomNumber [private]
Definition at line 61 of file raytracing/RandomDeviate.h.
Referenced by RandomDeviate(), RandomDouble(), and ~RandomDeviate().
The documentation for this class was generated from the following files:
raytracing/RandomDeviate.h
statistics/RandomDeviate.h