Tonatiuh: TLightKit Class Reference
http://tonatiuh.googlecode.com
TLightKit Class Reference
The TLightKit class provides a kit with a transform, a light, a shape and a sunshape to represents the sun light.
Public Member Functions
TLightKit ()
void ChangePosition (double newAzimuth, double newZenith)
void Update (BBox box)
void ComputeLightSourceArea (QVector< QPair< TShapeKit *, Transform > > surfacesList)
Static Public Member Functions
static void initClass ()
Public Attributes
trt::TONATIUH_REAL azimuth
trt::TONATIUH_REAL zenith
Private Member Functions
SO_KIT_HEADER (TLightKit)
SO_KIT_CATALOG_ENTRY_HEADER (iconMaterial)
SO_KIT_CATALOG_ENTRY_HEADER (iconTexture)
SO_KIT_CATALOG_ENTRY_HEADER (tsunshape)
virtual ~TLightKit ()
void UpdateSunPosition ()
Detailed Description
The TLightKit class provides a kit with a transform, a light, a shape and a sunshape to represents the sun light.
The TLightKit structure:
  CLASS TLightKit
  -->"this"
        "callbackList"
  -->   "transformGroup"
  -->      "transform"
  -->      "light"
  -->      "iconSeparator"
  -->         "icon"
  -->      "tsunshape"
Detailed information on catalog parts:
  CLASS TLightKit
  PVT   "this",  TLightKit  ---
        "callbackList",  SoNodeKitListPart [ SoCallback, SoEventCallback ]
  PVT   "transformGroup",  SoTransformSeparator  ---
        "transform",  SoTransform  ---
        "light",  SoLight  --- , (default type = SoDirectionalLight)
  PVT   "iconSeparator",  SoSeparator  ---
        "icon",  SoNode  --- , (default type = SoCube)
        "tsunshape",  TSunShape  --- , (default type = TDefaultSunShape)
Definition at line 90 of file TLightKit.h.
Constructor & Destructor Documentation
TLightKit::TLightKit ()
Creates a new TLightKit.
Definition at line 80 of file TLightKit.cpp.
References azimuth, and zenith.
TLightKit::~TLightKit () [private, virtual]
Destructor.
Definition at line 129 of file TLightKit.cpp.
Member Function Documentation
void TLightKit::ChangePosition (double newAzimuth, double newZenith)
Changes the light position to azimuth, zenith, and distance from the scene centre. Azimuth and Zenith are in radians.
See also:
redo().
Definition at line 141 of file TLightKit.cpp.
References azimuth, and zenith.
Referenced by LightDialog::GetTLightKit(), CmdLightPositionModified::redo(), CmdLightKitModified::redo(), ScriptRayTracer::Trace(), CmdLightPositionModified::undo(), and CmdLightKitModified::undo().
void TLightKit::ComputeLightSourceArea (QVector< QPair< TShapeKit *, Transform > > surfacesList)
Definition at line 199 of file TLightKit.cpp.
References TLightShape::delta, TShape::GetBBox(), Transform::GetInverse(), BBox::pMax, BBox::pMin, TLightShape::SetLightSourceArea(), Point3D::x, TLightShape::xMax, TLightShape::xMin, Point3D::y, Point3D::z, TLightShape::zMax, and TLightShape::zMin.
Referenced by MainWindow::Run(), and ScriptRayTracer::Trace().
void TLightKit::initClass () [static]
Initializates TLightKit componets
Definition at line 72 of file TLightKit.cpp.
Referenced by main().
TLightKit::SO_KIT_CATALOG_ENTRY_HEADER (iconMaterial) [private]
TLightKit::SO_KIT_CATALOG_ENTRY_HEADER (tsunshape) [private]
TLightKit::SO_KIT_CATALOG_ENTRY_HEADER (iconTexture) [private]
TLightKit::SO_KIT_HEADER (TLightKit) [private]
void TLightKit::Update (BBox box)
Definition at line 150 of file TLightKit.cpp.
References TLightShape::delta, TSunShape::GetThetaMax(), tgc::Infinity, BBox::pMax, BBox::pMin, BBox::Volume(), Point3D::x, TLightShape::xMax, TLightShape::xMin, Point3D::y, Point3D::z, TLightShape::zMax, and TLightShape::zMin.
Referenced by SceneModel::UpdateSceneModel().
void TLightKit::UpdateSunPosition () [private]
Member Data Documentation
trt::TONATIUH_REAL TLightKit::azimuth
Definition at line 109 of file TLightKit.h.
Referenced by ChangePosition(), CmdLightKitModified::CmdLightKitModified(), CmdLightPositionModified::CmdLightPositionModified(), SceneModel::InsertLightNode(), CmdLightKitModified::redo(), CmdInsertTracker::redo(), LightDialog::SunPositionTab(), TLightKit(), and CmdDeleteTracker::undo().
trt::TONATIUH_REAL TLightKit::zenith
Definition at line 110 of file TLightKit.h.
Referenced by ChangePosition(), CmdLightKitModified::CmdLightKitModified(), CmdLightPositionModified::CmdLightPositionModified(), SceneModel::InsertLightNode(), CmdLightKitModified::redo(), CmdInsertTracker::redo(), LightDialog::SunPositionTab(), TLightKit(), and CmdDeleteTracker::undo().
The documentation for this class was generated from the following files:
TLightKit.h
TLightKit.cpp