Tonatiuh: CmdInsertTracker Class Reference
http://tonatiuh.googlecode.com
CmdInsertTracker Class Reference
CmdInsertTracker class is the insert command for trackers stored in the command stack.
Public Member Functions
CmdInsertTracker (TTracker *tracker, const QModelIndex &parentIndex, SoSceneKit *scene, SceneModel *model, QUndoCommand *parent=0)
~CmdInsertTracker ()
virtual void undo ()
virtual void redo ()
Private Attributes
TTracker * m_tracker
SoBaseKit * m_coinParent
SoSceneKit * m_scene
SceneModel * m_pModel
int m_row
Detailed Description
CmdInsertTracker class is the insert command for trackers stored in the command stack.
CmdInsertTracker represents a single shape insertion action on a scene, insert a new trackers node to the scene.
Definition at line 55 of file CmdInsertTracker.h.
Constructor & Destructor Documentation
CmdInsertTracker::CmdInsertTracker (TTracker * tracker, const QModelIndex & parentIndex, SoSceneKit * scene, SceneModel * model, QUndoCommand * parent = 0)
Creates a new tracker insert command that adds a tracker to a parent node with parentIndex in the model.
If parent is not null, this command is appended to parent's child list and then owns this command.
Definition at line 57 of file CmdInsertTracker.cpp.
References InstanceNode::GetNode(), m_coinParent, m_pModel, m_tracker, SceneModel::NodeFromIndex(), and tgf::SevereError().
CmdInsertTracker::~CmdInsertTracker ()
Destroys the CmdInsertTracker object.
Definition at line 72 of file CmdInsertTracker.cpp.
References m_tracker.
Member Function Documentation
void CmdInsertTracker::redo () [virtual]
Inserts the tracker in the scene model as a parentIndex child.
Definition at line 90 of file CmdInsertTracker.cpp.
References TLightKit::azimuth, SceneModel::InsertCoinNode(), m_coinParent, m_pModel, m_row, m_scene, m_tracker, TTracker::SetAzimuthAngle(), TTracker::SetZenithAngle(), and TLightKit::zenith.
void CmdInsertTracker::undo () [virtual]
Reverts model state. After undo() is called, the parentIndex node will not contain a tracker type node.
See also:
redo().
Definition at line 81 of file CmdInsertTracker.cpp.
References TTracker::Disconnect(), m_coinParent, m_pModel, m_row, m_tracker, and SceneModel::RemoveCoinNode().
Member Data Documentation
SoBaseKit* CmdInsertTracker::m_coinParent [private]
Definition at line 67 of file CmdInsertTracker.h.
Referenced by CmdInsertTracker(), redo(), and undo().
SceneModel* CmdInsertTracker::m_pModel [private]
Definition at line 69 of file CmdInsertTracker.h.
Referenced by CmdInsertTracker(), redo(), and undo().
int CmdInsertTracker::m_row [private]
Definition at line 70 of file CmdInsertTracker.h.
Referenced by redo(), and undo().
SoSceneKit* CmdInsertTracker::m_scene [private]
Definition at line 67 of file CmdInsertTracker.h.
Referenced by redo().
TTracker* CmdInsertTracker::m_tracker [private]
Definition at line 66 of file CmdInsertTracker.h.
Referenced by CmdInsertTracker(), redo(), undo(), and ~CmdInsertTracker().
The documentation for this class was generated from the following files:
CmdInsertTracker.h
CmdInsertTracker.cpp