Tonatiuh: ScriptEditorDialog Class Reference
http://tonatiuh.googlecode.com
ScriptEditorDialog Class Reference
ScriptEditorDialog class is the dialog to edit and run scripts with Tonatiuh.
Public Slots
void AbortEvaluation (QString error)
Public Member Functions
ScriptEditorDialog (QVector< TPhotonMapFactory * > listTPhotonMapFactory, QVector< RandomDeviateFactory * > listRandomDeviateFactory, QWidget *parent=0)
~ScriptEditorDialog ()
Protected Member Functions
void closeEvent (QCloseEvent *event)
Private Slots
void Close (bool checked)
void OpenScriptFile (const QModelIndex &index)
void RunScript ()
void SetCurrentFile (QString fileName)
void WriteMessage (QString message)
Private Attributes
QString m_currentScritFileName
FilesModel * m_fileModel
QScriptEngine * m_interpreter
Detailed Description
ScriptEditorDialog class is the dialog to edit and run scripts with Tonatiuh.
ScriptEditorDialog allow to the user open, edit, run and save scripts to automate the ray tracing.
Definition at line 58 of file ScriptEditorDialog.h.
Constructor & Destructor Documentation
ScriptEditorDialog::ScriptEditorDialog (QVector< TPhotonMapFactory * > listTPhotonMapFactory, QVector< RandomDeviateFactory * > listRandomDeviateFactory, QWidget * parent = 0)
Creates a dialog to edit scripts and run them. The lists listTPhotonMapFactory and listRandomDeviateFactory are the photon map types and random generator types that can be defined in the scripts to run Tonatiuh. The dialog explorer shows the directories and scripts files from dirName path.
Definition at line 53 of file ScriptEditorDialog.cpp.
References AbortEvaluation(), Close(), m_fileModel, m_interpreter, OpenScriptFile(), RunScript(), and SetCurrentFile().
ScriptEditorDialog::~ScriptEditorDialog ()
Destroys the file dialog.
Definition at line 102 of file ScriptEditorDialog.cpp.
References m_fileModel, and m_interpreter.
Member Function Documentation
void ScriptEditorDialog::AbortEvaluation (QString error) [slot]
Definition at line 108 of file ScriptEditorDialog.cpp.
References m_interpreter.
Referenced by ScriptEditorDialog().
void ScriptEditorDialog::Close (bool checked) [private, slot]
Closes dialog.
Closes the dialog.
Definition at line 130 of file ScriptEditorDialog.cpp.
Referenced by ScriptEditorDialog().
void ScriptEditorDialog::closeEvent (QCloseEvent * event) [protected]
Reimplemented from QDialog::closeEvent().
Definition at line 118 of file ScriptEditorDialog.cpp.
void ScriptEditorDialog::OpenScriptFile (const QModelIndex & index) [private, slot]
Opens the file selected into the file explorer.
Before open the selected script, it verifies if the current script can be closed.
Definition at line 141 of file ScriptEditorDialog.cpp.
References m_fileModel.
Referenced by ScriptEditorDialog().
void ScriptEditorDialog::RunScript () [private, slot]
Executes the code editor script.
Definition at line 155 of file ScriptEditorDialog.cpp.
References tonatiuh_script::init(), m_currentScritFileName, m_interpreter, ScriptRayTracer::SetDir(), and WriteMessage().
Referenced by ScriptEditorDialog().
void ScriptEditorDialog::SetCurrentFile (QString fileName) [private, slot]
Sets the editor current script file to fileName.
Changes the editor dialog title to shows the current file base name.
Definition at line 221 of file ScriptEditorDialog.cpp.
References m_currentScritFileName, and WriteMessage().
Referenced by ScriptEditorDialog().
void ScriptEditorDialog::WriteMessage (QString message) [private, slot]
Write the message at log window.
Definition at line 242 of file ScriptEditorDialog.cpp.
Referenced by RunScript(), and SetCurrentFile().
Member Data Documentation
QString ScriptEditorDialog::m_currentScritFileName [private]
Definition at line 81 of file ScriptEditorDialog.h.
Referenced by RunScript(), and SetCurrentFile().
FilesModel* ScriptEditorDialog::m_fileModel [private]
Definition at line 82 of file ScriptEditorDialog.h.
Referenced by OpenScriptFile(), ScriptEditorDialog(), and ~ScriptEditorDialog().
QScriptEngine* ScriptEditorDialog::m_interpreter [private]
Definition at line 83 of file ScriptEditorDialog.h.
Referenced by AbortEvaluation(), RunScript(), ScriptEditorDialog(), and ~ScriptEditorDialog().
The documentation for this class was generated from the following files:
ScriptEditorDialog.h
ScriptEditorDialog.cpp