Tonatiuh: TMaterialFactory Class Reference
http://tonatiuh.googlecode.com
TMaterialFactory Class Reference
Public Member Functions
virtual ~TMaterialFactory ()
virtual QString TMaterialName () const =0
virtual QIcon TMaterialIcon () const =0
virtual TMaterial * CreateTMaterial () const =0
Detailed Description
Definition at line 48 of file TMaterialFactory.h.
Constructor & Destructor Documentation
virtual TMaterialFactory::~TMaterialFactory () [inline, virtual]
Definition at line 51 of file TMaterialFactory.h.
Member Function Documentation
virtual TMaterial* TMaterialFactory::CreateTMaterial () const [pure virtual]
Referenced by MainWindow::CreateMaterial(), and PluginManager::LoadMaterialPlugin().
virtual QIcon TMaterialFactory::TMaterialIcon () const [pure virtual]
Referenced by MainWindow::SetupActionsInsertMaterial().
virtual QString TMaterialFactory::TMaterialName () const [pure virtual]
Referenced by MainWindow::CreateMaterial(), and MainWindow::SetupActionsInsertMaterial().
The documentation for this class was generated from the following file:
TMaterialFactory.h