Tonatiuh: Matrix4x4 Class Reference
http://tonatiuh.googlecode.com
Matrix4x4 Class Reference
Public Member Functions
Matrix4x4 ()
Matrix4x4 (double array[4][4])
Matrix4x4 (double t00, double t01, double t02, double t03, double t10, double t11, double t12, double t13, double t20, double t21, double t22, double t23, double t30, double t31, double t32, double t33)
Matrix4x4 (const Matrix4x4 &rhs)
~Matrix4x4 ()
Ptr< Matrix4x4 > Transpose () const
Ptr< Matrix4x4 > Inverse () const
bool operator== (const Matrix4x4 &matrix) const
Public Attributes
double m [4][4]
Detailed Description
Definition at line 47 of file Matrix4x4.h.
Constructor & Destructor Documentation
Matrix4x4::Matrix4x4 ()
Definition at line 46 of file Matrix4x4.cpp.
References m.
Referenced by Inverse(), and Transpose().
Matrix4x4::Matrix4x4 (double array[4][4])
Definition at line 57 of file Matrix4x4.cpp.
References m.
Matrix4x4::Matrix4x4 (double t00, double t01, double t02, double t03, double t10, double t11, double t12, double t13, double t20, double t21, double t22, double t23, double t30, double t31, double t32, double t33)
Definition at line 63 of file Matrix4x4.cpp.
References m.
Matrix4x4::Matrix4x4 (const Matrix4x4 & rhs)
Definition at line 75 of file Matrix4x4.cpp.
References m.
Matrix4x4::~Matrix4x4 ()
Definition at line 82 of file Matrix4x4.cpp.
Member Function Documentation
Ptr< Matrix4x4 > Matrix4x4::Inverse () const
Definition at line 117 of file Matrix4x4.cpp.
References tgc::Epsilon, m, Matrix4x4(), and tgf::SevereError().
bool Matrix4x4::operator== (const Matrix4x4 & matrix) const
Definition at line 86 of file Matrix4x4.cpp.
References tgc::Epsilon, and m.
Ptr< Matrix4x4 > Matrix4x4::Transpose () const
Definition at line 109 of file Matrix4x4.cpp.
References m, and Matrix4x4().
Member Data Documentation
double Matrix4x4::m[4][4]
Definition at line 63 of file Matrix4x4.h.
Referenced by Inverse(), Matrix4x4(), operator<<(), operator==(), and Transpose().
The documentation for this class was generated from the following files:
Matrix4x4.h
Matrix4x4.cpp