Tonatiuh: TAnalyzerKit Class Reference
http://tonatiuh.googlecode.com
TAnalyzerKit Class Reference
TAnalyzerKit class groups what is necessary to the shape.
Public Member Functions
TAnalyzerKit ()
bool IntersectP (const Ray &ray) const
void Compute (std::vector< std::vector< Ray > > *raysWays, Transform *m_transformWTO, QMutex *mutex)
void PrepareCompute (SceneModel *pModel)
void FinalizeCompute (double raydensity, Transform *m_transformWTO)
void DisplayResults ()
void RemoveResult (SceneModel *pModel)
void UpdateSize (SceneModel *pModel)
void ResetValues ()
QString getIcon ()
SoNodeKitListPart * GetLevelList ()
TSeparatorKit * GetResultsList ()
Static Public Member Functions
static void initClass ()
Private Types
typedef TSeparatorKit inherited
Private Member Functions
SO_KIT_HEADER (TAnalyzerKit)
SO_KIT_CATALOG_ENTRY_HEADER (parameter)
SO_KIT_CATALOG_ENTRY_HEADER (result)
SO_KIT_CATALOG_ENTRY_HEADER (levelList)
virtual ~TAnalyzerKit ()
Private Attributes
SoSFVec3s previousSplit
trt::TONATIUH_REAL previousElemSize
Detailed Description
TAnalyzerKit class groups what is necessary to the shape.
TAnalyzerKit groups the shape geometry, material and the transformation.
Definition at line 66 of file TAnalyzerKit.h.
Member Typedef Documentation
typedef TSeparatorKit TAnalyzerKit::inherited [private]
Reimplemented from TSeparatorKit.
Definition at line 68 of file TAnalyzerKit.h.
Constructor & Destructor Documentation
TAnalyzerKit::TAnalyzerKit ()
Constructor.
Definition at line 78 of file TAnalyzerKit.cpp.
References GetLevelList(), TSeparatorKit::getPart(), TAnalyzerLevel::materialColor, TAnalyzerLevel::materialTransparency, TAnalyzerLevel::minValue, previousElemSize, previousSplit, and TSeparatorKit::TSeparatorKit().
TAnalyzerKit::~TAnalyzerKit () [private, virtual]
Destroys the TAnalyzerKit object.
Definition at line 181 of file TAnalyzerKit.cpp.
Member Function Documentation
void TAnalyzerKit::Compute (std::vector< std::vector< Ray > > * raysWays, Transform * m_transformWTO, QMutex * mutex)
void TAnalyzerKit::DisplayResults ()
Definition at line 352 of file TAnalyzerKit.cpp.
References TAnalyzerResultKit::DisplayResult(), GetLevelList(), TSeparatorKit::getPart(), GetResultsList(), TAnalyzerParameter::infoDisplayed, and TAnalyzerParameter::setParent().
Referenced by InstanceNode::DisplayAnalyzeResults(), and ResetValues().
void TAnalyzerKit::FinalizeCompute (double raydensity, Transform * m_transformWTO)
Definition at line 314 of file TAnalyzerKit.cpp.
References TSeparatorKit::getPart().
QString TAnalyzerKit::getIcon ()
Returns the icon that represents TSeparatorKit nodes.
Reimplemented from TSeparatorKit.
Definition at line 387 of file TAnalyzerKit.cpp.
Referenced by SceneModel::data().
SoNodeKitListPart * TAnalyzerKit::GetLevelList ()
Definition at line 186 of file TAnalyzerKit.cpp.
References TSeparatorKit::getPart().
Referenced by DisplayResults(), and TAnalyzerKit().
TSeparatorKit * TAnalyzerKit::GetResultsList ()
Definition at line 191 of file TAnalyzerKit.cpp.
References TSeparatorKit::getPart().
Referenced by DisplayResults(), PrepareCompute(), RemoveResult(), and ResetValues().
void TAnalyzerKit::initClass () [static]
Sets up initialization for data common to all instances of this class, like submitting necessary information to the Coin type system.
Reimplemented from TSeparatorKit.
Definition at line 69 of file TAnalyzerKit.cpp.
Referenced by main().
bool TAnalyzerKit::IntersectP (const Ray & ray) const
void TAnalyzerKit::PrepareCompute (SceneModel * pModel)
Definition at line 230 of file TAnalyzerKit.cpp.
References TAnalyzerParameter::elemSize, TShape::GetBBox(), TSeparatorKit::getPart(), GetResultsList(), SceneModel::InsertCoinNode(), TAnalyzerResult::numRayIntersected, BBox::pMax, BBox::pMin, previousElemSize, previousSplit, RemoveResult(), TAnalyzerParameter::setParent(), TAnalyzerParameter::split, to_string(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by InstanceNode::PrepareAnalyze().
void TAnalyzerKit::RemoveResult (SceneModel * pModel)
Definition at line 210 of file TAnalyzerKit.cpp.
References TSeparatorKit::getPart(), GetResultsList(), previousElemSize, previousSplit, and SceneModel::RemoveCoinNode().
Referenced by PrepareCompute(), and UpdateSize().
void TAnalyzerKit::ResetValues ()
Definition at line 368 of file TAnalyzerKit.cpp.
References DisplayResults(), TSeparatorKit::getPart(), GetResultsList(), and TAnalyzerResultKit::ResetValues().
Referenced by InstanceNode::ResetAnalyzeValues().
TAnalyzerKit::SO_KIT_CATALOG_ENTRY_HEADER (levelList) [private]
TAnalyzerKit::SO_KIT_CATALOG_ENTRY_HEADER (parameter) [private]
TAnalyzerKit::SO_KIT_CATALOG_ENTRY_HEADER (result) [private]
TAnalyzerKit::SO_KIT_HEADER (TAnalyzerKit) [private]
void TAnalyzerKit::UpdateSize (SceneModel * pModel)
Definition at line 327 of file TAnalyzerKit.cpp.
References TAnalyzerParameter::elemSize, TSeparatorKit::getPart(), TCube::m_depth, TCube::m_height, TCube::m_width, previousElemSize, previousSplit, RemoveResult(), and TAnalyzerParameter::split.
Referenced by InstanceNode::UpdateAnalyzerSize().
Member Data Documentation
trt::TONATIUH_REAL TAnalyzerKit::previousElemSize [private]
Definition at line 95 of file TAnalyzerKit.h.
Referenced by PrepareCompute(), RemoveResult(), TAnalyzerKit(), and UpdateSize().
SoSFVec3s TAnalyzerKit::previousSplit [private]
Definition at line 94 of file TAnalyzerKit.h.
Referenced by PrepareCompute(), RemoveResult(), TAnalyzerKit(), and UpdateSize().
The documentation for this class was generated from the following files:
TAnalyzerKit.h
TAnalyzerKit.cpp