Tonatiuh: GraphicRootTracker Class Reference
http://tonatiuh.googlecode.com
GraphicRootTracker Class Reference
Public Member Functions
QString getIcon ()
GraphicRootTracker ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual ~GraphicRootTracker ()
Private Member Functions
SO_NODEENGINE_HEADER (GraphicRootTracker)
virtual void evaluate ()
Detailed Description
Definition at line 52 of file GraphicRootTracker.h.
Constructor & Destructor Documentation
GraphicRootTracker::GraphicRootTracker ()
Definition at line 66 of file GraphicRootTracker.cpp.
References TTracker::m_azimuth, TTracker::m_zenith, TTracker::outputCenter, TTracker::outputRotation, TTracker::outputScaleFactor, TTracker::outputScaleOrientation, and TTracker::outputTranslation.
GraphicRootTracker::~GraphicRootTracker () [protected, virtual]
Definition at line 84 of file GraphicRootTracker.cpp.
Member Function Documentation
void GraphicRootTracker::evaluate () [private, virtual]
Implements TTracker.
Definition at line 94 of file GraphicRootTracker.cpp.
References TTracker::GetAzimuth(), TTracker::GetZenith(), TTracker::IsConnected(), tgc::Pi, and TTracker::SetEngineOutputRotation().
QString GraphicRootTracker::getIcon () [virtual]
Implements TTracker.
Definition at line 88 of file GraphicRootTracker.cpp.
void GraphicRootTracker::initClass () [static]
Reimplemented from TTracker.
Definition at line 60 of file GraphicRootTracker.cpp.
Referenced by main().
GraphicRootTracker::SO_NODEENGINE_HEADER (GraphicRootTracker) [private]
The documentation for this class was generated from the following files:
GraphicRootTracker.h
GraphicRootTracker.cpp