Tonatiuh: PluginManager Class Reference
http://tonatiuh.googlecode.com
PluginManager Class Reference
PluginManager class manages plugin loading. PluginManager is used to load plugins, manage the list of loaded plugins.
Public Member Functions
PluginManager ()
~PluginManager ()
QVector< RandomDeviateFactory * > GetRandomDeviateFactories () const
QVector< TMaterialFactory * > GetMaterialFactories () const
QVector< TPhotonMapFactory * > GetPhotonMapFactories () const
QVector< TShapeFactory * > GetShapeFactories () const
QVector< TSunShapeFactory * > GetSunShapeFactories () const
QVector< TTrackerFactory * > GetTrackerFactories () const
void LoadAvailablePlugins (QDir pluginsDirectory)
Private Member Functions
void AddFilesToList (QDir directory, QStringList &filesList)
void BuildFileList (QDir directory, QStringList &filesList)
void LoadAvailablePlugins ()
void LoadMaterialPlugin (QObject *plugin)
void LoadPhotonMapPlugin (QObject *plugin)
void LoadRandomDeviatePlugin (QObject *plugin)
void LoadShapePlugin (QObject *plugin)
void LoadSunshapePlugin (QObject *plugin)
void LoadTrackerPlugin (QObject *plugin)
void LoadTonatiuhPlugin (const QString &fileName)
bool ValidDirectoryName (QString &directoryName)
Private Attributes
QVector< RandomDeviateFactory * > m_RandomDeviateFactoryList
QVector< TMaterialFactory * > m_materialFactoryList
QVector< TPhotonMapFactory * > m_photonmapFactoryList
QVector< TShapeFactory * > m_shapeFactoryList
QVector< TSunShapeFactory * > m_sunshapeFactoryList
QVector< TTrackerFactory * > m_trackerFactoryList
Detailed Description
PluginManager class manages plugin loading. PluginManager is used to load plugins, manage the list of loaded plugins.
Definition at line 55 of file PluginManager.h.
Constructor & Destructor Documentation
PluginManager::PluginManager ()
Creates a new PluginManager object.
Definition at line 62 of file PluginManager.cpp.
PluginManager::~PluginManager ()
Destroyes PluginManager object.
Definition at line 75 of file PluginManager.cpp.
Member Function Documentation
void PluginManager::AddFilesToList (QDir directory, QStringList & filesList) [private]
Appends to fileList directory files.
Definition at line 143 of file PluginManager.cpp.
Referenced by BuildFileList().
void PluginManager::BuildFileList (QDir directory, QStringList & filesList) [private]
Creates a list with the files al files in the defined directory and its subdirectories.
Definition at line 157 of file PluginManager.cpp.
References AddFilesToList(), and ValidDirectoryName().
Referenced by LoadAvailablePlugins().
QVector< TMaterialFactory * > PluginManager::GetMaterialFactories () const
Returns available random deviates plugins factory list.
Definition at line 91 of file PluginManager.cpp.
References m_materialFactoryList.
Referenced by MainWindow::CreateMaterial(), and MainWindow::SetupActionsInsertMaterial().
QVector< TPhotonMapFactory * > PluginManager::GetPhotonMapFactories () const
Returns available photonmap plugins factory list.
Definition at line 99 of file PluginManager.cpp.
References m_photonmapFactoryList.
Referenced by MainWindow::on_actionOpenScriptEditor_triggered(), MainWindow::ReadyForRaytracing(), MainWindow::SetPhotonMapType(), and MainWindow::ShowRayTracerOptionsDialog().
QVector< RandomDeviateFactory * > PluginManager::GetRandomDeviateFactories () const
Returns available random deviates plugins factory list.
Definition at line 83 of file PluginManager.cpp.
References m_RandomDeviateFactoryList.
Referenced by MainWindow::on_actionOpenScriptEditor_triggered(), MainWindow::ReadyForRaytracing(), and MainWindow::ShowRayTracerOptionsDialog().
QVector< TShapeFactory * > PluginManager::GetShapeFactories () const
Returns available shape plugins factory list.
Definition at line 107 of file PluginManager.cpp.
References m_shapeFactoryList.
Referenced by MainWindow::CreateShape(), MainWindow::DefineSunLight(), and MainWindow::SetupActionsInsertShape().
QVector< TSunShapeFactory * > PluginManager::GetSunShapeFactories () const
Returns available sunshape plugins factory list.
Definition at line 115 of file PluginManager.cpp.
References m_sunshapeFactoryList.
Referenced by MainWindow::DefineSunLight().
QVector< TTrackerFactory * > PluginManager::GetTrackerFactories () const
Returns available tracker plugins factory list.
Definition at line 124 of file PluginManager.cpp.
References m_trackerFactoryList.
Referenced by MainWindow::CreateTracker(), and MainWindow::SetupActionsInsertTracker().
void PluginManager::LoadAvailablePlugins () [private]
void PluginManager::LoadAvailablePlugins (QDir pluginsDirectory)
Loads all the valid plugins from "plugins" subdirecotry of the directory in which the running version of Tonatiuh is located.
Definition at line 133 of file PluginManager.cpp.
References BuildFileList(), and LoadTonatiuhPlugin().
Referenced by MainWindow::SetupPluginsManager().
void PluginManager::LoadMaterialPlugin (QObject * plugin) [private]
Definition at line 173 of file PluginManager.cpp.
References TMaterialFactory::CreateTMaterial(), m_materialFactoryList, and tgf::SevereError().
Referenced by LoadTonatiuhPlugin().
void PluginManager::LoadPhotonMapPlugin (QObject * plugin) [private]
Definition at line 182 of file PluginManager.cpp.
References m_photonmapFactoryList, and tgf::SevereError().
Referenced by LoadTonatiuhPlugin().
void PluginManager::LoadRandomDeviatePlugin (QObject * plugin) [private]
Loads the plugin as RandomDeviatePlugin type.
Definition at line 192 of file PluginManager.cpp.
References m_RandomDeviateFactoryList.
Referenced by LoadTonatiuhPlugin().
void PluginManager::LoadShapePlugin (QObject * plugin) [private]
Definition at line 199 of file PluginManager.cpp.
References TShapeFactory::CreateTShape(), m_shapeFactoryList, and tgf::SevereError().
Referenced by LoadTonatiuhPlugin().
void PluginManager::LoadSunshapePlugin (QObject * plugin) [private]
Definition at line 208 of file PluginManager.cpp.
References TSunShapeFactory::CreateTSunShape(), m_sunshapeFactoryList, and tgf::SevereError().
Referenced by LoadTonatiuhPlugin().
void PluginManager::LoadTonatiuhPlugin (const QString & fileName) [private]
Loads the plugin is defined in fileName, if it is a valid plugin.
Definition at line 228 of file PluginManager.cpp.
References LoadMaterialPlugin(), LoadPhotonMapPlugin(), LoadRandomDeviatePlugin(), LoadShapePlugin(), LoadSunshapePlugin(), and LoadTrackerPlugin().
Referenced by LoadAvailablePlugins().
void PluginManager::LoadTrackerPlugin (QObject * plugin) [private]
Definition at line 216 of file PluginManager.cpp.
References TTrackerFactory::CreateTTracker(), m_trackerFactoryList, and tgf::SevereError().
Referenced by LoadTonatiuhPlugin().
bool PluginManager::ValidDirectoryName (QString & directoryName) [private]
Checks if the directoryName is a valid directory name. '.' and '..' are not valid names.
Definition at line 247 of file PluginManager.cpp.
Referenced by BuildFileList().
Member Data Documentation
QVector< TMaterialFactory* > PluginManager::m_materialFactoryList [private]
Definition at line 85 of file PluginManager.h.
Referenced by GetMaterialFactories(), and LoadMaterialPlugin().
QVector< TPhotonMapFactory* > PluginManager::m_photonmapFactoryList [private]
Definition at line 86 of file PluginManager.h.
Referenced by GetPhotonMapFactories(), and LoadPhotonMapPlugin().
QVector< RandomDeviateFactory* > PluginManager::m_RandomDeviateFactoryList [private]
Definition at line 84 of file PluginManager.h.
Referenced by GetRandomDeviateFactories(), and LoadRandomDeviatePlugin().
QVector< TShapeFactory* > PluginManager::m_shapeFactoryList [private]
Definition at line 87 of file PluginManager.h.
Referenced by GetShapeFactories(), and LoadShapePlugin().
QVector< TSunShapeFactory* > PluginManager::m_sunshapeFactoryList [private]
Definition at line 88 of file PluginManager.h.
Referenced by GetSunShapeFactories(), and LoadSunshapePlugin().
QVector< TTrackerFactory* > PluginManager::m_trackerFactoryList [private]
Definition at line 89 of file PluginManager.h.
Referenced by GetTrackerFactories(), and LoadTrackerPlugin().
The documentation for this class was generated from the following files:
PluginManager.h
PluginManager.cpp