ExportDialog Class Reference
http://tonatiuh.googlecode.com
ExportDialog Class Reference
ExportDialog class is the dialog to define the photon map export mode.
Public Slots
void accept ()
Public Member Functions
ExportDialog (SceneModel &sceneModel, QString previousSurfaceUrl=0, bool previusInGlobal=true, QString previousFile=0, QWidget *parent=0)
~ExportDialog ()
bool ExportAllPhotonMap () const
bool ExportPhotonsInGlobal () const
QString GetExportFileName () const
QString GetSelectedSurface () const
Private Slots
void SetExportAllPhotons (bool allPhotos)
void SetExportSurfacePhotons (bool surfacePhotos)
void SelectFile ()
Private Attributes
SceneModel * m_exportSceneModel
QItemSelectionModel * m_exportSelectionModel
Detailed Description
ExportDialog class is the dialog to define the photon map export mode.
ExportDialog sets the photons to export, the coordinates system and the file to save selected information.
Definition at line 52 of file ExportDialog.h.
Constructor & Destructor Documentation
ExportDialog::ExportDialog (SceneModel & sceneModel, QString previousSurfaceUrl = 0, bool previusInGlobal = true, QString previousFile = 0, QWidget * parent = 0)
Creates a dialog to define export parameters. The dialog need sceneModel to allow user to select a surface to export. Sets export mode to export all photos if previousSurfaceUrl is empty. Otherwise, sets to surface export mode. Sets global coordinate system if previusInGlobal is true. Otherwise, sets to local coordinate system. The current export file value takes the previousFile name. The file previousFile is the last file uses to export a photon map.
Definition at line 53 of file ExportDialog.cpp.
References Ui_ExportDialog::allMapRadio, Ui_ExportDialog::fileNameEdit, Ui_ExportDialog::globalCoordinatesRadio, SceneModel::IndexFromNodeUrl(), Ui_ExportDialog::localCoordinates, m_exportSceneModel, m_exportSelectionModel, Ui_ExportDialog::modelView, Ui_ExportDialog::selectFile, SelectFile(), SetExportAllPhotons(), SetExportSurfacePhotons(), Ui_ExportDialog::setupUi(), and Ui_ExportDialog::surfaceMapRadio.
ExportDialog::~ExportDialog ()
Destroys the file dialog.
Definition at line 94 of file ExportDialog.cpp.
References m_exportSelectionModel.
Member Function Documentation
void ExportDialog::accept () [slot]
Hides the modal dialog and sets the result code to Accepted.
Definition at line 149 of file ExportDialog.cpp.
References Ui_ExportDialog::fileNameEdit, InstanceNode::GetNode(), m_exportSceneModel, m_exportSelectionModel, SceneModel::NodeFromIndex(), and Ui_ExportDialog::surfaceMapRadio.
bool ExportDialog::ExportAllPhotonMap () const
Returns true if the option export all photon map option is selected. Otherwise, returns false.
Definition at line 102 of file ExportDialog.cpp.
References Ui_ExportDialog::allMapRadio.
Referenced by MainWindow::ExportPhotonMap().
bool ExportDialog::ExportPhotonsInGlobal () const
Return true if the global coordinates system is selected. Otherwise, returns false.
Definition at line 111 of file ExportDialog.cpp.
References Ui_ExportDialog::globalCoordinatesRadio.
Referenced by MainWindow::ExportPhotonMap().
QString ExportDialog::GetExportFileName () const
Returns id to indicate selected photon map photons.
If all photon map is selected, returns 0. To surface photon map returns 1.
See also:
GetSelectedSurface
Definition at line 124 of file ExportDialog.cpp.
References Ui_ExportDialog::fileNameEdit.
Referenced by MainWindow::ExportPhotonMap().
QString ExportDialog::GetSelectedSurface () const
Return selected surface node url.
Returns an empty string if there is not selection or selected node is not surface node.
Definition at line 134 of file ExportDialog.cpp.
References InstanceNode::GetNode(), InstanceNode::GetNodeURL(), m_exportSceneModel, m_exportSelectionModel, SceneModel::NodeFromIndex(), and Ui_ExportDialog::surfaceMapRadio.
Referenced by MainWindow::ExportPhotonMap().
void ExportDialog::SelectFile () [private, slot]
Opens a dialog to select a file as the the file to save the export information.
fileNameEdit line will show the selected file path.
Definition at line 201 of file ExportDialog.cpp.
References Ui_ExportDialog::fileNameEdit.
Referenced by ExportDialog().
void ExportDialog::SetExportAllPhotons (bool allPhotos) [private, slot]
If allPhotos is true set export mode to export all photon map. Otherwise sets to export all photons if surface photons is not checked.
Definition at line 178 of file ExportDialog.cpp.
References Ui_ExportDialog::allMapRadio, and Ui_ExportDialog::surfaceMapRadio.
Referenced by ExportDialog().
void ExportDialog::SetExportSurfacePhotons (bool surfacePhotos) [private, slot]
If allPhotos is true set export mode to export surface photons. Otherwise sets to export surface photons if all photons is not checked.
Definition at line 189 of file ExportDialog.cpp.
References Ui_ExportDialog::allMapRadio, and Ui_ExportDialog::surfaceMapRadio.
Referenced by ExportDialog().
Member Data Documentation
SceneModel* ExportDialog::m_exportSceneModel [private]
Definition at line 75 of file ExportDialog.h.
Referenced by accept(), ExportDialog(), and GetSelectedSurface().
QItemSelectionModel* ExportDialog::m_exportSelectionModel [private]
Definition at line 76 of file ExportDialog.h.
Referenced by accept(), ExportDialog(), GetSelectedSurface(), and ~ExportDialog().
The documentation for this class was generated from the following files:
ExportDialog.h
ExportDialog.cpp