Tonatiuh: FieldContainerWidget Class Reference
http://tonatiuh.googlecode.com
FieldContainerWidget Class Reference
Signals
void valueModificated (SoNode *nodeContainer, QString parameterName, QString newValue)
Public Member Functions
FieldContainerWidget (QWidget *parent=0)
FieldContainerWidget (SoNode *fieldContainer, QString containerName, QWidget *parent=0)
~FieldContainerWidget ()
void SetContainer (SoNode *fieldContainer, QString containerName)
void SetEditable (bool editable)
Protected Slots
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Private Member Functions
void ReadFields ()
Private Attributes
QString m_containerName
QModelIndex m_currentIndex
ParametersDelegate * m_pDelegate
SoNode * m_pFieldContainer
ParametersModel * m_pModel
Detailed Description
Definition at line 52 of file FieldContainerWidget.h.
Constructor & Destructor Documentation
FieldContainerWidget::FieldContainerWidget (QWidget * parent = 0)
Creates an empty widget.
Definition at line 62 of file FieldContainerWidget.cpp.
References m_pDelegate, m_pModel, and ParametersModel::SetEditable().
FieldContainerWidget::FieldContainerWidget (SoNode * fieldContainer, QString containerName, QWidget * parent = 0)
Creates a new FieldContainerWidget for the parameters in the fieldContainer with parent parent.
The container name is containerName.
Definition at line 86 of file FieldContainerWidget.cpp.
References m_pDelegate, m_pFieldContainer, m_pModel, ReadFields(), and ParametersModel::SetEditable().
FieldContainerWidget::~FieldContainerWidget ()
Destroys the FieldContainerWidget object.
Definition at line 111 of file FieldContainerWidget.cpp.
References m_pDelegate, and m_pModel.
Member Function Documentation
void FieldContainerWidget::closeEditor (QWidget * editor, QAbstractItemDelegate::EndEditHint hint) [protected, slot]
Definition at line 149 of file FieldContainerWidget.cpp.
References ParametersItem::GetField(), m_currentIndex, m_pFieldContainer, m_pModel, ParametersModel::ModelItem(), and valueModificated().
void FieldContainerWidget::currentChanged (const QModelIndex & current, const QModelIndex & previous) [protected, slot]
Sets current as the view current element index.
Definition at line 144 of file FieldContainerWidget.cpp.
References m_currentIndex.
void FieldContainerWidget::ReadFields () [private]
Reads container parameters and for each parameters adds its name and value to de widget.
Definition at line 175 of file FieldContainerWidget.cpp.
References m_pFieldContainer, and m_pModel.
Referenced by FieldContainerWidget(), and SetContainer().
void FieldContainerWidget::SetContainer (SoNode * fieldContainer, QString containerName)
Sets fieldContainer as widget container and containerName as its containerName name.
Definition at line 121 of file FieldContainerWidget.cpp.
References m_containerName, m_pFieldContainer, m_pModel, and ReadFields().
void FieldContainerWidget::SetEditable (bool editable)
Sets if the parameters values can be modified.
Definition at line 136 of file FieldContainerWidget.cpp.
References m_pModel, and ParametersModel::SetEditable().
void FieldContainerWidget::valueModificated (SoNode * nodeContainer, QString parameterName, QString newValue) [signal]
Referenced by closeEditor().
Member Data Documentation
QString FieldContainerWidget::m_containerName [private]
Definition at line 74 of file FieldContainerWidget.h.
Referenced by SetContainer().
QModelIndex FieldContainerWidget::m_currentIndex [private]
Definition at line 75 of file FieldContainerWidget.h.
Referenced by closeEditor(), and currentChanged().
ParametersDelegate* FieldContainerWidget::m_pDelegate [private]
Definition at line 76 of file FieldContainerWidget.h.
Referenced by FieldContainerWidget(), and ~FieldContainerWidget().
SoNode* FieldContainerWidget::m_pFieldContainer [private]
Definition at line 77 of file FieldContainerWidget.h.
Referenced by closeEditor(), FieldContainerWidget(), ReadFields(), and SetContainer().
ParametersModel* FieldContainerWidget::m_pModel [private]
Definition at line 78 of file FieldContainerWidget.h.
Referenced by closeEditor(), FieldContainerWidget(), ReadFields(), SetContainer(), SetEditable(), and ~FieldContainerWidget().
The documentation for this class was generated from the following files:
FieldContainerWidget.h
FieldContainerWidget.cpp