Tonatiuh: TSeparatorKit Class Reference
http://tonatiuh.googlecode.com
TSeparatorKit Class Reference
The TSeparatorKit class provides a set of others TSeparatorKit and TShapeKit nodes with a transform and a tracker.
Public Member Functions
TSeparatorKit ()
virtual SbBool setPart (const SbName &partname, SoNode *from)
virtual SoNode * getPart (const SbName &partname, SbBool makeifneeded)
QString getIcon ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual ~TSeparatorKit ()
Private Types
typedef SoSeparatorKit inherited
Private Member Functions
SO_KIT_HEADER (TSeparatorKit)
SO_KIT_CATALOG_ENTRY_HEADER (tracker)
Detailed Description
The TSeparatorKit class provides a set of others TSeparatorKit and TShapeKit nodes with a transform and a tracker.
The TSeparatorKit structure:
  CLASS TSeparatorKitt
  -->"this"
        "callbackList"
  -->   "topSeparator"
  -->      "pickStyle"
  -->      "appearance"
  -->      "units"
  -->      "transform"
  -->      "texture2Transform"
  -->      "childList"
  -->"tracker"
Detailed information on catalog parts:
  CLASS SoSeparatorKit
  PVT   "this",  SoSeparatorKit  ---
        "callbackList",  SoNodeKitListPart [ SoCallback, SoEventCallback ]
  PVT   "topSeparator",  SoSeparator  ---
        "pickStyle",  SoPickStyle  ---
        "appearance",  SoAppearanceKit  ---
        "units",  SoUnits  ---
        "transform",  SoTransform  ---
        "texture2Transform",  SoTexture2Transform  ---
        "childList",  SoNodeKitListPart [ SoShapeKit, SoSeparatorKit ]
        "tracker", TTacker  --- , (default type = TDefaultTracker)
Definition at line 83 of file TSeparatorKit.h.
Member Typedef Documentation
typedef SoSeparatorKit TSeparatorKit::inherited [private]
Reimplemented in TAnalyzerKit.
Definition at line 85 of file TSeparatorKit.h.
Constructor & Destructor Documentation
TSeparatorKit::TSeparatorKit ()
Creates a new TSeparatorKit node.
Definition at line 61 of file TSeparatorKit.cpp.
References setPart().
Referenced by TAnalyzerKit::TAnalyzerKit().
TSeparatorKit::~TSeparatorKit () [protected, virtual]
TSeparatorKit destructor.
Definition at line 76 of file TSeparatorKit.cpp.
Member Function Documentation
QString TSeparatorKit::getIcon ()
Returns the icon that represents TSeparatorKit nodes.
Reimplemented in TAnalyzerKit.
Definition at line 125 of file TSeparatorKit.cpp.
Referenced by SceneModel::data().
SoNode * TSeparatorKit::getPart (const SbName & partname, SbBool makeifneeded) [virtual]
Returns a pointer to the node part with partname.
Definition at line 83 of file TSeparatorKit.cpp.
Referenced by CmdDeleteTracker::CmdDeleteTracker(), SceneModel::DeleteInstanceTree(), TAnalyzerKit::DisplayResults(), TAnalyzerKit::FinalizeCompute(), TAnalyzerKit::GetLevelList(), TAnalyzerKit::GetResultsList(), TSceneKit::GetSoPath(), SceneModel::Paste(), TAnalyzerKit::PrepareCompute(), CmdDeleteTracker::redo(), TAnalyzerKit::RemoveResult(), TAnalyzerKit::ResetValues(), SceneModel::SetConcentrator(), setPart(), MainWindow::SetValue(), MainWindow::ShowMenu(), TAnalyzerKit::TAnalyzerKit(), CmdDeleteTracker::undo(), and TAnalyzerKit::UpdateSize().
void TSeparatorKit::initClass () [static]
Does initialization common for all objects of the TSeparatorKit class. This includes setting up the type system, among other things.
Reimplemented in TAnalyzerKit.
Definition at line 53 of file TSeparatorKit.cpp.
Referenced by main().
SbBool TSeparatorKit::setPart (const SbName & partname, SoNode * from) [virtual]
Set from node as partname node.
Definition at line 91 of file TSeparatorKit.cpp.
References TTracker::ConnectParentTranform(), and getPart().
Referenced by SceneModel::SetConcentrator(), and TSeparatorKit().
TSeparatorKit::SO_KIT_CATALOG_ENTRY_HEADER (tracker) [private]
TSeparatorKit::SO_KIT_HEADER (TSeparatorKit) [private]
The documentation for this class was generated from the following files:
TSeparatorKit.h
TSeparatorKit.cpp