Tonatiuh: ParametersItem Class Reference
http://tonatiuh.googlecode.com
ParametersItem Class Reference
Public Member Functions
ParametersItem (QString text, bool editable, SoField *field)
~ParametersItem ()
SoField * GetField () const
QVariant data (int role=Qt::UserRole+1) const
void setData (const QVariant &value, int role=Qt::UserRole+1)
QString text () const
Private Attributes
SoField * m_pField
SoFieldSensor * m_pFieldSensor
QString m_text
Detailed Description
Definition at line 49 of file ParametersItem.h.
Constructor & Destructor Documentation
ParametersItem::ParametersItem (QString text, bool editable, SoField * field)
Definition at line 55 of file ParametersItem.cpp.
References m_pField, m_pFieldSensor, and updateItem().
ParametersItem::~ParametersItem ()
Definition at line 67 of file ParametersItem.cpp.
References m_pFieldSensor.
Member Function Documentation
QVariant ParametersItem::data (int role = Qt::UserRole + 1) const
Definition at line 72 of file ParametersItem.cpp.
References m_pField, and m_text.
Referenced by ParametersModel::data(), and updateItem().
SoField* ParametersItem::GetField () const [inline]
Definition at line 56 of file ParametersItem.h.
References m_pField.
Referenced by FieldContainerWidget::closeEditor(), ParametersDelegate::createEditor(), and ParametersDelegate::setEditorData().
void ParametersItem::setData (const QVariant & value, int role = Qt::UserRole + 1)
Definition at line 86 of file ParametersItem.cpp.
References m_pField, and m_text.
Referenced by ParametersModel::setData(), and updateItem().
QString ParametersItem::text () const
Definition at line 100 of file ParametersItem.cpp.
References m_text.
Member Data Documentation
SoField* ParametersItem::m_pField [private]
Definition at line 63 of file ParametersItem.h.
Referenced by data(), GetField(), ParametersItem(), and setData().
SoFieldSensor* ParametersItem::m_pFieldSensor [private]
Definition at line 64 of file ParametersItem.h.
Referenced by ParametersItem(), and ~ParametersItem().
QString ParametersItem::m_text [private]
Definition at line 65 of file ParametersItem.h.
Referenced by data(), setData(), and text().
The documentation for this class was generated from the following files:
ParametersItem.h
ParametersItem.cpp