TDefaultTracker Class Reference
http://tonatiuh.googlecode.com
TDefaultTracker Class Reference
Public Member Functions
QString getIcon ()
TDefaultTracker ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual ~TDefaultTracker ()
Private Member Functions
SO_NODEENGINE_HEADER (TDefaultTracker)
virtual void evaluate ()
Detailed Description
Definition at line 49 of file TDefaultTracker.h.
Constructor & Destructor Documentation
TDefaultTracker::TDefaultTracker ()
TDefaultTracker constructor
Definition at line 63 of file TDefaultTracker.cpp.
References TTracker::m_azimuth, TTracker::m_zenith, TTracker::outputCenter, TTracker::outputRotation, TTracker::outputScaleFactor, TTracker::outputScaleOrientation, TTracker::outputTranslation, and tgc::Pi.
TDefaultTracker::~TDefaultTracker () [protected, virtual]
TDefaultTracker destructor
Definition at line 82 of file TDefaultTracker.cpp.
Member Function Documentation
void TDefaultTracker::evaluate () [private, virtual]
Computes the rotation ouput.
Implements TTracker.
Definition at line 98 of file TDefaultTracker.cpp.
References TTracker::IsConnected(), and TTracker::SetEngineOutputIdentity().
QString TDefaultTracker::getIcon () [virtual]
Returns the icon that represents the TDefaultTracker.
Implements TTracker.
Definition at line 90 of file TDefaultTracker.cpp.
void TDefaultTracker::initClass () [static]
Sets up initialization for data common to all instances of this class, like submitting necessary information to the Coin type system.
Reimplemented from TTracker.
Definition at line 54 of file TDefaultTracker.cpp.
Referenced by main().
TDefaultTracker::SO_NODEENGINE_HEADER (TDefaultTracker) [private]
The documentation for this class was generated from the following files:
TDefaultTracker.h
TDefaultTracker.cpp