Tonatiuh: CmdChangeNodeName Class Reference
http://tonatiuh.googlecode.com
CmdChangeNodeName Class Reference
CmdChangeNodeName is the command that represents a node name change.
Public Member Functions
CmdChangeNodeName (const QModelIndex &index, QString newName, SceneModel *model, QUndoCommand *parent=0)
~CmdChangeNodeName ()
virtual void undo ()
virtual void redo ()
Private Attributes
QString m_newName
QString m_previousName
SoNode * m_pNode
SceneModel * m_pModel
Detailed Description
CmdChangeNodeName is the command that represents a node name change.
CmdChangeNodeName represents a change in a node from the scene. The node can be any one.
Definition at line 49 of file CmdChangeNodeName.h.
Constructor & Destructor Documentation
CmdChangeNodeName::CmdChangeNodeName (const QModelIndex & index, QString newName, SceneModel * model, QUndoCommand * parent = 0)
Creates a new CmdChangeNodeName command.
Definition at line 60 of file CmdChangeNodeName.cpp.
References InstanceNode::GetNode(), m_pModel, m_pNode, m_previousName, SceneModel::NodeFromIndex(), and tgf::SevereError().
CmdChangeNodeName::~CmdChangeNodeName ()
Destroys command object.
Definition at line 75 of file CmdChangeNodeName.cpp.
Member Function Documentation
void CmdChangeNodeName::redo () [virtual]
Changes the node name to the name defined in the command constructor.
Definition at line 90 of file CmdChangeNodeName.cpp.
References m_newName, m_pModel, m_pNode, and SceneModel::SetNodeName().
void CmdChangeNodeName::undo () [virtual]
Changes the node name to the name that the node takes before the command is applied.
Definition at line 82 of file CmdChangeNodeName.cpp.
References m_pModel, m_pNode, m_previousName, and SceneModel::SetNodeName().
Member Data Documentation
QString CmdChangeNodeName::m_newName [private]
New node name
Definition at line 59 of file CmdChangeNodeName.h.
Referenced by redo().
SceneModel* CmdChangeNodeName::m_pModel [private]
The scene
Definition at line 62 of file CmdChangeNodeName.h.
Referenced by CmdChangeNodeName(), redo(), and undo().
SoNode* CmdChangeNodeName::m_pNode [private]
Changed node
Definition at line 61 of file CmdChangeNodeName.h.
Referenced by CmdChangeNodeName(), redo(), and undo().
QString CmdChangeNodeName::m_previousName [private]
Previous node name
Definition at line 60 of file CmdChangeNodeName.h.
Referenced by CmdChangeNodeName(), and undo().
The documentation for this class was generated from the following files:
CmdChangeNodeName.h
CmdChangeNodeName.cpp