Tonatiuh: RayTraceDialog Class Reference
http://tonatiuh.googlecode.com
RayTraceDialog Class Reference
RayTraceDialog class is the dialog to set ray trace options.
Public Slots
void applyChanges (QAbstractButton *button)
void saveChanges ()
Public Member Functions
RayTraceDialog (QWidget *parent=0, Qt::WindowFlags f=0)
RayTraceDialog (int numRays, QVector< RandomDeviateFactory * > randomFactoryList, double fraction, bool drawPhotons, QVector< TPhotonMapFactory * > photonMapFactoryList, int selectedRandomFactory=0, int selectedPhotonMapFactory=0, bool increasePhotonMap=false, QWidget *parent=0, Qt::WindowFlags f=0)
~RayTraceDialog ()
int GetNumRays () const
int GetRandomDeviateFactoryIndex () const
double GetRaysFactionToDraw () const
bool DrawPhotons () const
int GetPhotonMapFactoryIndex () const
bool IncreasePhotonMap () const
Private Attributes
int m_numRays
int m_selectedRandomFactory
double m_fraction
bool m_drawPhotons
int m_selectedPhotonMapFactory
bool m_increasePhotonMap
Detailed Description
RayTraceDialog class is the dialog to set ray trace options.
RayTraceDialog allow to the user modify ray tracer default options. The user can modify the number of ray to trace, draw and photon map options.
Definition at line 57 of file RayTraceDialog.h.
Constructor & Destructor Documentation
RayTraceDialog::RayTraceDialog (QWidget * parent = 0, Qt::WindowFlags f = 0)
Creates a dialog to ray tracer options with the given parent and f flags.
The variables take the default values.
Definition at line 52 of file RayTraceDialog.cpp.
References applyChanges(), Ui_RayTraceDialog::buttonBox, saveChanges(), and Ui_RayTraceDialog::setupUi().
RayTraceDialog::RayTraceDialog (int numRays, QVector< RandomDeviateFactory * > randomFactoryList, double fraction, bool drawPhotons, QVector< TPhotonMapFactory * > photonMapFactoryList, int selectedRandomFactory = 0, int selectedPhotonMapFactory = 0, bool increasePhotonMap = false, QWidget * parent = 0, Qt::WindowFlags f = 0)
Creates a dialog to ray tracer options with the given parent and f flags.
The variables take the values specified by numRats, faction, drawPhotons and increasePhotonMap.
Definition at line 65 of file RayTraceDialog.cpp.
References applyChanges(), Ui_RayTraceDialog::buttonBox, Ui_RayTraceDialog::drawSpin, Ui_RayTraceDialog::increaseMapRadio, m_drawPhotons, m_fraction, m_increasePhotonMap, m_numRays, m_selectedPhotonMapFactory, m_selectedRandomFactory, Ui_RayTraceDialog::newMapRadio, Ui_RayTraceDialog::photonmapTypeCombo, Ui_RayTraceDialog::photonsCheck, Ui_RayTraceDialog::randomCombo, Ui_RayTraceDialog::raysSpinBox, saveChanges(), and Ui_RayTraceDialog::setupUi().
RayTraceDialog::~RayTraceDialog ()
Destroys the RayTraceDialog object.
Definition at line 100 of file RayTraceDialog.cpp.
Member Function Documentation
void RayTraceDialog::applyChanges (QAbstractButton * button) [slot]
If the applyChanges button is clicked the dialog values are saved.
Definition at line 156 of file RayTraceDialog.cpp.
References Ui_RayTraceDialog::buttonBox, and saveChanges().
Referenced by RayTraceDialog().
bool RayTraceDialog::DrawPhotons () const
Returns if the photons are going to be represented.
Definition at line 132 of file RayTraceDialog.cpp.
References m_drawPhotons.
Referenced by MainWindow::ShowRayTracerOptionsDialog().
int RayTraceDialog::GetNumRays () const
Returns the number of rays to trace.
Definition at line 107 of file RayTraceDialog.cpp.
References m_numRays.
Referenced by MainWindow::ShowRayTracerOptionsDialog().
int RayTraceDialog::GetPhotonMapFactoryIndex () const
Returns the factory to create a new photon map.
Definition at line 140 of file RayTraceDialog.cpp.
References m_selectedPhotonMapFactory.
Referenced by MainWindow::ShowRayTracerOptionsDialog().
int RayTraceDialog::GetRandomDeviateFactoryIndex () const
Returns the factory to create a new random generator.
Definition at line 123 of file RayTraceDialog.cpp.
References m_selectedRandomFactory.
Referenced by MainWindow::ShowRayTracerOptionsDialog().
double RayTraceDialog::GetRaysFactionToDraw () const
Returns the fraction of trace rays to draw.
Definition at line 115 of file RayTraceDialog.cpp.
References m_fraction.
Referenced by MainWindow::ShowRayTracerOptionsDialog().
bool RayTraceDialog::IncreasePhotonMap () const
Returns if the the tracer use the same photon map used in the previous tracer process.
Definition at line 148 of file RayTraceDialog.cpp.
References m_increasePhotonMap.
Referenced by MainWindow::ShowRayTracerOptionsDialog().
void RayTraceDialog::saveChanges () [slot]
Saves the values of the dialog.
Definition at line 164 of file RayTraceDialog.cpp.
References Ui_RayTraceDialog::drawSpin, m_drawPhotons, m_fraction, m_increasePhotonMap, m_numRays, m_selectedPhotonMapFactory, m_selectedRandomFactory, Ui_RayTraceDialog::newMapRadio, Ui_RayTraceDialog::photonmapTypeCombo, Ui_RayTraceDialog::photonsCheck, Ui_RayTraceDialog::randomCombo, and Ui_RayTraceDialog::raysSpinBox.
Referenced by applyChanges(), and RayTraceDialog().
Member Data Documentation
bool RayTraceDialog::m_drawPhotons [private]
This property holds whether photons are going to be drawn.
Definition at line 88 of file RayTraceDialog.h.
Referenced by DrawPhotons(), RayTraceDialog(), and saveChanges().
double RayTraceDialog::m_fraction [private]
Faction of traced rays to draw.
Definition at line 87 of file RayTraceDialog.h.
Referenced by GetRaysFactionToDraw(), RayTraceDialog(), and saveChanges().
bool RayTraceDialog::m_increasePhotonMap [private]
This property holds whether traced phtons are going to added to the old photon map.
Definition at line 91 of file RayTraceDialog.h.
Referenced by IncreasePhotonMap(), RayTraceDialog(), and saveChanges().
int RayTraceDialog::m_numRays [private]
Number of rays to trace.
Definition at line 84 of file RayTraceDialog.h.
Referenced by GetNumRays(), RayTraceDialog(), and saveChanges().
int RayTraceDialog::m_selectedPhotonMapFactory [private]
The index of factory selected from TPhotonMapFactory list.
Definition at line 90 of file RayTraceDialog.h.
Referenced by GetPhotonMapFactoryIndex(), RayTraceDialog(), and saveChanges().
int RayTraceDialog::m_selectedRandomFactory [private]
The index of factory selected from TPhotonMapFactory list.
Definition at line 85 of file RayTraceDialog.h.
Referenced by GetRandomDeviateFactoryIndex(), RayTraceDialog(), and saveChanges().
The documentation for this class was generated from the following files:
RayTraceDialog.h
RayTraceDialog.cpp