Tonatiuh: Transform Class Reference
http://tonatiuh.googlecode.com
Transform Class Reference
Public Member Functions
Transform ()
Transform (double mat[4][4])
Transform (const Ptr< Matrix4x4 > &mdir)
Transform (const Ptr< Matrix4x4 > &mdir, const Ptr< Matrix4x4 > &minv)
Transform (double t00, double t01, double t02, double t03, double t10, double t11, double t12, double t13, double t20, double t21, double t22, double t23, double t30, double t31, double t32, double t33)
Point3D operator() (const Point3D &point) const
void operator() (const Point3D &point, Point3D &transformedPoint) const
Vector3D operator() (const Vector3D &vector) const
void operator() (const Vector3D &vector, Vector3D &transformedVector) const
NormalVector operator() (const NormalVector &normal) const
void operator() (const NormalVector &normal, NormalVector &transformedNormal) const
Ray operator() (const Ray &ray) const
void operator() (const Ray &ray, Ray &transformedRay) const
BBox operator() (const BBox &bbox) const
void operator() (const BBox &bbox, BBox &transformedBbox) const
Transform operator* (const Transform &rhs) const
bool operator== (const Transform &mat) const
Ptr< Matrix4x4 > GetMatrix () const
Transform Transpose () const
Transform GetInverse () const
bool SwapsHandedness () const
Vector3D multVecMatrix (const Vector3D &src) const
Vector3D multDirMatrix (const Vector3D &src) const
Private Attributes
Ptr< Matrix4x4 > m_mdir
Ptr< Matrix4x4 > m_minv
Detailed Description
Definition at line 54 of file Transform.h.
Constructor & Destructor Documentation
Transform::Transform ()
Definition at line 46 of file Transform.cpp.
Referenced by GetInverse(), operator*(), and Transpose().
Transform::Transform (double mat[4][4])
Definition at line 52 of file Transform.cpp.
References m_mdir, and m_minv.
Transform::Transform (const Ptr< Matrix4x4 > & mdir)
Definition at line 61 of file Transform.cpp.
References m_mdir, and m_minv.
Transform::Transform (const Ptr< Matrix4x4 > & mdir, const Ptr< Matrix4x4 > & minv)
Definition at line 67 of file Transform.cpp.
Transform::Transform (double t00, double t01, double t02, double t03, double t10, double t11, double t12, double t13, double t20, double t21, double t22, double t23, double t30, double t31, double t32, double t33)
Definition at line 73 of file Transform.cpp.
References m_mdir, and m_minv.
Member Function Documentation
Transform Transform::GetInverse () const
Definition at line 213 of file Transform.cpp.
References m_mdir, m_minv, and Transform().
Referenced by TLightKit::ComputeLightSourceArea(), trf::ComputeSceneTreeMap(), and InstanceNode::SetIntersectionTransform().
Ptr<Matrix4x4> Transform::GetMatrix () const [inline]
Definition at line 80 of file Transform.h.
References m_mdir.
Referenced by tgf::MatrixFromTransform(), and operator<<().
Vector3D Transform::multDirMatrix (const Vector3D & src) const
Definition at line 247 of file Transform.cpp.
References m_mdir.
Vector3D Transform::multVecMatrix (const Vector3D & src) const
Definition at line 224 of file Transform.cpp.
References m_mdir.
Ray Transform::operator() (const Ray & ray) const
Definition at line 136 of file Transform.cpp.
References Ray::direction(), Ray::maxt, Ray::mint, Ray::origin, and Ray::setDirection().
void Transform::operator() (const Ray & ray, Ray & transformedRay) const
Definition at line 148 of file Transform.cpp.
References Ray::direction(), Ray::maxt, Ray::mint, Ray::origin, and Ray::setDirection().
void Transform::operator() (const NormalVector & normal, NormalVector & transformedNormal) const
Definition at line 129 of file Transform.cpp.
References m_minv, NormalVector::x, NormalVector::y, and NormalVector::z.
void Transform::operator() (const Vector3D & vector, Vector3D & transformedVector) const
Definition at line 115 of file Transform.cpp.
References m_mdir, Vector3D::x, Vector3D::y, and Vector3D::z.
void Transform::operator() (const Point3D & point, Point3D & transformedPoint) const
Definition at line 98 of file Transform.cpp.
References m_mdir, Point3D::x, Point3D::y, and Point3D::z.
NormalVector Transform::operator() (const NormalVector & normal) const
Definition at line 122 of file Transform.cpp.
References m_minv, NormalVector::x, NormalVector::y, and NormalVector::z.
void Transform::operator() (const BBox & bbox, BBox & transformedBbox) const
Definition at line 172 of file Transform.cpp.
References BBox::pMax, BBox::pMin, Union(), Point3D::x, Point3D::y, and Point3D::z.
BBox Transform::operator() (const BBox & bbox) const
Definition at line 158 of file Transform.cpp.
References BBox::pMax, BBox::pMin, Union(), Point3D::x, Point3D::y, and Point3D::z.
Point3D Transform::operator() (const Point3D & point) const
Definition at line 86 of file Transform.cpp.
References m_mdir, Point3D::x, Point3D::y, and Point3D::z.
Vector3D Transform::operator() (const Vector3D & vector) const
Definition at line 108 of file Transform.cpp.
References m_mdir, Vector3D::x, Vector3D::y, and Vector3D::z.
Transform Transform::operator* (const Transform & rhs) const
Definition at line 185 of file Transform.cpp.
References m_mdir, m_minv, Mul(), and Transform().
bool Transform::operator== (const Transform & mat) const
Definition at line 192 of file Transform.cpp.
References tgc::Epsilon, and m_mdir.
bool Transform::SwapsHandedness () const
Definition at line 265 of file Transform.cpp.
References m_mdir.
Transform Transform::Transpose () const
Definition at line 218 of file Transform.cpp.
References m_mdir, and Transform().
Member Data Documentation
Ptr<Matrix4x4> Transform::m_mdir [private]
Definition at line 88 of file Transform.h.
Referenced by GetInverse(), GetMatrix(), multDirMatrix(), multVecMatrix(), operator()(), operator*(), operator==(), SwapsHandedness(), Transform(), and Transpose().
Ptr<Matrix4x4> Transform::m_minv [private]
Definition at line 89 of file Transform.h.
Referenced by GetInverse(), operator()(), operator*(), and Transform().
The documentation for this class was generated from the following files:
Transform.h
Transform.cpp