Tonatiuh: Image Class Reference
Image Class Reference
Public Member Functions
Image (QString fileName)
QString country (int x, int y)
void addCountries ()
Private Attributes
QStringList countries
Constructor & Destructor Documentation
Image::Image (QString fileName)
References addCountries().
Member Function Documentation
void Image::addCountries ()
References countries.
Referenced by Image().
QString Image::country (int x, int y)
References countries.
Referenced by WorldMap::mouseMoveEvent().
Member Data Documentation
QStringList Image::countries [private]
Referenced by addCountries(), and country().
The documentation for this class was generated from the following files:
Image.h
Image.cpp