Tonatiuh: MapDialog Class Reference
http://tonatiuh.googlecode.com
MapDialog Class Reference
MapDialog class is the dialog to select a localization.
Public Slots
void SetHomeLatitude ()
void SetHomeLongitude ()
void SetHomePosition (double lon, double lat)
void UpdateHomePosition ()
Public Member Functions
MapDialog (QWidget *=0)
~MapDialog ()
void GetHomePosition (double &longitude, double &latitude)
Private Member Functions
QString DefaultMapThemeId () const
Private Attributes
Marble::MapThemeManager * m_mapThemeManager
double m_longitude
double m_latitude
Detailed Description
MapDialog class is the dialog to select a localization.
MapDialog is the dialog show a world map and select a localization in a easy way.
Definition at line 66 of file MapDialog.h.
Constructor & Destructor Documentation
MapDialog::MapDialog (QWidget * parent = 0)
Definition at line 70 of file MapDialog.cpp.
References DefaultMapThemeId(), Ui_MapDialog::latitudeCombo, Ui_MapDialog::latitudeSpin, Ui_MapDialog::legendTab, Ui_MapDialog::longitudeCombo, Ui_MapDialog::longitudeSpin, m_mapThemeManager, Ui_MapDialog::mainSplitter, Ui_MapDialog::mapViewTab, Ui_MapDialog::marbleWidget, Ui_MapDialog::navigationWidget, SetHomeLatitude(), SetHomeLongitude(), Ui_MapDialog::setupUi(), and UpdateHomePosition().
MapDialog::~MapDialog ()
Definition at line 118 of file MapDialog.cpp.
References m_mapThemeManager.
Member Function Documentation
QString MapDialog::DefaultMapThemeId () const [private]
Definition at line 208 of file MapDialog.cpp.
References m_mapThemeManager.
Referenced by MapDialog().
void MapDialog::GetHomePosition (double & longitude, double & latitude)
Definition at line 124 of file MapDialog.cpp.
References m_latitude, and m_longitude.
Referenced by SunPositionCalculatorDialog::on_selectButton_clicked().
void MapDialog::SetHomeLatitude () [slot]
Definition at line 131 of file MapDialog.cpp.
References Ui_MapDialog::latitudeCombo, Ui_MapDialog::latitudeSpin, m_latitude, m_longitude, and Ui_MapDialog::marbleWidget.
Referenced by MapDialog().
void MapDialog::SetHomeLongitude () [slot]
Definition at line 141 of file MapDialog.cpp.
References Ui_MapDialog::longitudeCombo, Ui_MapDialog::longitudeSpin, m_latitude, m_longitude, and Ui_MapDialog::marbleWidget.
Referenced by MapDialog().
void MapDialog::SetHomePosition (double lon, double lat) [slot]
Update home location to lon and lat coordinates. The lon and lat variables are in degree. lon is positive to east and lat is positive for north.
Definition at line 153 of file MapDialog.cpp.
References m_latitude, m_longitude, and Ui_MapDialog::marbleWidget.
Referenced by SunPositionCalculatorDialog::on_selectButton_clicked().
void MapDialog::UpdateHomePosition () [slot]
Update home location to lon and lat coordinates. The lon and lat variables are in degree. lon is positive to east and lat is positive for north.
Definition at line 177 of file MapDialog.cpp.
References Ui_MapDialog::latitudeCombo, Ui_MapDialog::latitudeSpin, Ui_MapDialog::longitudeCombo, Ui_MapDialog::longitudeSpin, m_latitude, m_longitude, and Ui_MapDialog::marbleWidget.
Referenced by MapDialog().
Member Data Documentation
double MapDialog::m_latitude [private]
Definition at line 87 of file MapDialog.h.
Referenced by GetHomePosition(), SetHomeLatitude(), SetHomeLongitude(), SetHomePosition(), and UpdateHomePosition().
double MapDialog::m_longitude [private]
Definition at line 86 of file MapDialog.h.
Referenced by GetHomePosition(), SetHomeLatitude(), SetHomeLongitude(), SetHomePosition(), and UpdateHomePosition().
Marble::MapThemeManager* MapDialog::m_mapThemeManager [private]
Definition at line 85 of file MapDialog.h.
Referenced by DefaultMapThemeId(), MapDialog(), and ~MapDialog().
The documentation for this class was generated from the following files:
MapDialog.h
MapDialog.cpp