TShape Class Reference
http://tonatiuh.googlecode.com
TShape Class Reference
Public Member Functions
virtual bool IntersectP (const Ray &objectRay) const =0
virtual bool Intersect (const Ray &objectRay, double *tHit, DifferentialGeometry *dg) const =0
virtual double GetArea () const =0
virtual double GetVolume () const =0
virtual BBox GetBBox () const =0
virtual QString GetIcon () const =0
virtual Point3D Sample (double u, double v) const =0
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center)=0
virtual void generatePrimitives (SoAction *action)=0
TShape ()
~TShape ()
Private Member Functions
SO_NODE_ABSTRACT_HEADER (TShape)
Detailed Description
Definition at line 51 of file TShape.h.
Constructor & Destructor Documentation
TShape::TShape () [protected]
Definition at line 48 of file TShape.cpp.
TShape::~TShape () [protected]
Definition at line 53 of file TShape.cpp.
Member Function Documentation
virtual void TShape::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) [protected, pure virtual]
Implemented in TCube, and TSquare.
virtual void TShape::generatePrimitives (SoAction * action) [protected, pure virtual]
Implemented in TCube, and TSquare.
virtual double TShape::GetArea () const [pure virtual]
Implemented in TCube, and TSquare.
Referenced by TAnalyzerResultKit::FinalizeCompute().
virtual BBox TShape::GetBBox () const [pure virtual]
Implemented in TCube, and TSquare.
Referenced by TLightKit::ComputeLightSourceArea(), trf::ComputeSceneTreeMap(), and TAnalyzerKit::PrepareCompute().
virtual QString TShape::GetIcon () const [pure virtual]
Implemented in TCube, and TSquare.
Referenced by SceneModel::data().
virtual double TShape::GetVolume () const [pure virtual]
Implemented in TCube, and TSquare.
Referenced by TAnalyzerResultKit::FinalizeCompute().
void TShape::initClass () [static]
Reimplemented in TCube, and TSquare.
Definition at line 43 of file TShape.cpp.
Referenced by main().
virtual bool TShape::Intersect (const Ray & objectRay, double * tHit, DifferentialGeometry * dg) const [pure virtual]
Implemented in TCube, and TSquare.
Referenced by InstanceNode::Intersect().
virtual bool TShape::IntersectP (const Ray & objectRay) const [pure virtual]
Implemented in TCube, and TSquare.
Referenced by TAnalyzerResultKit::Compute().
virtual Point3D TShape::Sample (double u, double v) const [pure virtual]
Implemented in TCube, and TSquare.
TShape::SO_NODE_ABSTRACT_HEADER (TShape) [private]
The documentation for this class was generated from the following files:
TShape.h
TShape.cpp