Tonatiuh: SceneModel Class Reference
http://tonatiuh.googlecode.com
SceneModel Class Reference
Signals
void LightNodeStateChanged (int newState)
Public Member Functions
SceneModel (QObject *parent=0)
~SceneModel ()
void Clear ()
void SetCoinRoot (SoSeparator &coinRoot)
void SetCoinScene (TSceneKit &coinScene)
QModelIndex index (int row, int column, const QModelIndex &parentModelIndex=QModelIndex()) const
int rowCount (const QModelIndex &parentModelIndex) const
int columnCount (const QModelIndex &) const
QModelIndex parent (const QModelIndex &childModelIndex) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QVariant data (const QModelIndex &modelIndex, int role=Qt::DisplayRole) const
Qt::ItemFlags flags (const QModelIndex &index) const
Qt::DropActions supportedDropActions () const
Qt::DropActions supportedDragActions () const
bool Cut (SoBaseKit &coinParent, int row)
QModelIndex IndexFromNodeUrl (QString nodeUrl) const
QModelIndex IndexFromPath (const SoNodeKitPath &coinNodePath) const
int InsertCoinNode (SoNode &coinChild, SoBaseKit &coinParent)
void InsertLightNode (TLightKit &coinLight)
InstanceNode * NodeFromIndex (const QModelIndex &modelIndex) const
SoNodeKitPath * PathFromIndex (const QModelIndex &modelIndex) const
bool Paste (tgc::PasteType type, SoBaseKit &coinParent, SoNode &coinChild, int row)
void RemoveCoinNode (int row, SoBaseKit &coinParent)
void RemoveLightNode (TLightKit &coinLight)
void PrepareAnalyze ()
void FinalyzeAnalyze (double raydensity)
void DisplayAnalyzeResults ()
void ResetAnalyzeValues ()
bool SetNodeName (SoNode *coinChild, QString newName)
void UpdateSceneModel ()
void DisconnectAllTrackers ()
void ReconnectAllTrackers ()
Private Member Functions
void DeleteInstanceTree (InstanceNode &instanceNode)
void SetRoot ()
void SetLight ()
void SetConcentrator ()
InstanceNode * AddInstanceNode (InstanceNode &instanceNodeParent, SoNode *separatorKit)
void GenerateInstanceTree (InstanceNode &instanceParent)
void GenerateTShapeKitSubTree (InstanceNode &instanceNodeParent, SoNode *parentNode)
void GenerateTSeparatorKitSubTree (InstanceNode &instanceNodeParent, SoNode *parentNode)
Private Attributes
SoSeparator * m_coinRoot
TSceneKit * m_coinScene
InstanceNode * m_instanceRoot
InstanceNode * m_instanceConcentrator
std::map< SoNode *, QList
< InstanceNode * > > m_mapCoinQt
Detailed Description
Definition at line 56 of file SceneModel.h.
Constructor & Destructor Documentation
SceneModel::SceneModel (QObject * parent = 0)
Creates an empty model.
Definition at line 68 of file SceneModel.cpp.
SceneModel::~SceneModel ()
Destroys the model.
Definition at line 77 of file SceneModel.cpp.
References Clear().
Member Function Documentation
InstanceNode * SceneModel::AddInstanceNode (InstanceNode & instanceNodeParent, SoNode * separatorKit) [private]
Definition at line 199 of file SceneModel.cpp.
References InstanceNode::AddChild(), and m_mapCoinQt.
Referenced by GenerateTSeparatorKitSubTree(), GenerateTShapeKitSubTree(), and SetConcentrator().
void SceneModel::Clear ()
Clears the model scene
Clears nodes from the model.
Definition at line 114 of file SceneModel.cpp.
References DeleteInstanceTree(), and m_instanceRoot.
Referenced by SetCoinScene(), MainWindow::StartOver(), and ~SceneModel().
int SceneModel::columnCount (const QModelIndex &) const
Definition at line 294 of file SceneModel.cpp.
bool SceneModel::Cut (SoBaseKit & coinParent, int row)
Cuts the row child from coinParent node.
Returns whether the cut is successfully done.
Definition at line 631 of file SceneModel.cpp.
References InstanceNode::children, DeleteInstanceTree(), index(), m_mapCoinQt, and tgf::SevereError().
Referenced by CmdDeleteTracker::redo(), CmdDelete::redo(), CmdCut::redo(), and CmdPaste::undo().
QVariant SceneModel::data (const QModelIndex & modelIndex, int role = Qt::DisplayRole) const
Definition at line 323 of file SceneModel.cpp.
References TTracker::getIcon(), TMaterial::getIcon(), TShape::GetIcon(), TSeparatorKit::getIcon(), TAnalyzerKit::getIcon(), InstanceNode::GetNode(), m_coinRoot, NodeFromIndex(), and PathFromIndex().
Referenced by NodeNameDelegate::setEditorData().
void SceneModel::DeleteInstanceTree (InstanceNode & instanceNode) [private]
Definition at line 952 of file SceneModel.cpp.
References InstanceNode::children, InstanceNode::GetNode(), InstanceNode::GetParent(), and m_mapCoinQt.
Referenced by Clear(), and Cut().
void SceneModel::DisconnectAllTrackers ()
Definition at line 600 of file SceneModel.cpp.
References InstanceNode::DisconnectAllTrackers(), and m_instanceRoot.
Referenced by MainWindow::DisconnectAllTrackers(), and ScriptRayTracer::SetDisconnectAllTrackers().
void SceneModel::DisplayAnalyzeResults ()
Definition at line 555 of file SceneModel.cpp.
References InstanceNode::DisplayAnalyzeResults(), and m_instanceRoot.
Referenced by FinalyzeAnalyze(), and MainWindow::StartOver().
void SceneModel::FinalyzeAnalyze (double raydensity)
Definition at line 564 of file SceneModel.cpp.
References DisplayAnalyzeResults(), InstanceNode::FinalyzeAnalyze(), and m_instanceRoot.
Qt::ItemFlags SceneModel::flags (const QModelIndex & index) const
Definition at line 605 of file SceneModel.cpp.
void SceneModel::GenerateInstanceTree (InstanceNode & instanceParent) [private]
Definition at line 212 of file SceneModel.cpp.
References GenerateTSeparatorKitSubTree(), GenerateTShapeKitSubTree(), and InstanceNode::GetNode().
Referenced by GenerateTSeparatorKitSubTree(), InsertCoinNode(), Paste(), and SetConcentrator().
void SceneModel::GenerateTSeparatorKitSubTree (InstanceNode & instanceNodeParent, SoNode * parentNode) [private]
Definition at line 247 of file SceneModel.cpp.
References AddInstanceNode(), GenerateInstanceTree(), index(), m_coinScene, and TTracker::SetSceneKit().
Referenced by GenerateInstanceTree().
void SceneModel::GenerateTShapeKitSubTree (InstanceNode & instanceNodeParent, SoNode * parentNode) [private]
Definition at line 235 of file SceneModel.cpp.
References AddInstanceNode().
Referenced by GenerateInstanceTree().
QVariant SceneModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Definition at line 314 of file SceneModel.cpp.
QModelIndex SceneModel::index (int row, int column, const QModelIndex & parentModelIndex = QModelIndex()) const
Definition at line 274 of file SceneModel.cpp.
References InstanceNode::children, m_instanceRoot, and NodeFromIndex().
Referenced by MainWindow::CreateAnalyzerNode(), MainWindow::CreateGroupNode(), MainWindow::CreateMaterial(), MainWindow::CreateShape(), MainWindow::CreateSurfaceNode(), MainWindow::CreateTracker(), Cut(), GenerateTSeparatorKitSubTree(), IndexFromNodeUrl(), IndexFromPath(), InsertCoinNode(), MainWindow::InsertFileComponent(), InsertLightNode(), MainWindow::InsertUserDefinedComponent(), Paste(), RemoveCoinNode(), RemoveLightNode(), and SetNodeName().
QModelIndex SceneModel::IndexFromNodeUrl (QString nodeUrl) const
Returns the index of item with the nodeUrl.
If nodeUrl is not a valid node url, the function returns root node index.
See also:
IndexFromNodeUrl, NodeFromIndex, PathFromIndex.
Definition at line 713 of file SceneModel.cpp.
References InstanceNode::children, index(), and NodeFromIndex().
Referenced by MainWindow::ChangeModelScene(), MainWindow::Copy(), MainWindow::Cut(), MainWindow::DefineSunLight(), MainWindow::Delete(), ExportDialog::ExportDialog(), MainWindow::ExportPhotonMap(), ScriptRayTracer::IsValidSurface(), MainWindow::Paste(), MainWindow::SelectNode(), ScriptRayTracer::SetExportSurface(), MainWindow::SetupTreeView(), MainWindow::SetValue(), and MainWindow::StartOver().
QModelIndex SceneModel::IndexFromPath (const SoNodeKitPath & coinNodePath) const
Returns the index of item with the coinNodePath.
If coinNodePath is not a valid node path, the function returns root node index.
See also:
IndexFromNodeUrl, NodeFromIndex, PathFromIndex.
Definition at line 759 of file SceneModel.cpp.
References InstanceNode::children, index(), m_instanceRoot, and tgf::SevereError().
Referenced by MainWindow::SelectionFinish(), and MainWindow::StartManipulation().
int SceneModel::InsertCoinNode (SoNode & coinChild, SoBaseKit & coinParent)
Definition at line 423 of file SceneModel.cpp.
References GenerateInstanceTree(), index(), InstanceNode::InsertChild(), and m_mapCoinQt.
Referenced by TAnalyzerKit::PrepareCompute(), CmdInsertTracker::redo(), CmdInsertShapeKit::redo(), CmdInsertShape::redo(), CmdInsertSeparatorKit::redo(), CmdInsertMaterial::redo(), and CmdInsertAnalyzerKit::redo().
void SceneModel::InsertLightNode (TLightKit & coinLight)
Insert a light node to the model. If the model has an other light node, the previous node will be deleted.
Definition at line 482 of file SceneModel.cpp.
References TLightKit::azimuth, InstanceNode::children, index(), InstanceNode::InsertChild(), LightNodeStateChanged(), m_coinRoot, m_coinScene, m_instanceRoot, TTracker::SetAzimuthAngle(), TTracker::SetZenithAngle(), and TLightKit::zenith.
Referenced by CmdLightKitModified::redo(), and SetLight().
void SceneModel::LightNodeStateChanged (int newState) [signal]
Referenced by InsertLightNode(), and RemoveLightNode().
InstanceNode * SceneModel::NodeFromIndex (const QModelIndex & modelIndex) const
Definition at line 281 of file SceneModel.cpp.
References m_instanceRoot.
Referenced by ExportDialog::accept(), MainWindow::ChangeGridSettings(), MainWindow::ChangeModelScene(), MainWindow::ChangeNodeName(), MainWindow::ChangeSelection(), CmdChangeNodeName::CmdChangeNodeName(), CmdCopy::CmdCopy(), CmdCut::CmdCut(), CmdDelete::CmdDelete(), CmdDeleteTracker::CmdDeleteTracker(), CmdInsertAnalyzerKit::CmdInsertAnalyzerKit(), CmdInsertSeparatorKit::CmdInsertSeparatorKit(), CmdInsertShapeKit::CmdInsertShapeKit(), CmdInsertTracker::CmdInsertTracker(), CmdPaste::CmdPaste(), MainWindow::CreateAnalyzerNode(), MainWindow::CreateGroupNode(), MainWindow::CreateMaterial(), MainWindow::CreateShape(), MainWindow::CreateSurfaceNode(), MainWindow::CreateTracker(), data(), MainWindow::DefineSunLight(), MainWindow::Delete(), SceneModelView::dropEvent(), MainWindow::ExportPhotonMap(), MainWindow::FinishManipulation(), ExportDialog::GetSelectedSurface(), index(), IndexFromNodeUrl(), MainWindow::InsertFileComponent(), MainWindow::InsertUserDefinedComponent(), ScriptRayTracer::IsValidSurface(), MainWindow::ItemDragAndDrop(), MainWindow::ItemDragAndDropCopy(), parent(), MainWindow::Paste(), PathFromIndex(), MainWindow::ReadyForRaytracing(), rowCount(), MainWindow::SaveComponent(), MainWindow::SetAimingPointRelativity(), NodeNameDelegate::setEditorData(), ScriptRayTracer::SetExportSurface(), ScriptRayTracer::SetSunPositionToScene(), MainWindow::SetValue(), MainWindow::ShowMenu(), MainWindow::SoManip_to_SoTransform(), MainWindow::SoTransform_to_SoCenterballManip(), MainWindow::SoTransform_to_SoHandleBoxManip(), MainWindow::SoTransform_to_SoJackManip(), MainWindow::SoTransform_to_SoTabBoxManip(), MainWindow::SoTransform_to_SoTrackballManip(), MainWindow::SoTransform_to_SoTransformBoxManip(), MainWindow::SoTransform_to_SoTransformerManip(), MainWindow::StartOver(), and ScriptRayTracer::Trace().
QModelIndex SceneModel::parent (const QModelIndex & childModelIndex) const
Definition at line 299 of file SceneModel.cpp.
References InstanceNode::children, InstanceNode::GetParent(), and NodeFromIndex().
Referenced by SceneModelView::dropEvent(), and PathFromIndex().
bool SceneModel::Paste (tgc::PasteType type, SoBaseKit & coinParent, SoNode & coinNode, int row)
Adds a child to coinParent as row child. If type is tgc::Copied, the added child is a copy of coinNode. But the type is tgc::Shared the node is shared with previous parent. Return true if the paste action is correctly done. Otherwise returns false.
Definition at line 811 of file SceneModel.cpp.
References tgc::Copied, GenerateInstanceTree(), TSeparatorKit::getPart(), index(), InstanceNode::InsertChild(), m_mapCoinQt, tgf::SevereError(), and tgc::Shared.
Referenced by CmdPaste::redo(), CmdDeleteTracker::undo(), CmdDelete::undo(), and CmdCut::undo().
SoNodeKitPath * SceneModel::PathFromIndex (const QModelIndex & modelIndex) const
Definition at line 982 of file SceneModel.cpp.
References InstanceNode::GetNode(), InstanceNode::GetParent(), m_coinRoot, m_coinScene, NodeFromIndex(), parent(), and tgf::SevereError().
Referenced by data().
void SceneModel::PrepareAnalyze ()
Definition at line 550 of file SceneModel.cpp.
References m_instanceRoot, and InstanceNode::PrepareAnalyze().
Referenced by MainWindow::Run(), and ScriptRayTracer::Trace().
void SceneModel::ReconnectAllTrackers ()
Definition at line 594 of file SceneModel.cpp.
References m_coinScene, m_instanceRoot, and InstanceNode::ReconnectAllTrackers().
Referenced by MainWindow::DisconnectAllTrackers(), and ScriptRayTracer::SetDisconnectAllTrackers().
void SceneModel::RemoveCoinNode (int row, SoBaseKit & coinParent)
Definition at line 513 of file SceneModel.cpp.
References InstanceNode::children, InstanceNode::GetNode(), index(), and m_mapCoinQt.
Referenced by TAnalyzerKit::RemoveResult(), CmdInsertTracker::undo(), CmdInsertShapeKit::undo(), CmdInsertShape::undo(), CmdInsertSeparatorKit::undo(), CmdInsertMaterial::undo(), and CmdInsertAnalyzerKit::undo().
void SceneModel::RemoveLightNode (TLightKit & coinLight)
Definition at line 570 of file SceneModel.cpp.
References InstanceNode::children, TTracker::Disconnect(), index(), LightNodeStateChanged(), m_coinRoot, m_coinScene, and m_instanceRoot.
Referenced by CmdLightKitModified::undo().
void SceneModel::ResetAnalyzeValues ()
Definition at line 560 of file SceneModel.cpp.
References m_instanceRoot, and InstanceNode::ResetAnalyzeValues().
Referenced by MainWindow::ResetAnalyzerValues().
int SceneModel::rowCount (const QModelIndex & parentModelIndex) const
Definition at line 287 of file SceneModel.cpp.
References InstanceNode::children, InstanceNode::GetNode(), and NodeFromIndex().
void SceneModel::SetCoinRoot (SoSeparator & coinRoot)
Sets coinRoot as the model root.
Definition at line 85 of file SceneModel.cpp.
References m_coinRoot, and m_mapCoinQt.
Referenced by MainWindow::SetupModels().
void SceneModel::SetCoinScene (TSceneKit & coinScene)
Sets the model scene to the given coinScene.
Creates nodes for the model to the scene subnodes.
Definition at line 96 of file SceneModel.cpp.
References Clear(), m_coinScene, m_instanceRoot, m_mapCoinQt, SetConcentrator(), SetLight(), and SetRoot().
Referenced by MainWindow::ChangeModelScene(), ScriptRayTracer::SetTonatiuhModelFile(), and MainWindow::SetupModels().
void SceneModel::SetConcentrator () [private]
Definition at line 145 of file SceneModel.cpp.
References AddInstanceNode(), GenerateInstanceTree(), TSeparatorKit::getPart(), m_coinScene, m_instanceConcentrator, m_instanceRoot, TSeparatorKit::setPart(), and TTracker::SetSceneKit().
Referenced by SetCoinScene().
void SceneModel::SetLight () [private]
Definition at line 136 of file SceneModel.cpp.
References InsertLightNode(), and m_coinScene.
Referenced by SetCoinScene().
bool SceneModel::SetNodeName (SoNode * coinChild, QString newName)
Definition at line 899 of file SceneModel.cpp.
References InstanceNode::children, InstanceNode::GetParent(), index(), and m_mapCoinQt.
Referenced by MainWindow::CreateAnalyzerNode(), MainWindow::CreateGroupNode(), MainWindow::CreateSurfaceNode(), CmdPaste::redo(), CmdChangeNodeName::redo(), CmdPaste::undo(), and CmdChangeNodeName::undo().
void SceneModel::SetRoot () [private]
Sets model root
Sets m_coinScene as model.
Definition at line 128 of file SceneModel.cpp.
References m_coinScene, m_instanceRoot, and m_mapCoinQt.
Referenced by SetCoinScene().
Qt::DropActions SceneModel::supportedDragActions () const
Definition at line 622 of file SceneModel.cpp.
Qt::DropActions SceneModel::supportedDropActions () const
Definition at line 617 of file SceneModel.cpp.
void SceneModel::UpdateSceneModel ()
Definition at line 926 of file SceneModel.cpp.
References m_coinScene, BBox::pMax, BBox::pMin, and TLightKit::Update().
Referenced by MainWindow::ChangeSunPosition(), MainWindow::CreateAnalyzerNode(), MainWindow::CreateGroupNode(), MainWindow::CreateMaterial(), MainWindow::CreateShape(), MainWindow::CreateSurfaceNode(), MainWindow::CreateTracker(), MainWindow::Cut(), MainWindow::DefineSunLight(), MainWindow::Delete(), MainWindow::FinishManipulation(), MainWindow::InsertFileComponent(), MainWindow::ItemDragAndDrop(), MainWindow::ItemDragAndDropCopy(), MainWindow::Paste(), MainWindow::Redo(), MainWindow::Run(), MainWindow::SetParameterValue(), MainWindow::SetSunshape(), ScriptRayTracer::Trace(), and MainWindow::Undo().
Member Data Documentation
SoSeparator* SceneModel::m_coinRoot [private]
Definition at line 125 of file SceneModel.h.
Referenced by data(), InsertLightNode(), PathFromIndex(), RemoveLightNode(), and SetCoinRoot().
TSceneKit* SceneModel::m_coinScene [private]
Definition at line 126 of file SceneModel.h.
Referenced by GenerateTSeparatorKitSubTree(), InsertLightNode(), PathFromIndex(), ReconnectAllTrackers(), RemoveLightNode(), SetCoinScene(), SetConcentrator(), SetLight(), SetRoot(), and UpdateSceneModel().
InstanceNode* SceneModel::m_instanceConcentrator [private]
Definition at line 128 of file SceneModel.h.
Referenced by SetConcentrator().
InstanceNode* SceneModel::m_instanceRoot [private]
Definition at line 127 of file SceneModel.h.
Referenced by Clear(), DisconnectAllTrackers(), DisplayAnalyzeResults(), FinalyzeAnalyze(), index(), IndexFromPath(), InsertLightNode(), NodeFromIndex(), PrepareAnalyze(), ReconnectAllTrackers(), RemoveLightNode(), ResetAnalyzeValues(), SetCoinScene(), SetConcentrator(), and SetRoot().
std::map< SoNode*, QList<InstanceNode*> > SceneModel::m_mapCoinQt [private]
Definition at line 129 of file SceneModel.h.
Referenced by AddInstanceNode(), Cut(), DeleteInstanceTree(), InsertCoinNode(), Paste(), RemoveCoinNode(), SetCoinRoot(), SetCoinScene(), SetNodeName(), and SetRoot().
The documentation for this class was generated from the following files:
SceneModel.h
SceneModel.cpp