TransmissivityDialog Class Reference
http://tonatiuh.googlecode.com
TransmissivityDialog Class Reference
Public Slots
void SetValue (SoNode *node, QString paramenterName, QString newValue)
Public Member Functions
TransmissivityDialog (QVector< TTransmissivityFactory * > transmissivityFactoryList, QWidget *parent=0, Qt::WindowFlags f=0)
~TransmissivityDialog ()
TTransmissivity * GetTransmissivity () const
void SetCurrentTransmissivity (TTransmissivity *transmissivity)
Protected Slots
void ChangeTransmissivityType (int index)
Private Attributes
int m_currentTransmissivityIndex
TTransmissivity * m_currentTransmissivity
TTransmissivity * m_newTransmissivity
QMap< QString,
TTransmissivityFactory * > m_transmissivityFactoryList
Detailed Description
Definition at line 51 of file TransmissivityDialog.h.
Constructor & Destructor Documentation
TransmissivityDialog::TransmissivityDialog (QVector< TTransmissivityFactory * > transmissivityFactoryList, QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 51 of file TransmissivityDialog.cpp.
References ChangeTransmissivityType(), m_transmissivityFactoryList, Ui_TransmissivityDialog::setupUi(), SetValue(), Ui_TransmissivityDialog::transmissivityCombo, and Ui_TransmissivityDialog::transmissivityParameters.
TransmissivityDialog::~TransmissivityDialog ()
Definition at line 71 of file TransmissivityDialog.cpp.
Member Function Documentation
void TransmissivityDialog::ChangeTransmissivityType (int index) [protected, slot]
Definition at line 111 of file TransmissivityDialog.cpp.
References TTransmissivityFactory::CreateTTransmissivity(), m_currentTransmissivity, m_currentTransmissivityIndex, m_newTransmissivity, m_transmissivityFactoryList, FieldContainerWidget::SetContainer(), Ui_TransmissivityDialog::transmissivityCombo, and Ui_TransmissivityDialog::transmissivityParameters.
Referenced by TransmissivityDialog().
TTransmissivity * TransmissivityDialog::GetTransmissivity () const
Returns defined transmissivity node.
Definition at line 79 of file TransmissivityDialog.cpp.
References m_newTransmissivity.
void TransmissivityDialog::SetCurrentTransmissivity (TTransmissivity * transmissivity)
Definition at line 96 of file TransmissivityDialog.cpp.
References m_currentTransmissivity, m_currentTransmissivityIndex, and Ui_TransmissivityDialog::transmissivityCombo.
void TransmissivityDialog::SetValue (SoNode * node, QString paramenterName, QString newValue) [slot]
Definition at line 86 of file TransmissivityDialog.cpp.
Referenced by TransmissivityDialog().
Member Data Documentation
TTransmissivity* TransmissivityDialog::m_currentTransmissivity [private]
Definition at line 70 of file TransmissivityDialog.h.
Referenced by ChangeTransmissivityType(), and SetCurrentTransmissivity().
int TransmissivityDialog::m_currentTransmissivityIndex [private]
Definition at line 69 of file TransmissivityDialog.h.
Referenced by ChangeTransmissivityType(), and SetCurrentTransmissivity().
TTransmissivity* TransmissivityDialog::m_newTransmissivity [private]
Definition at line 71 of file TransmissivityDialog.h.
Referenced by ChangeTransmissivityType(), and GetTransmissivity().
QMap< QString, TTransmissivityFactory* > TransmissivityDialog::m_transmissivityFactoryList [private]
Definition at line 72 of file TransmissivityDialog.h.
Referenced by ChangeTransmissivityType(), and TransmissivityDialog().
The documentation for this class was generated from the following files:
TransmissivityDialog.h
TransmissivityDialog.cpp