Tonatiuh: CodeEditArea Class Reference
http://tonatiuh.googlecode.com
CodeEditArea Class Reference
Public Member Functions
CodeEditArea (QWidget *parent=0)
~CodeEditArea ()
int BlockTop (const QTextBlock &block) const
int BlockHeight (const QTextBlock &block) const
Private Slots
void UpdateCurrentLine ()
Detailed Description
Definition at line 13 of file CodeEditArea.h.
Constructor & Destructor Documentation
CodeEditArea::CodeEditArea (QWidget * parent = 0)
Definition at line 47 of file CodeEditArea.cpp.
References UpdateCurrentLine().
CodeEditArea::~CodeEditArea ()
Definition at line 60 of file CodeEditArea.cpp.
Member Function Documentation
int CodeEditArea::BlockHeight (const QTextBlock & block) const
Definition at line 70 of file CodeEditArea.cpp.
Referenced by LineNumberWidget::paintEvent().
int CodeEditArea::BlockTop (const QTextBlock & block) const
Definition at line 65 of file CodeEditArea.cpp.
Referenced by LineNumberWidget::paintEvent().
void CodeEditArea::UpdateCurrentLine () [private, slot]
Definition at line 75 of file CodeEditArea.cpp.
Referenced by CodeEditArea().
The documentation for this class was generated from the following files:
CodeEditArea.h
CodeEditArea.cpp