TSunShape Class Reference
http://tonatiuh.googlecode.com
TSunShape Class Reference
Public Member Functions
virtual void GenerateRayDirection (Vector3D &direction, RandomDeviate &rand) const =0
virtual double GetIrradiance () const =0
virtual double GetThetaMax () const =0
Static Public Member Functions
static void initClass ()
Protected Member Functions
TSunShape ()
virtual ~TSunShape ()
Private Types
typedef SoNode inherited
Private Member Functions
SO_NODE_ABSTRACT_HEADER (TSunShape)
Detailed Description
Definition at line 49 of file TSunShape.h.
Member Typedef Documentation
typedef SoNode TSunShape::inherited [private]
Definition at line 51 of file TSunShape.h.
Constructor & Destructor Documentation
TSunShape::TSunShape () [protected]
Definition at line 48 of file TSunShape.cpp.
TSunShape::~TSunShape () [protected, virtual]
Definition at line 52 of file TSunShape.cpp.
Member Function Documentation
virtual void TSunShape::GenerateRayDirection (Vector3D & direction, RandomDeviate & rand) const [pure virtual]
Implemented in TDefaultSunShape.
Referenced by RayTracer::NewPrimitiveRay(), and RayTracerNoTr::NewPrimitiveRay().
virtual double TSunShape::GetIrradiance () const [pure virtual]
Implemented in TDefaultSunShape.
Referenced by MainWindow::ExportPhotonMap(), and ScriptRayTracer::Trace().
virtual double TSunShape::GetThetaMax () const [pure virtual]
Implemented in TDefaultSunShape.
Referenced by TLightKit::Update().
void TSunShape::initClass () [static]
Reimplemented in TDefaultSunShape.
Definition at line 43 of file TSunShape.cpp.
Referenced by main().
TSunShape::SO_NODE_ABSTRACT_HEADER (TSunShape) [private]
The documentation for this class was generated from the following files:
TSunShape.h
TSunShape.cpp