Tonatiuh: RayTracer Class Reference
http://tonatiuh.googlecode.com
RayTracer Class Reference
Public Types
typedef QPair< TPhotonMap
*, std::vector
< RayTracerPhoton > > result_type
Public Member Functions
RayTracer (InstanceNode *rootNode, InstanceNode *lightNode, TLightShape *lightShape, TSunShape *const lightSunShape, Transform lightToWorld, TTransmissivity *transmissivity, RandomDeviate &rand, QMutex *mutex, TPhotonMap *photonMap)
QPair< TPhotonMap
*, std::vector
< RayTracerPhoton > > operator() (double numberOfRays)
Private Member Functions
bool NewPrimitiveRay (Ray *ray, ParallelRandomDeviate &rand)
Private Attributes
InstanceNode * m_rootNode
InstanceNode * m_lightNode
TLightShape * m_lightShape
const TSunShape * m_lightSunShape
Transform m_lightToWorld
RandomDeviate * m_pRand
QMutex * m_mutex
TPhotonMap * m_photonMap
TTransmissivity * m_transmissivity
std::vector< QPair< int, int > > m_validAreasVector
Detailed Description
Definition at line 63 of file RayTracer.h.
Member Typedef Documentation
typedef QPair< TPhotonMap*, std::vector< RayTracerPhoton > > RayTracer::result_type
Definition at line 77 of file RayTracer.h.
Constructor & Destructor Documentation
RayTracer::RayTracer (InstanceNode * rootNode, InstanceNode * lightNode, TLightShape * lightShape, TSunShape *const lightSunShape, Transform lightToWorld, TTransmissivity * transmissivity, RandomDeviate & rand, QMutex * mutex, TPhotonMap * photonMap)
Definition at line 51 of file RayTracer.cpp.
References TLightShape::GetValidAreasCoord(), m_lightShape, and m_validAreasVector.
Member Function Documentation
bool RayTracer::NewPrimitiveRay (Ray * ray, ParallelRandomDeviate & rand) [private]
Definition at line 74 of file RayTracer.cpp.
References TSunShape::GenerateRayDirection(), m_lightShape, m_lightSunShape, m_lightToWorld, m_validAreasVector, RandomDeviate::RandomDouble(), and TLightShape::Sample().
Referenced by operator()().
QPair< TPhotonMap *, std::vector< RayTracerPhoton > > RayTracer::operator() (double numberOfRays)
Definition at line 91 of file RayTracer.cpp.
References InstanceNode::Analyze(), InstanceNode::Intersect(), TTransmissivity::IsTransmitted(), m_lightNode, m_mutex, m_photonMap, m_pRand, m_rootNode, m_transmissivity, Ray::maxt, NewPrimitiveRay(), and Ray::origin.
Member Data Documentation
InstanceNode* RayTracer::m_lightNode [private]
Definition at line 83 of file RayTracer.h.
Referenced by operator()().
TLightShape* RayTracer::m_lightShape [private]
Definition at line 84 of file RayTracer.h.
Referenced by NewPrimitiveRay(), and RayTracer().
const TSunShape* RayTracer::m_lightSunShape [private]
Definition at line 85 of file RayTracer.h.
Referenced by NewPrimitiveRay().
Transform RayTracer::m_lightToWorld [private]
Definition at line 86 of file RayTracer.h.
Referenced by NewPrimitiveRay().
QMutex* RayTracer::m_mutex [private]
Definition at line 88 of file RayTracer.h.
Referenced by operator()().
TPhotonMap* RayTracer::m_photonMap [private]
Definition at line 89 of file RayTracer.h.
Referenced by operator()().
RandomDeviate* RayTracer::m_pRand [private]
Definition at line 87 of file RayTracer.h.
Referenced by operator()().
InstanceNode* RayTracer::m_rootNode [private]
Definition at line 82 of file RayTracer.h.
Referenced by operator()().
TTransmissivity* RayTracer::m_transmissivity [private]
Definition at line 90 of file RayTracer.h.
Referenced by operator()().
std::vector< QPair< int, int > > RayTracer::m_validAreasVector [private]
Definition at line 91 of file RayTracer.h.
Referenced by NewPrimitiveRay(), and RayTracer().
The documentation for this class was generated from the following files:
RayTracer.h
RayTracer.cpp