Tonatiuh: UpdatesManager Class Reference
http://tonatiuh.googlecode.com
UpdatesManager Class Reference
UpdateManager class manages Tonatiuh updates.
Public Slots
void CheckLastUpdate ()
void FileDownloadComplete ()
void Read ()
void ReadFile ()
void UpdateDownload (int fileIndex)
Public Member Functions
UpdatesManager (QString currentVersion)
~UpdatesManager ()
void CheckForUpdates ()
Private Member Functions
void DeleteDirOldFiles (QString dirName)
void DeleteOldFiles ()
void DownloadFile (QString urlPath, QString saveFileName)
void RemoveDir (QString dirName)
Private Attributes
QNetworkAccessManager * m_networkAccessManager
QNetworkReply * m_reply
bool m_httpRequestAborted
QString m_osType
QString m_currentVersion
QString m_lastUpdateData
QString m_latestVersion
QMap< QString, QString > m_filelist
QVector< QString > m_executableFilelist
QNetworkReply * m_fileReply
bool m_fileRequestAborted
QFile * m_file
int m_filedownloaded
Detailed Description
UpdateManager class manages Tonatiuh updates.
UpdateManager checks if there is new Tonatiuh updates in the web. This class manages updates download and installation.
Definition at line 59 of file UpdatesManager.h.
Constructor & Destructor Documentation
UpdatesManager::UpdatesManager (QString currentVersion)
Definition at line 58 of file UpdatesManager.cpp.
References DeleteOldFiles(), and m_osType.
UpdatesManager::~UpdatesManager ()
Destroyes manager object.
Definition at line 96 of file UpdatesManager.cpp.
References m_networkAccessManager.
Member Function Documentation
void UpdatesManager::CheckForUpdates ()
Checks for new Tonatiuh updates.
Definition at line 104 of file UpdatesManager.cpp.
References CheckLastUpdate(), m_httpRequestAborted, m_networkAccessManager, m_reply, and Read().
Referenced by MainWindow::on_actionCheckForUpdates_triggered().
void UpdatesManager::CheckLastUpdate () [slot]
Reads latest update version and this version files. If the Sthepanie installed version is oldder, checks if the user want to update to this version.
Definition at line 122 of file UpdatesManager.cpp.
References m_currentVersion, m_executableFilelist, m_filedownloaded, m_filelist, m_httpRequestAborted, m_lastUpdateData, m_latestVersion, m_osType, m_reply, and UpdateDownload().
Referenced by CheckForUpdates().
void UpdatesManager::DeleteDirOldFiles (QString dirName) [private]
Removes dirName directory old files.
Definition at line 354 of file UpdatesManager.cpp.
Referenced by DeleteOldFiles().
void UpdatesManager::DeleteOldFiles () [private]
Removes application old files.
Definition at line 377 of file UpdatesManager.cpp.
References DeleteDirOldFiles().
Referenced by UpdatesManager().
void UpdatesManager::DownloadFile (QString urlPath, QString saveFileName) [private]
Downloads fileName file from updates server.
Definition at line 388 of file UpdatesManager.cpp.
References FileDownloadComplete(), m_file, m_fileReply, m_fileRequestAborted, m_networkAccessManager, and ReadFile().
Referenced by UpdateDownload().
void UpdatesManager::FileDownloadComplete () [slot]
Finishes file download.
Definition at line 230 of file UpdatesManager.cpp.
References m_file, m_filedownloaded, m_fileReply, m_fileRequestAborted, and UpdateDownload().
Referenced by DownloadFile().
void UpdatesManager::Read () [slot]
Reads reply data to m_lastUpdateData.
Definition at line 213 of file UpdatesManager.cpp.
References m_lastUpdateData, and m_reply.
Referenced by CheckForUpdates().
void UpdatesManager::ReadFile () [slot]
Reads reply data to m_file.
Definition at line 222 of file UpdatesManager.cpp.
References m_file, and m_fileReply.
Referenced by DownloadFile().
void UpdatesManager::RemoveDir (QString dirName) [private]
Removes the file hierarchy rooted by dirName.
Definition at line 435 of file UpdatesManager.cpp.
Referenced by UpdateDownload().
void UpdatesManager::UpdateDownload (int fileIndex) [slot]
Definition at line 260 of file UpdatesManager.cpp.
References DownloadFile(), m_executableFilelist, m_filedownloaded, m_filelist, m_latestVersion, m_osType, and RemoveDir().
Referenced by CheckLastUpdate(), and FileDownloadComplete().
Member Data Documentation
QString UpdatesManager::m_currentVersion [private]
Definition at line 87 of file UpdatesManager.h.
Referenced by CheckLastUpdate().
QVector< QString > UpdatesManager::m_executableFilelist [private]
Definition at line 92 of file UpdatesManager.h.
Referenced by CheckLastUpdate(), and UpdateDownload().
QFile* UpdatesManager::m_file [private]
Definition at line 96 of file UpdatesManager.h.
Referenced by DownloadFile(), FileDownloadComplete(), and ReadFile().
int UpdatesManager::m_filedownloaded [private]
Definition at line 97 of file UpdatesManager.h.
Referenced by CheckLastUpdate(), FileDownloadComplete(), and UpdateDownload().
QMap< QString, QString > UpdatesManager::m_filelist [private]
Definition at line 91 of file UpdatesManager.h.
Referenced by CheckLastUpdate(), and UpdateDownload().
QNetworkReply* UpdatesManager::m_fileReply [private]
Definition at line 94 of file UpdatesManager.h.
Referenced by DownloadFile(), FileDownloadComplete(), and ReadFile().
bool UpdatesManager::m_fileRequestAborted [private]
Definition at line 95 of file UpdatesManager.h.
Referenced by DownloadFile(), and FileDownloadComplete().
bool UpdatesManager::m_httpRequestAborted [private]
Definition at line 84 of file UpdatesManager.h.
Referenced by CheckForUpdates(), and CheckLastUpdate().
QString UpdatesManager::m_lastUpdateData [private]
Definition at line 89 of file UpdatesManager.h.
Referenced by CheckLastUpdate(), and Read().
QString UpdatesManager::m_latestVersion [private]
Definition at line 90 of file UpdatesManager.h.
Referenced by CheckLastUpdate(), and UpdateDownload().
QNetworkAccessManager* UpdatesManager::m_networkAccessManager [private]
Definition at line 82 of file UpdatesManager.h.
Referenced by CheckForUpdates(), DownloadFile(), and ~UpdatesManager().
QString UpdatesManager::m_osType [private]
Definition at line 86 of file UpdatesManager.h.
Referenced by CheckLastUpdate(), UpdateDownload(), and UpdatesManager().
QNetworkReply* UpdatesManager::m_reply [private]
Definition at line 83 of file UpdatesManager.h.
Referenced by CheckForUpdates(), CheckLastUpdate(), and Read().
The documentation for this class was generated from the following files:
UpdatesManager.h
UpdatesManager.cpp