TTracker Class Reference
http://tonatiuh.googlecode.com
TTracker Class Reference
Public Member Functions
virtual QString getIcon ()=0
void Disconnect ()
void SetLightAngles (TLightKit *coinLight)
void SetAzimuthAngle (trt::TONATIUH_REAL *azimuthField)
void SetZenithAngle (trt::TONATIUH_REAL *zenithField)
void SetSceneKit (TSceneKit *scene)
void SetAnglesToScene ()
void ConnectParentTranform (SoTransform *parentTransform)
double GetAzimuth ()
double GetZenith ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
TTracker ()
virtual ~TTracker ()
void SetEngineOutput (SoTransform *newTransform)
void SetEngineOutputIdentity ()
void SetEngineOutputRotation (SbRotation rotation)
Vector3D GetGobalSunVector ()
SbVec3f GetGobalSunVect ()
bool IsConnected ()
Protected Attributes
trt::TONATIUH_REAL m_azimuth
TSceneKit * m_scene
trt::TONATIUH_REAL m_zenith
SoEngineOutput outputTranslation
SoEngineOutput outputRotation
SoEngineOutput outputScaleFactor
SoEngineOutput outputScaleOrientation
SoEngineOutput outputCenter
Private Member Functions
SO_NODEENGINE_ABSTRACT_HEADER (TTracker)
virtual void evaluate ()=0
Detailed Description
Definition at line 54 of file TTracker.h.
Constructor & Destructor Documentation
TTracker::TTracker () [protected]
Definition at line 55 of file TTracker.cpp.
TTracker::~TTracker () [protected, virtual]
Definition at line 70 of file TTracker.cpp.
References m_azimuth, m_scene, and m_zenith.
Member Function Documentation
void TTracker::ConnectParentTranform (SoTransform * parentTransform)
Definition at line 104 of file TTracker.cpp.
References outputCenter, outputRotation, outputScaleFactor, outputScaleOrientation, and outputTranslation.
Referenced by GraphicRoot::GraphicRoot(), TSeparatorKit::setPart(), and CmdDeleteTracker::undo().
void TTracker::Disconnect ()
Definition at line 77 of file TTracker.cpp.
References m_azimuth, and m_zenith.
Referenced by InstanceNode::DisconnectAllTrackers(), CmdDeleteTracker::redo(), SceneModel::RemoveLightNode(), GraphicRoot::RemoveModel(), and CmdInsertTracker::undo().
virtual void TTracker::evaluate () [private, pure virtual]
Implemented in GraphicRootTracker, TSceneTracker, and TDefaultTracker.
double TTracker::GetAzimuth () [inline]
Definition at line 69 of file TTracker.h.
References m_azimuth.
Referenced by GraphicRootTracker::evaluate(), and TSceneTracker::evaluate().
SbVec3f TTracker::GetGobalSunVect () [protected]
Definition at line 154 of file TTracker.cpp.
References m_azimuth, and m_zenith.
Vector3D TTracker::GetGobalSunVector () [protected]
Definition at line 147 of file TTracker.cpp.
References m_azimuth, and m_zenith.
virtual QString TTracker::getIcon () [pure virtual]
Implemented in GraphicRootTracker, TSceneTracker, and TDefaultTracker.
Referenced by SceneModel::data().
double TTracker::GetZenith () [inline]
Definition at line 70 of file TTracker.h.
References m_zenith.
Referenced by GraphicRootTracker::evaluate(), and TSceneTracker::evaluate().
void TTracker::initClass () [static]
Reimplemented in GraphicRootTracker, TSceneTracker, TDefaultTracker, and TTrackerForAiming.
Definition at line 50 of file TTracker.cpp.
Referenced by main().
bool TTracker::IsConnected () [protected]
Definition at line 140 of file TTracker.cpp.
References m_azimuth, and m_zenith.
Referenced by TDefaultTracker::evaluate(), TSceneTracker::evaluate(), and GraphicRootTracker::evaluate().
void TTracker::SetAnglesToScene ()
Definition at line 162 of file TTracker.cpp.
References TSceneKit::azimuth, m_azimuth, m_scene, m_zenith, and TSceneKit::zenith.
Referenced by TSceneTracker::evaluate().
void TTracker::SetAzimuthAngle (trt::TONATIUH_REAL * azimuthField)
Definition at line 89 of file TTracker.cpp.
References m_azimuth.
Referenced by GraphicRoot::AddModel(), SceneModel::InsertLightNode(), CmdInsertTracker::redo(), and CmdDeleteTracker::undo().
void TTracker::SetEngineOutput (SoTransform * newTransform) [protected]
Definition at line 113 of file TTracker.cpp.
References outputCenter, outputRotation, outputScaleFactor, outputScaleOrientation, and outputTranslation.
void TTracker::SetEngineOutputIdentity () [protected]
Definition at line 131 of file TTracker.cpp.
References outputCenter, outputRotation, outputScaleFactor, outputScaleOrientation, and outputTranslation.
Referenced by TDefaultTracker::evaluate().
void TTracker::SetEngineOutputRotation (SbRotation rotation) [protected]
Definition at line 122 of file TTracker.cpp.
References outputCenter, outputRotation, outputScaleFactor, outputScaleOrientation, and outputTranslation.
Referenced by GraphicRootTracker::evaluate(), and TSceneTracker::evaluate().
void TTracker::SetLightAngles (TLightKit * coinLight)
Definition at line 83 of file TTracker.cpp.
References TLightKit::azimuth, m_azimuth, m_zenith, and TLightKit::zenith.
Referenced by InstanceNode::ReconnectAllTrackers().
void TTracker::SetSceneKit (TSceneKit * scene)
Definition at line 99 of file TTracker.cpp.
References m_scene.
Referenced by GraphicRoot::AddModel(), MainWindow::CreateTracker(), SceneModel::GenerateTSeparatorKitSubTree(), GraphicRoot::RemoveModel(), and SceneModel::SetConcentrator().
void TTracker::SetZenithAngle (trt::TONATIUH_REAL * zenithField)
Definition at line 94 of file TTracker.cpp.
References m_zenith.
Referenced by GraphicRoot::AddModel(), SceneModel::InsertLightNode(), CmdInsertTracker::redo(), and CmdDeleteTracker::undo().
TTracker::SO_NODEENGINE_ABSTRACT_HEADER (TTracker) [private]
Member Data Documentation
trt::TONATIUH_REAL TTracker::m_azimuth [protected]
Definition at line 85 of file TTracker.h.
Referenced by Disconnect(), GetAzimuth(), GetGobalSunVect(), GetGobalSunVector(), GraphicRootTracker::GraphicRootTracker(), IsConnected(), SetAnglesToScene(), SetAzimuthAngle(), SetLightAngles(), TDefaultTracker::TDefaultTracker(), TSceneTracker::TSceneTracker(), and ~TTracker().
TSceneKit* TTracker::m_scene [protected]
Definition at line 86 of file TTracker.h.
Referenced by SetAnglesToScene(), SetSceneKit(), and ~TTracker().
trt::TONATIUH_REAL TTracker::m_zenith [protected]
Definition at line 87 of file TTracker.h.
Referenced by Disconnect(), GetGobalSunVect(), GetGobalSunVector(), GetZenith(), GraphicRootTracker::GraphicRootTracker(), IsConnected(), SetAnglesToScene(), SetLightAngles(), SetZenithAngle(), TDefaultTracker::TDefaultTracker(), TSceneTracker::TSceneTracker(), and ~TTracker().
SoEngineOutput TTracker::outputCenter [protected]
Definition at line 93 of file TTracker.h.
Referenced by ConnectParentTranform(), GraphicRootTracker::GraphicRootTracker(), SetEngineOutput(), SetEngineOutputIdentity(), SetEngineOutputRotation(), TDefaultTracker::TDefaultTracker(), and TSceneTracker::TSceneTracker().
SoEngineOutput TTracker::outputRotation [protected]
Definition at line 90 of file TTracker.h.
Referenced by ConnectParentTranform(), GraphicRootTracker::GraphicRootTracker(), SetEngineOutput(), SetEngineOutputIdentity(), SetEngineOutputRotation(), TDefaultTracker::TDefaultTracker(), and TSceneTracker::TSceneTracker().
SoEngineOutput TTracker::outputScaleFactor [protected]
Definition at line 91 of file TTracker.h.
Referenced by ConnectParentTranform(), GraphicRootTracker::GraphicRootTracker(), SetEngineOutput(), SetEngineOutputIdentity(), SetEngineOutputRotation(), TDefaultTracker::TDefaultTracker(), and TSceneTracker::TSceneTracker().
SoEngineOutput TTracker::outputScaleOrientation [protected]
Definition at line 92 of file TTracker.h.
Referenced by ConnectParentTranform(), GraphicRootTracker::GraphicRootTracker(), SetEngineOutput(), SetEngineOutputIdentity(), SetEngineOutputRotation(), TDefaultTracker::TDefaultTracker(), and TSceneTracker::TSceneTracker().
SoEngineOutput TTracker::outputTranslation [protected]
Definition at line 89 of file TTracker.h.
Referenced by ConnectParentTranform(), GraphicRootTracker::GraphicRootTracker(), SetEngineOutput(), SetEngineOutputIdentity(), SetEngineOutputRotation(), TDefaultTracker::TDefaultTracker(), and TSceneTracker::TSceneTracker().
The documentation for this class was generated from the following files:
TTracker.h
TTracker.cpp