Tonatiuh: CodeEditorWidget Class Reference
http://tonatiuh.googlecode.com
CodeEditorWidget Class Reference
Public Slots
void NewScriptFile ()
void OpenScriptFile ()
void UpdateCodeEditorWidth (int width)
Signals
void FileOpened (QString fileName)
void FileSaved (QString fileName)
void RunScript ()
void Warging (QString message)
Public Member Functions
CodeEditorWidget (QWidget *parent=0, Qt::WindowFlags f=0)
~CodeEditorWidget ()
QTextDocument * Document () const
bool OkToContinue ()
void OpenScriptFile (QString fileName)
Private Slots
void Run ()
bool SaveAsScriptFile ()
bool SaveScript ()
Private Member Functions
bool SaveScriptFile (const QString &fileName)
void SetupToolbar ()
void StartDocument (QString fileName)
Private Attributes
QString m_currentScritFileName
Detailed Description
Definition at line 57 of file CodeEditorWidget.h.
Constructor & Destructor Documentation
CodeEditorWidget::CodeEditorWidget (QWidget * parent = 0, Qt::WindowFlags f = 0)
Creates a new code editor widget.
Definition at line 55 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor, Ui_CodeEditorWidget::lineNumberWidget, LineNumberWidget::SetCodeEditor(), SetupToolbar(), and Ui_CodeEditorWidget::setupUi().
CodeEditorWidget::~CodeEditorWidget ()
Destroys editor.
Definition at line 73 of file CodeEditorWidget.cpp.
Member Function Documentation
QTextDocument * CodeEditorWidget::Document () const
Definition at line 79 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor.
Referenced by ScriptEditorDialog::RunScript().
void CodeEditorWidget::FileOpened (QString fileName) [signal]
Referenced by NewScriptFile(), and StartDocument().
void CodeEditorWidget::FileSaved (QString fileName) [signal]
Referenced by SaveScriptFile().
void CodeEditorWidget::NewScriptFile () [slot]
Creates a new empty script.
Before creates the new scripts, it verifies if the current script can be closed.
Definition at line 124 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor, FileOpened(), m_currentScritFileName, and OkToContinue().
Referenced by SetupToolbar().
bool CodeEditorWidget::OkToContinue ()
Returns true if the application is ready to start with other script. Otherwise, returns false.
Definition at line 88 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor, and SaveScript().
Referenced by ScriptEditorDialog::closeEvent(), NewScriptFile(), and OpenScriptFile().
void CodeEditorWidget::OpenScriptFile () [slot]
Opens a script file into the script editor and sets this file as current file.
A dialog is created to select an existing script file.
Before open the selected script, it verifies if the current script can be closed.
Definition at line 145 of file CodeEditorWidget.cpp.
References OkToContinue(), and StartDocument().
Referenced by SetupToolbar().
void CodeEditorWidget::OpenScriptFile (QString fileName)
Opens the script saved at fileName.
Definition at line 111 of file CodeEditorWidget.cpp.
References OkToContinue(), and StartDocument().
Referenced by ScriptEditorDialog::OpenScriptFile().
void CodeEditorWidget::Run () [private, slot]
Executes the code editor script.
Definition at line 169 of file CodeEditorWidget.cpp.
References RunScript().
Referenced by SetupToolbar().
void CodeEditorWidget::RunScript () [signal]
Referenced by Run().
bool CodeEditorWidget::SaveAsScriptFile () [private, slot]
Returns true if script is correctly saved. Otherwise, returns false. A file dialog is created to select a file.
See also:
SaveScriptFile, SaveFile.
Definition at line 179 of file CodeEditorWidget.cpp.
References SaveScriptFile().
Referenced by SaveScript(), and SetupToolbar().
bool CodeEditorWidget::SaveScript () [private, slot]
Saves the editor code in the file defined as current. If a current file is not defined, it calls to SaveAsScriptFile to define a current file.
See also:
SaveScriptFile, SaveAsScriptFile.
Definition at line 204 of file CodeEditorWidget.cpp.
References m_currentScritFileName, SaveAsScriptFile(), and SaveScriptFile().
Referenced by OkToContinue(), and SetupToolbar().
bool CodeEditorWidget::SaveScriptFile (const QString & fileName) [private]
Returns true if the scripts is correctly saved into the the given fileName. Otherwise, returns false.
See also:
SaveAsScriptFile, SaveScript.
Definition at line 216 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor, FileSaved(), and m_currentScritFileName.
Referenced by SaveAsScriptFile(), and SaveScript().
void CodeEditorWidget::SetupToolbar () [private]
Creates connector for toolbar buttons.
Definition at line 253 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor, Ui_CodeEditorWidget::copyButton, Ui_CodeEditorWidget::cutButton, Ui_CodeEditorWidget::newButton, NewScriptFile(), Ui_CodeEditorWidget::openButton, OpenScriptFile(), Ui_CodeEditorWidget::pasteButton, Ui_CodeEditorWidget::redoButton, Run(), Ui_CodeEditorWidget::runButton, Ui_CodeEditorWidget::saveAsButton, SaveAsScriptFile(), Ui_CodeEditorWidget::saveButton, SaveScript(), and Ui_CodeEditorWidget::undoButton.
Referenced by CodeEditorWidget().
void CodeEditorWidget::StartDocument (QString fileName) [private]
Sets the code editor's contents to fileName contents and sets the currents file to fileName.
Definition at line 274 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor, FileOpened(), and m_currentScritFileName.
Referenced by OpenScriptFile().
void CodeEditorWidget::UpdateCodeEditorWidth (int width) [slot]
Updates code editor width.
Definition at line 244 of file CodeEditorWidget.cpp.
References Ui_CodeEditorWidget::codeEditor, LineNumberWidget::LineNumberAreaWidth(), and Ui_CodeEditorWidget::lineNumberWidget.
void CodeEditorWidget::Warging (QString message) [signal]
Member Data Documentation
QString CodeEditorWidget::m_currentScritFileName [private]
Definition at line 90 of file CodeEditorWidget.h.
Referenced by NewScriptFile(), SaveScript(), SaveScriptFile(), and StartDocument().
The documentation for this class was generated from the following files:
CodeEditorWidget.h
CodeEditorWidget.cpp