Tonatiuh: TAnalyzerResultKit Class Reference
http://tonatiuh.googlecode.com
TAnalyzerResultKit Class Reference
TAnalyzerResultKit class groups what is necessary to the shape.
Public Member Functions
TAnalyzerResultKit ()
bool IntersectP (const Ray &ray) const
void Compute (std::vector< Ray > *raysWays, Transform *m_transformWTO, QMutex *mutex)
void PrepareCompute ()
void FinalizeCompute (double raydensity, Transform *m_transformWTO)
void DisplayResult (int typeOfDisplay, SoNodeKitListPart *levelList)
void ResetValues ()
QString getIcon ()
Static Public Member Functions
static void initClass ()
Private Types
typedef TShapeKit inherited
Private Member Functions
SO_KIT_HEADER (TAnalyzerResultKit)
SO_KIT_CATALOG_ENTRY_HEADER (result)
virtual ~TAnalyzerResultKit ()
Private Attributes
TAnalyzerResult * analyzerResult
TShape * tshape
Detailed Description
TAnalyzerResultKit class groups what is necessary to the shape.
TAnalyzerResultKit groups the shape geometry, material and the transformation.
Definition at line 63 of file TAnalyzerResultKit.h.
Member Typedef Documentation
typedef TShapeKit TAnalyzerResultKit::inherited [private]
Reimplemented from TShapeKit.
Definition at line 65 of file TAnalyzerResultKit.h.
Constructor & Destructor Documentation
TAnalyzerResultKit::TAnalyzerResultKit ()
Constructor.
Definition at line 78 of file TAnalyzerResultKit.cpp.
References analyzerResult, and tshape.
TAnalyzerResultKit::~TAnalyzerResultKit () [private, virtual]
Destroys the TAnalyzerResultKit object.
Definition at line 93 of file TAnalyzerResultKit.cpp.
Member Function Documentation
void TAnalyzerResultKit::Compute (std::vector< Ray > * raysWays, Transform * m_transformWTO, QMutex * mutex)
Definition at line 106 of file TAnalyzerResultKit.cpp.
References analyzerResult, TShape::IntersectP(), TAnalyzerResult::numRayIntersected, and tshape.
Referenced by InstanceNode::Analyze().
void TAnalyzerResultKit::DisplayResult (int typeOfDisplay, SoNodeKitListPart * levelList)
Definition at line 160 of file TAnalyzerResultKit.cpp.
References analyzerResult, TAnalyzerResult::currentValue, TAnalyzerLevel::isActive, TAnalyzerLevel::materialColor, TAnalyzerLevel::materialTransparency, TAnalyzerResult::maxValue, TAnalyzerLevel::minValue, and TAnalyzerResult::minValue.
Referenced by TAnalyzerKit::DisplayResults().
void TAnalyzerResultKit::FinalizeCompute (double raydensity, Transform * m_transformWTO)
Definition at line 129 of file TAnalyzerResultKit.cpp.
References analyzerResult, TAnalyzerResult::FinalizeCompute(), TShape::GetArea(), TShape::GetVolume(), tgf::MatrixFromTransform(), and tshape.
Referenced by InstanceNode::FinalyzeAnalyze().
QString TAnalyzerResultKit::getIcon ()
Returns the icon that represents TSeparatorKit nodes.
Definition at line 216 of file TAnalyzerResultKit.cpp.
void TAnalyzerResultKit::initClass () [static]
Sets up initialization for data common to all instances of this class, like submitting necessary information to the Coin type system.
Reimplemented from TShapeKit.
Definition at line 69 of file TAnalyzerResultKit.cpp.
Referenced by main().
bool TAnalyzerResultKit::IntersectP (const Ray & ray) const
Check if ray intersects with the node.
Reimplemented from TShapeKit.
void TAnalyzerResultKit::PrepareCompute ()
Definition at line 98 of file TAnalyzerResultKit.cpp.
References analyzerResult, TAnalyzerResult::numRayIntersected, and tshape.
Referenced by InstanceNode::PrepareAnalyze().
void TAnalyzerResultKit::ResetValues ()
Definition at line 154 of file TAnalyzerResultKit.cpp.
References analyzerResult, and TAnalyzerResult::ResetValues().
Referenced by TAnalyzerKit::ResetValues().
TAnalyzerResultKit::SO_KIT_CATALOG_ENTRY_HEADER (result) [private]
TAnalyzerResultKit::SO_KIT_HEADER (TAnalyzerResultKit) [private]
Member Data Documentation
TAnalyzerResult* TAnalyzerResultKit::analyzerResult [private]
Definition at line 88 of file TAnalyzerResultKit.h.
Referenced by Compute(), DisplayResult(), FinalizeCompute(), PrepareCompute(), ResetValues(), and TAnalyzerResultKit().
TShape* TAnalyzerResultKit::tshape [private]
Definition at line 89 of file TAnalyzerResultKit.h.
Referenced by Compute(), FinalizeCompute(), PrepareCompute(), and TAnalyzerResultKit().
The documentation for this class was generated from the following files:
TAnalyzerResultKit.h
TAnalyzerResultKit.cpp