Tonatiuh: GridSettingsDialog Class Reference
http://tonatiuh.googlecode.com
GridSettingsDialog Class Reference
Public Member Functions
GridSettingsDialog (int xDimension=100, int zDimension=100, double xSpacing=1, double zSpacing=1, QWidget *parent=0)
~GridSettingsDialog ()
int GetXDimension ()
int GetZDimension ()
double GetXSpacing ()
double GetZSpacing ()
bool IsSizeDefined ()
Detailed Description
Definition at line 48 of file GridSettingsDialog.h.
Constructor & Destructor Documentation
GridSettingsDialog::GridSettingsDialog (int xDimension = 100, int zDimension = 100, double xSpacing = 1, double zSpacing = 1, QWidget * parent = 0)
Definition at line 41 of file GridSettingsDialog.cpp.
References Ui_GridSettingsDialog::setupUi(), Ui_GridSettingsDialog::xDimensionSpin, Ui_GridSettingsDialog::xSpacingSpin, Ui_GridSettingsDialog::zDimensionSpin, and Ui_GridSettingsDialog::zSpacingSpin.
GridSettingsDialog::~GridSettingsDialog ()
Definition at line 52 of file GridSettingsDialog.cpp.
Member Function Documentation
int GridSettingsDialog::GetXDimension ()
Definition at line 57 of file GridSettingsDialog.cpp.
References Ui_GridSettingsDialog::xDimensionSpin.
Referenced by MainWindow::ChangeGridSettings().
double GridSettingsDialog::GetXSpacing ()
Definition at line 67 of file GridSettingsDialog.cpp.
References Ui_GridSettingsDialog::xSpacingSpin.
Referenced by MainWindow::ChangeGridSettings().
int GridSettingsDialog::GetZDimension ()
Definition at line 62 of file GridSettingsDialog.cpp.
References Ui_GridSettingsDialog::zDimensionSpin.
Referenced by MainWindow::ChangeGridSettings().
double GridSettingsDialog::GetZSpacing ()
Definition at line 72 of file GridSettingsDialog.cpp.
References Ui_GridSettingsDialog::zSpacingSpin.
Referenced by MainWindow::ChangeGridSettings().
bool GridSettingsDialog::IsSizeDefined ()
Definition at line 78 of file GridSettingsDialog.cpp.
References Ui_GridSettingsDialog::userDefinedRadio.
Referenced by MainWindow::ChangeGridSettings().
The documentation for this class was generated from the following files:
GridSettingsDialog.h
GridSettingsDialog.cpp