Tonatiuh: HorizontalWidget Class Reference
http://tonatiuh.googlecode.com
HorizontalWidget Class Reference
Public Slots
void CoordinatesChanged (cSunCoordinates coordinates)
Public Member Functions
HorizontalWidget (QWidget *parent=0)
~HorizontalWidget ()
Private Member Functions
SoSeparator * AzimuthLine ()
SoSeparator * Ejes () const
SoSeparator * Horizon () const
SoSeparator * Sphere () const
SoSeparator * Star ()
SoSeparator * Text ()
SoSeparator * ZenithLine ()
Private Attributes
QLabel * m_azimuthValue
QLabel * m_zenithValue
SoSeparator * m_rootNode
const double sphereRadio
double m_azimuth
double m_zenith
Detailed Description
Definition at line 49 of file HorizontalWidget.h.
Constructor & Destructor Documentation
HorizontalWidget::HorizontalWidget (QWidget * parent = 0)
Definition at line 64 of file HorizontalWidget.cpp.
References AzimuthLine(), Ejes(), Horizon(), m_azimuth, m_azimuthValue, m_rootNode, m_zenith, m_zenithValue, Sphere(), Star(), Text(), and ZenithLine().
HorizontalWidget::~HorizontalWidget ()
Definition at line 114 of file HorizontalWidget.cpp.
Member Function Documentation
SoSeparator * HorizontalWidget::AzimuthLine () [private]
Definition at line 139 of file HorizontalWidget.cpp.
References m_azimuth, tgc::Pi, sphereRadio, Point3D::x, Point3D::y, and Point3D::z.
Referenced by CoordinatesChanged(), and HorizontalWidget().
void HorizontalWidget::CoordinatesChanged (cSunCoordinates coordinates) [slot]
Definition at line 119 of file HorizontalWidget.cpp.
References AzimuthLine(), cSunCoordinates::dAzimuth, cSunCoordinates::dZenithAngle, m_azimuth, m_azimuthValue, m_rootNode, m_zenith, m_zenithValue, Star(), and ZenithLine().
SoSeparator * HorizontalWidget::Ejes () const [private]
Definition at line 226 of file HorizontalWidget.cpp.
References sphereRadio.
Referenced by HorizontalWidget().
SoSeparator * HorizontalWidget::Horizon () const [private]
Definition at line 254 of file HorizontalWidget.cpp.
References tgc::Pi, and sphereRadio.
Referenced by HorizontalWidget().
SoSeparator * HorizontalWidget::Sphere () const [private]
Definition at line 280 of file HorizontalWidget.cpp.
References sphereRadio.
Referenced by HorizontalWidget().
SoSeparator * HorizontalWidget::Star () [private]
Definition at line 300 of file HorizontalWidget.cpp.
References m_azimuth, m_zenith, tgc::Pi, and sphereRadio.
Referenced by CoordinatesChanged(), and HorizontalWidget().
SoSeparator * HorizontalWidget::Text () [private]
Definition at line 323 of file HorizontalWidget.cpp.
References sphereRadio.
Referenced by HorizontalWidget().
SoSeparator * HorizontalWidget::ZenithLine () [private]
Definition at line 382 of file HorizontalWidget.cpp.
References m_azimuth, m_zenith, tgc::Pi, sphereRadio, Point3D::x, Point3D::y, and Point3D::z.
Referenced by CoordinatesChanged(), and HorizontalWidget().
Member Data Documentation
double HorizontalWidget::m_azimuth [private]
Definition at line 75 of file HorizontalWidget.h.
Referenced by AzimuthLine(), CoordinatesChanged(), HorizontalWidget(), Star(), and ZenithLine().
QLabel* HorizontalWidget::m_azimuthValue [private]
Definition at line 60 of file HorizontalWidget.h.
Referenced by CoordinatesChanged(), and HorizontalWidget().
SoSeparator* HorizontalWidget::m_rootNode [private]
Definition at line 71 of file HorizontalWidget.h.
Referenced by CoordinatesChanged(), and HorizontalWidget().
double HorizontalWidget::m_zenith [private]
Definition at line 76 of file HorizontalWidget.h.
Referenced by CoordinatesChanged(), HorizontalWidget(), Star(), and ZenithLine().
QLabel* HorizontalWidget::m_zenithValue [private]
Definition at line 61 of file HorizontalWidget.h.
Referenced by CoordinatesChanged(), and HorizontalWidget().
const double HorizontalWidget::sphereRadio [private]
Definition at line 73 of file HorizontalWidget.h.
Referenced by AzimuthLine(), Ejes(), Horizon(), Sphere(), Star(), Text(), and ZenithLine().
The documentation for this class was generated from the following files:
HorizontalWidget.h
HorizontalWidget.cpp