Tonatiuh: SceneModelView Class Reference
http://tonatiuh.googlecode.com
SceneModelView Class Reference
Signals
void dragAndDrop (const QModelIndex &newParent, const QModelIndex &item)
void dragAndDropCopy (const QModelIndex &newParent, const QModelIndex &item)
void nodeNameModificated (const QModelIndex &index, const QString &newName)
void showMenu (const QModelIndex &index)
Public Member Functions
SceneModelView (QWidget *parent=0)
~SceneModelView ()
Protected Slots
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
void resizeViewToContents (const QModelIndex &index)
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dragMoveEvent (QDragMoveEvent *event)
void dropEvent (QDropEvent *event)
Private Member Functions
void startDrag (QMouseEvent *event)
Private Attributes
QModelIndex m_currentIndex
NodeNameDelegate * m_iteimsDelegate
QPoint startPos
Detailed Description
Definition at line 46 of file SceneModelView.h.
Constructor & Destructor Documentation
SceneModelView::SceneModelView (QWidget * parent = 0)
Creates a new view for a model. This
Definition at line 55 of file SceneModelView.cpp.
References m_iteimsDelegate, and resizeViewToContents().
SceneModelView::~SceneModelView ()
Destoryes view object.
Definition at line 76 of file SceneModelView.cpp.
References m_iteimsDelegate.
Member Function Documentation
void SceneModelView::closeEditor (QWidget * editor, QAbstractItemDelegate::EndEditHint hint) [protected, slot]
Definition at line 202 of file SceneModelView.cpp.
References m_currentIndex, and nodeNameModificated().
void SceneModelView::currentChanged (const QModelIndex & current, const QModelIndex & previous) [protected, slot]
Sets current as the view current element index.
Definition at line 196 of file SceneModelView.cpp.
References m_currentIndex.
void SceneModelView::dragAndDrop (const QModelIndex & newParent, const QModelIndex & item) [signal]
Referenced by dropEvent().
void SceneModelView::dragAndDropCopy (const QModelIndex & newParent, const QModelIndex & item) [signal]
Referenced by dropEvent().
void SceneModelView::dragEnterEvent (QDragEnterEvent * event) [protected]
Not yet docummented
Definition at line 113 of file SceneModelView.cpp.
void SceneModelView::dragMoveEvent (QDragMoveEvent * event) [protected]
Not yet docummented
Definition at line 122 of file SceneModelView.cpp.
void SceneModelView::dropEvent (QDropEvent * event) [protected]
Not yet docummented
Definition at line 131 of file SceneModelView.cpp.
References dragAndDrop(), dragAndDropCopy(), InstanceNode::GetNode(), SceneModel::NodeFromIndex(), and SceneModel::parent().
void SceneModelView::mouseMoveEvent (QMouseEvent * event) [protected]
Not yet docummented
Definition at line 100 of file SceneModelView.cpp.
References startDrag(), and startPos.
void SceneModelView::mousePressEvent (QMouseEvent * event) [protected]
Not yet docummented
Definition at line 84 of file SceneModelView.cpp.
References showMenu(), and startPos.
void SceneModelView::nodeNameModificated (const QModelIndex & index, const QString & newName) [signal]
Referenced by closeEditor().
void SceneModelView::resizeViewToContents (const QModelIndex & index) [protected, slot]
Resizes the view to the size of its contents.
Definition at line 216 of file SceneModelView.cpp.
Referenced by SceneModelView().
void SceneModelView::showMenu (const QModelIndex & index) [signal]
Referenced by mousePressEvent().
void SceneModelView::startDrag (QMouseEvent * event) [private]
Not yet docummented
Definition at line 224 of file SceneModelView.cpp.
Referenced by mouseMoveEvent().
Member Data Documentation
QModelIndex SceneModelView::m_currentIndex [private]
Definition at line 77 of file SceneModelView.h.
Referenced by closeEditor(), and currentChanged().
NodeNameDelegate* SceneModelView::m_iteimsDelegate [private]
Definition at line 78 of file SceneModelView.h.
Referenced by SceneModelView(), and ~SceneModelView().
QPoint SceneModelView::startPos [private]
Definition at line 79 of file SceneModelView.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following files:
SceneModelView.h
SceneModelView.cpp