Tonatiuh: tonatiuh_script Namespace Reference
http://tonatiuh.googlecode.com
tonatiuh_script Namespace Reference
Functions
int init (QScriptEngine *engine)
QScriptValue tonatiuh_exportAll (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_export (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_filename (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_irradiance (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_numrays (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_numdivisions (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_photon_map (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_random_generator (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_sunposition (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_calculatesun (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_setsunpositiontoscene (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_setdisconnectalltrackers (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_saveas (QScriptContext *context, QScriptEngine *engine)
QScriptValue tonatiuh_trace (QScriptContext *context, QScriptEngine *engine)
Function Documentation
int tonatiuh_script::init (QScriptEngine * engine)
Definition at line 53 of file tonatiuh_script.cpp.
References ScriptRayTracer::Clear(), tonatiuh_calculatesun(), tonatiuh_export(), tonatiuh_exportAll(), tonatiuh_filename(), tonatiuh_irradiance(), tonatiuh_numdivisions(), tonatiuh_numrays(), tonatiuh_photon_map(), tonatiuh_random_generator(), tonatiuh_saveas(), tonatiuh_setdisconnectalltrackers(), tonatiuh_setsunpositiontoscene(), tonatiuh_sunposition(), and tonatiuh_trace().
Referenced by main(), and ScriptEditorDialog::RunScript().
QScriptValue tonatiuh_script::tonatiuh_calculatesun (QScriptContext * context, QScriptEngine * engine)
Definition at line 356 of file tonatiuh_script.cpp.
References cSunCoordinates::dAzimuth, cSunCoordinates::dZenithAngle, ScriptRayTracer::SetSunAzimtuh(), ScriptRayTracer::SetSunElevation(), ScriptRayTracer::SetSunPositionToScene(), and sunpos().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_export (QScriptContext * context, QScriptEngine * engine)
Definition at line 139 of file tonatiuh_script.cpp.
References ScriptRayTracer::GetDir(), ScriptRayTracer::IsValidSurface(), and ScriptRayTracer::SetExportSurface().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_exportAll (QScriptContext * context, QScriptEngine * engine)
Definition at line 106 of file tonatiuh_script.cpp.
References ScriptRayTracer::GetDir(), and ScriptRayTracer::SetExportAll().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_filename (QScriptContext * context, QScriptEngine * engine)
Definition at line 194 of file tonatiuh_script.cpp.
References ScriptRayTracer::GetDir(), and ScriptRayTracer::SetTonatiuhModelFile().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_irradiance (QScriptContext * context, QScriptEngine * engine)
Definition at line 234 of file tonatiuh_script.cpp.
References ScriptRayTracer::SetIrradiance().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_numdivisions (QScriptContext * context, QScriptEngine * engine)
Definition at line 268 of file tonatiuh_script.cpp.
References ScriptRayTracer::SetNumberOfHeightDivisions(), and ScriptRayTracer::SetNumberOfWidthDivisions().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_numrays (QScriptContext * context, QScriptEngine * engine)
Definition at line 251 of file tonatiuh_script.cpp.
References ScriptRayTracer::SetNumberOfRays().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_photon_map (QScriptContext * context, QScriptEngine * engine)
Definition at line 295 of file tonatiuh_script.cpp.
References ScriptRayTracer::IsValidPhotonMapType(), and ScriptRayTracer::SetPhotonMapType().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_random_generator (QScriptContext * context, QScriptEngine * engine)
Definition at line 312 of file tonatiuh_script.cpp.
References ScriptRayTracer::IsValidRandomGeneratorType(), and ScriptRayTracer::SetRandomDeviateType().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_saveas (QScriptContext * context, QScriptEngine * engine)
Definition at line 433 of file tonatiuh_script.cpp.
References ScriptRayTracer::GetDir(), and ScriptRayTracer::Save().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_setdisconnectalltrackers (QScriptContext * context, QScriptEngine * engine)
Definition at line 419 of file tonatiuh_script.cpp.
References ScriptRayTracer::SetDisconnectAllTrackers().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_setsunpositiontoscene (QScriptContext * context, QScriptEngine * engine)
Definition at line 405 of file tonatiuh_script.cpp.
References ScriptRayTracer::SetSunPositionToScene().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_sunposition (QScriptContext * context, QScriptEngine * engine)
Definition at line 332 of file tonatiuh_script.cpp.
References ScriptRayTracer::SetSunAzimtuh(), and ScriptRayTracer::SetSunElevation().
Referenced by init().
QScriptValue tonatiuh_script::tonatiuh_trace (QScriptContext * context, QScriptEngine * engine)
Definition at line 461 of file tonatiuh_script.cpp.
References ScriptRayTracer::Trace().
Referenced by init().