Tonatiuh: trf Namespace Reference
http://tonatiuh.googlecode.com
trf Namespace Reference
Functions
void ComputeSceneTreeMap (InstanceNode *instanceNode, Transform parentWTO, QVector< QPair< TShapeKit *, Transform > > *surfacesList)
void CreatePhotonMap (TPhotonMap *&photonMap, QPair< TPhotonMap *, std::vector< RayTracerPhoton > > photonsList)
int ExportAll (QString fileName, double wPhoton, TPhotonMap *photonMap)
int ExportSurfaceGlobalCoordinates (QString fileName, InstanceNode *selectedSurface, double wPhoton, TPhotonMap *photonMap)
int ExportSurfaceLocalCoordinates (QString fileName, InstanceNode *selectedSurface, double wPhoton, TPhotonMap *photonMap)
SoSeparator * DrawPhotonMapPoints (const TPhotonMap &map)
SoSeparator * DrawPhotonMapRays (const TPhotonMap &map, unsigned long numberOfRays, double fraction)
Function Documentation
void trf::ComputeSceneTreeMap (InstanceNode * instanceNode, Transform parentWTO, QVector< QPair< TShapeKit *, Transform > > * surfacesList) [inline]
Compute a map with the InstanceNodes of sub-tree with top node instanceNode.
The map stores for each InstanceNode its BBox and its transform in global coordinates.
Definition at line 79 of file trf.h.
References InstanceNode::children, TShape::GetBBox(), InstanceNode::GetIntersectionBBox(), Transform::GetInverse(), InstanceNode::GetNode(), InstanceNode::SetIntersectionBBox(), InstanceNode::SetIntersectionTransform(), tgf::TransformFromSoTransform(), and Union().
Referenced by MainWindow::Run(), and ScriptRayTracer::Trace().
void trf::CreatePhotonMap (TPhotonMap *& photonMap, QPair< TPhotonMap *, std::vector< RayTracerPhoton > > photonsList) [inline]
Definition at line 137 of file trf.h.
References Photon::intersectedSurface, Photon::next, and TPhotonMap::StoreRay().
Referenced by MainWindow::Run(), and ScriptRayTracer::Trace().
SoSeparator * trf::DrawPhotonMapPoints (const TPhotonMap & map)
Definition at line 176 of file trf.cpp.
References TPhotonMap::GetAllPhotons(), Point3D::x, Point3D::y, and Point3D::z.
Referenced by MainWindow::ShowRaysIn3DView().
SoSeparator * trf::DrawPhotonMapRays (const TPhotonMap & map, unsigned long numberOfRays, double fraction)
Definition at line 204 of file trf.cpp.
References TPhotonMap::GetAllPhotons(), Photon::next, Photon::pos, Point3D::x, Point3D::y, and Point3D::z.
Referenced by MainWindow::ShowRaysIn3DView().
int trf::ExportAll (QString fileName, double wPhoton, TPhotonMap * photonMap)
Saves to filename file the photonMap all information.
The file first data is the wPhoton. The power per photon in W/m2.
Definition at line 68 of file trf.cpp.
References TPhotonMap::GetAllPhotons(), Photon::id, Photon::next, Photon::pos, Photon::prev, Photon::side, Point3D::x, Point3D::y, and Point3D::z.
Referenced by MainWindow::ExportPhotonMap(), and ScriptRayTracer::SetExportAll().
int trf::ExportSurfaceGlobalCoordinates (QString fileName, InstanceNode * selectedSurface, double wPhoton, TPhotonMap * photonMap)
Saves to filename file the selectedSurface photons in scene global coordinates.
The file first data is the wPhoton. The power per photon in W/m2.
Definition at line 97 of file trf.cpp.
References InstanceNode::GetNode(), TPhotonMap::GetSurfacePhotons(), Photon::id, Photon::next, Photon::pos, Photon::prev, Photon::side, Point3D::x, Point3D::y, and Point3D::z.
Referenced by MainWindow::ExportPhotonMap(), and ScriptRayTracer::SetExportSurface().
int trf::ExportSurfaceLocalCoordinates (QString fileName, InstanceNode * selectedSurface, double wPhoton, TPhotonMap * photonMap)
Saves to filename file the selectedSurface photons in scene surface node local coordinates.
The file first data is the wPhoton. The power per photon in W/m2.
Definition at line 137 of file trf.cpp.
References InstanceNode::GetIntersectionTransform(), InstanceNode::GetNode(), TPhotonMap::GetSurfacePhotons(), Photon::id, Photon::next, Photon::pos, Photon::prev, Photon::side, Point3D::x, Point3D::y, and Point3D::z.
Referenced by MainWindow::ExportPhotonMap(), and ScriptRayTracer::SetExportSurface().