Tonatiuh: Matrix4x4 Struct Reference
Matrix4x4 Struct Reference
Public Member Functions
Matrix4x4 ()
Matrix4x4 (double mat[4][4])
Matrix4x4 (double t00, double t01, double t02, double t03, double t10, double t11, double t12, double t13, double t20, double t21, double t22, double t23, double t30, double t31, double t32, double t33)
Matrix4x4 (const Matrix4x4 &rhs)
Ptr< Matrix4x4 > Transpose () const
Ptr< Matrix4x4 > Inverse () const
bool operator== (const Matrix4x4 &mat) const
Public Attributes
double m [4][4]
Constructor & Destructor Documentation
Matrix4x4::Matrix4x4 ()
References m.
Referenced by Inverse(), and Transpose().
Matrix4x4::Matrix4x4 (double mat[4][4])
References m.
Matrix4x4::Matrix4x4 (double t00, double t01, double t02, double t03, double t10, double t11, double t12, double t13, double t20, double t21, double t22, double t23, double t30, double t31, double t32, double t33)
References m.
Matrix4x4::Matrix4x4 (const Matrix4x4 & rhs)
References m.
Member Function Documentation
Ptr< Matrix4x4 > Matrix4x4::Inverse () const
References m, and Matrix4x4().
bool Matrix4x4::operator== (const Matrix4x4 & mat) const
References tgc::Epsilon, and m.
Ptr< Matrix4x4 > Matrix4x4::Transpose () const
References m, and Matrix4x4().
Member Data Documentation
double Matrix4x4::m[4][4]
Referenced by Inverse(), Matrix4x4(), operator<<(), operator==(), and Transpose().
The documentation for this struct was generated from the following files:
Matrix4x4.h
Matrix4x4.cpp